arduino/arduino-cli

- README.md
- commands/core/install.go
it looks like this slipped in 59c851ed
> use arduino-cli in examples

- commands/commands_test.go
- commands/compile/compile.go
- commands/upload/upload.go
- The exported compiled binary now does not contains the FQBN "config" part anymore. This means that, for example, the default exported file for `arduino:avr:mega:cpu=atmega1280` will be called `Blink.arduino.avr.mega.hex` instead of `Blink.arduino.avr.mega.cpu=atmega1280.hex`.
The change above should fix #64
- The `compile` command now has a `-o, --output` to manually specifiy the output filename for the compiled binary.
- The `upload` command now has a `-i, --input` to manually specify the input filename of the binary to upload to the board.
> Various improvements in compile / upload

- README.md
Added documentation to readme about adding 3rd party cores
> Add documentation about 3rd party cores 

- Gopkg.lock
- vendor/go.bug.st/downloader/downloader.go
Should fix #87.
/cc @wjwieland @OBerghmans
> Fix uint64 un-aligned atomic access

- README.md
- Clarify executable needs to be renamed to proceed with the getting started section
- Not needed for the build from source section
> Clarify install via download

- commands/commands_test.go
- commands/testdata/sketchbook_with_custom_hardware/hardware/test/avr/boards.txt
- commands/testdata/sketchbook_with_custom_hardware/hardware/test/avr/platform.txt
- commands/testdata/sketchbook_with_custom_hardware/hardware/test2/avr/boards.txt
- commands/testdata/sketchbook_with_custom_hardware/hardware/test2/avr/platform.txt
- commands/testdata/sketchbook_with_custom_hardware/test.hex
- commands/upload/upload.go
- configs/configuration.go
- configs/env_vars_serializer.go
- configs/yaml_serializer.go
- Added tests for upload command (parsing only)
- Added check for missing "recipe.output.tmp_file" property
- Fixed check for `upload.tool` existence (it should not check for tool existence but just for the referenced platform, if specified). Should help to fix #83 
Not strictly related to upload, but useful to make tests run more efficiently:
- Downloaded archives are kept in a temporary folder and reused (so they are downloaded only once and not many times)
> Various fix and improvements to "upload"

- .travis.yml
Refactoring the installation of dep in travis.yml follow this guidelines
https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci
> Dep install refactoring

- commands/root/root.go
We will remove support for old-style config in the next release.
This will allow a smooth transition to the new file name.
> Do not bail out if old-style config file is found

- commands/root/root.go
- configs/navigate.go
- configs/navigate_test.go
Fix #150 
/cc @berry0511 @SebCanet
> bugfix: Navigate method didn't work with Windows-style paths

- Taskfile.yml
- auth/auth_test.go
The project currently has a robust test suite that exercises most of the functionalities against the actual http API. This is not very suitable to iterate fast on the code, thus this PR introduces the concept of unit tests in addition to the existing suite that will stay as it is but will be marked as "integration tests".
Integration test functions will contain the string `Integration` in the name, so that the suite can be run with `go test -run integration ./...`. Integration tests will be skipped when running unit tests and we use the `short` option from the Go standard lib to make this easy: each test function will begin like this:
```
if testing.Short() {
t.Skip("skip integration test")
}
```
This way, unit tests will be run with just `go test -short ./...`
To make easier for …
> Introduce new testing layout

- configs/directories.go
This allows user to use a different directory by exporting own value for the $HOME variable.
Follow up of https://github.com/arduino/arduino-cli/pull/169
> Use os.UserHomeDir() for obtaining user's home directory

- .travis.yml
- Taskfile.yml
split test tasks into:
* unit
* integrations
* legacy
Make sure Travis runs all.
> Split test tasks

- README.md
- Taskfile.yml
- version/version.go
This PR bumps the arduino-cli version in order to make the next release 0.3.7-alpha.preview
> bump release version to 0.3.7-alpha.preview

- README.md
This PR adds nightly downloads link under the 'nightly' section.
- A nightly pipeline is producing the artifacts in the links that is currently configured in the Arduino private internal Jenkins instance
- Removed links for arm64 build as at the time of this commit, arm64
builds are not supported
> Add nightly build links under the download section

- README.md
As reported in multiple issues (#138 #191 #271) finding the right FQBN for a board can be difficult.
Improving the documentation may help users to find the relevant information.
Specifically, this PR closes #271 and add little improvement as suggested in #191.
> improve find FQBN FAQ

- arduino/cores/tools.go
- arduino/cores/tools_test.go
> Added arm64 support

- Dockerfiles/CI/Dockerfile
`protoc` will search for include files in the same folder of the binary by default. This will allow us to avoid specifying `-I` explicitly, leaving to the host running the compiler to put things in the right place.
> Move default include files where protoc can find them

- version/version.go
- version/version_test.go
Fixes #283 
I added `time.Format(time.RFC3339)` in version
> Fix time format RFC3339 in version #283

- Taskfile.yml
- arduino/cores/cores.go
- arduino/cores/packageindex/index.go
- arduino/cores/packagemanager/download.go
- arduino/cores/packagemanager/install_uninstall.go
- arduino/cores/packagemanager/loader.go
- arduino/cores/packagemanager/package_manager.go
- arduino/cores/status.go
- cli/core/list.go
- cli/core/upgrade.go
- commands/board/listall.go
- commands/bundled_tools_ctags.go
- commands/bundled_tools_serial_discovery.go
- commands/core/core.go
- commands/core/list.go
- commands/core/search.go
- commands/core/upgrade.go
- commands/daemon/daemon.go
- commands/instances.go
- commands/upload/upload.go
- legacy/builder/add_build_board_property_if_missing.go
- legacy/builder/hardware_loader.go
- legacy/builder/rewrite_hardware_keys.go
- legacy/builder/setup_build_properties.go
- legacy/builder/test/hardware_loader_test.go
- legacy/builder/test/rewrite_hardware_keys_test.go
- legacy/builder/types/context.go
This PR fixes the case where no args are passed to the upgrade command, like:
```
arduino-cli core upgrade
```
Now an upgrade will be performed to any core that is up to date. If all the cores are at the latest version, command is a no op and will exit without errors, providing and info message.
Fixes ~#285~ #273  
I took the opportunity to review the design of the code that lists all the available cores that was depending on the `rpc` package for no reason. Also the api of the old `PlatformList` required a `context` that was never used.
Other minor improvements are commented inline.
> Fix core upgrade

- Dockerfiles/CI/Dockerfile
Be ready to run integration tests under `/test`
> Add Python3.7 to the CI image

- .drone.yml
- Taskfile.yml
- cli/cli_test.go
- version/version_test.go
Let the CI run integration tests, for now the step is expected to fail while we fix the actual issues causing the failure.
> Run integration tests on the CI

- test/test_main.py
Following up discussion at https://github.com/arduino/arduino-cli/issues/96 we ensure that when command has no output nothing will be printed out, even if the selected format was JSON (`docker` cli style).
> Assert output is empty

- cli/daemon/daemon.go
- cli/globals/globals.go
- test/test_main.py
- version/version.go
- version/version_test.go
This proved to be problematic when playing with repeatable builds and the value added is very little.
> Remove build date from the version

- commands/lib/uninstall.go
- commands/lib/utils.go
Cli doesn't fail anymore if a library scheduled for removal is not actually installed.
> Do not exit with an error if lib is not present

- commands/bundled_tools_ctags.go
This PR updates the ctags metadata for the following platforms:
- `aarch64-linux` (arm 64 bit)
- `x86_64-apple` (macOS 64 bit)
In order to force the arduino-cli to download the correct version of the Arduino ctags binary tool (https://github.com/arduino/ctags) for each platform
***regarding the arm 64 bit platforms***
The PR completes the arm64 support effort started in https://github.com/arduino/arduino-cli/pull/204, solving the following error that happened when using the cli built and executed on an arm64 board (i.e. NVIDIA Jetson) 
```
downloading builtin:ctags@5.8-arduino11 tool: tool not available for your OS
```
This PR also solves https://github.com/arduino/arduino-cli/issues/292 together with Arduino CI pipeline configuration to enable the arm64 build.
***regarding the macOS 64 …
> ctags arm64 osx64 support

- README.md
This PR follows https://github.com/arduino/arduino-cli/pull/304
Readme links updated to include `linuxarm64` binaries links and renaming `linuxarm` to `linuxarm32` to have a clear distinction between the two architectures
Updated also instructions as the binaries in the archive are, from now on, always named `arduino-cli`
> updated README.md download links with linuxarm32 and linuxarm64 links

- Taskfile.yml
- appveyor.yml
- test/conftest.py
- test/test_main.py
> Run tests on Appveyor

- .drone.yml
- test/test_main.py
Integration tests were allowed to fail until now, this PR makes them mandatory by skipping tests requiring a serial port (like `board list`) since VMs on drone.io have no serial ports attached.
> Skip tests we cannot run on Drone

- commands/.test-config.yml
- configs/directories.go
Fixes #290.
Also removed an hidden, unused file I've found while searching for references to the default dir.
> Use same default data dir as the IDE on OSX

- commands/core/core.go
This patch falls back to the `BoardsManifest` when the `Boards` is not
available.
When the `Boards` are not installed, hence unavailable, the produced
gRPC instance won't contain the `FQBN` but the `Name` only.
This patch is a kind of a workaround for #277. The name of the boards will be still available, although the `FQBN` cannot be accessed.
Let me know what you think about this patch. Thanks!
> Use `BoardsManifest` if `Boards` is not applicable

- arduino/discovery/discovery.go
Fixes https://github.com/arduino/arduino-cli/issues/306
> Sync board list to avoid race conditions

- .drone.yml
- .gitignore
- .goreleaser.yml
- CONTRIBUTING.md
- Dockerfiles/builder/Dockerfile
- README.md
This PR adds a Dockerfile used to build an image capable to cross compile the CLI for all the supported platforms:
- arduino-cli_0.3.7-alpha.preview-next_Linux_32bit.tar.gz
- arduino-cli_0.3.7-alpha.preview-next_Linux_64bit.tar.gz
- arduino-cli_0.3.7-alpha.preview-next_Linux_ARM64.tar.gz
- arduino-cli_0.3.7-alpha.preview-next_Linux_ARMv7.tar.gz
- arduino-cli_0.3.7-alpha.preview-next_Windows_32bit.zip
- arduino-cli_0.3.7-alpha.preview-next_Windows_64bit.zip
- arduino-cli_0.3.7-alpha.preview-next_macOS_64bit.tar.gz
~**NOTE** this is highly WIP work, because of https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1300211 the image doesn't work ootb. Currently trying to build from https://github.com/multiarch/crossbuild instead of `golang-cross`.~
This PR supersedes #120 and partially …
> Use goreleaser to build the full binary matrix

- .drone.yml
- .goreleaser.yml
This PR adds s3 upload support in .goreleaser.yml via `blob` configuration.
`arduino-downloads-prod-beagle` is the Arduino artifact repository bucket that is configured to allow public download
Used `blob` configuration instead of deprecated` s3` one. 
This requires adding a AWS_DEFAULT_REGION env var to the drone step (together with
the IAM credentials), because this property is missing in the blob config
TODO:
> Goreleaser S3 upload support

- cli/instance/instance.go
- cli/lib/upgrade.go
- commands/core/install.go
- commands/core/uninstall.go
- commands/core/upgrade.go
- commands/daemon/daemon.go
- commands/instances.go
- commands/lib/download.go
- commands/lib/install.go
- commands/lib/list.go
- commands/lib/search.go
- commands/lib/uninstall.go
- commands/lib/upgrade.go
Adding the ability to upgrade single libs vs. just upgrading all or nothing. This will be now possible:
```
arduino-cli lib upgrade WiFiNINA
```
Also in this PR (sorry it got too large)
* fix a bug preventing to show the latest version in `arduino-cli lib list` (an integration test will be added separately to avoid regressions)
* changed the API to avoid passing around useless parameters
> Update single libraries

- .editorconfig
- README.md
- install.sh
This PR adds an `install.sh` script based on the one from `https://github.com/Masterminds/glide` to allow newcomers to simply do:
```
curl https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
```
to install the CLI.
It also updates the README accordingly, showing the various supported install methods. The markdown was also fixed to leverage Github's rendering helpers and show a nice output in the examples.
> Add install script and update install instructions

- README.md
> [skip changelog] Update nightly links and add nightly checksum link

- README.md
Fixes #219 
There's no `Installed` column is search output
> [skip changelog] Fix examples in README

- Dockerfiles/CI/Dockerfile
Now we can have the same version on both drone.io and AppVeyor, see PR #329 for the details.
> [skip changelog] Upgrade protobuf on the CI

- .drone.yml
- appveyor.yml
We can now switch back to a current version of the protocol since the
PR https://github.com/protocolbuffers/protobuf/pull/5044 has been
merged to master a released.
> [skip changelog] Remove protobuf workaround on AppVeyor 

- arduino/cores/packagemanager/identify.go
- cli/board/list.go
- cli/output/table.go
- cli/output/text.go
- commands/board/list.go
- commands/board/list_test.go
- commands/daemon/daemon.go
This PR makes the command `arduino-cli board list` properly work even when a core for the connected board is not installed. It works by querying the Arduino Cloud backend passing VID and PID, hence the CLI must be able to access the Internet for this to work.
> Query the backend to get the fqbn when a core is not installed

- commands/compile/compile.go
- legacy/builder/wipeout_build_path_if_build_options_changed.go
The command should exit early when `--preprocess` or `--show-properties` are passed, since binary artifacts are not produced and command would fail.
EDIT: Now that #337 was merged, this PR fixes #333
> Fix compile error when --preprocess or --show-properties were passed

- install.sh
The Raspberry Pi presents itself as an `armv7l` architecture and with this mapping the install script will download the most appropriate archive for this platform.
> Fix install.sh script so it downloads the right package for ARMv7

- .goreleaser.yml
- install.sh
Fixes #340
Nightly will be available in the archive `arduino-cli_nightly-20190812_Linux_ARMv6.tar.gz`
> Add support for ARM v6

- install.sh
Archive name was wrong, we use Zip to distribute the binaries on Windows.
Fixes #334
> Fix install script for Windows shells

- install.sh
We used to query the GitHub API to get the latest version of the CLI and such calls might be rate limited, specially in shared CI environments.
This PR hits the downloads page directly and `grep`s the HTML contents so no rate limit will be applied. As a side effect, we don't need Python anymore and this will make the install script more robust under Windows shells like MinGW and Msys.
> Do not hit github api to get latest version from install script

- commands/board/list.go
- commands/bundled_tools_serial_discovery.go
Attempt to fix a concurrency issue surfacing when multiple clients at once use the CLI from the gRPC Api. Instead of having the client code calling `Start`, `List` and `Close` in sequence, we only export `List` that will take care of the entire workflow.
> Make the serial discovery execution atomic

- go.mod
- go.sum
- legacy/builder/builder_utils/utils.go
Because of a bug in the properties map checking, the "build options" resulted always "changed" resulting in a full rebuild every time.
The real fix is in the update of the library go-properties-orderedmap.
The rest of the patch is just cosmetic.
> Fix cached build

- .goreleaser.yml
This PR removes additional `=` sign from .goreleaser.yml build config causing wrong commit checksum string in version info
> Fix .goreleaser.yml typo in injecting commit in version string

- .github/workflows/test.yaml
Workflows run on PRs coming from forks are currently broken.
Since secrets aren't available on forks, we only upload coverage on `push`. This might change if Codecov whitelists GitHub, lifting the need for a token.
> [skip changelog] Upload coverage only on push events

- cli/cli.go
- test/test_main.py
This PR adds the `--log-format` option.
Same as you can do with output, let users choose the format of the logged informations to ease parsing the CLI output.
Also accepts uppercase strings when parsing format args, i.e. `--format JSON` will work as good as `--format json`.
> Add an option to format logs with JSON

- README.md
> [skip changelog] [skip ci] Add latest redirect links for nightly builds

- commands/board/list.go
- commands/bundled_tools_serial_discovery.go
This PR fixes some concurrency issues we faced when connecting multiple gRPC client to the same CLI daemon. We don't really know the root cause but the problems went away by making really atomic the execution of the external tool. With this PR, only one function is called by the clients, and this function is responsible for:
* creating the command
* launching the process
* setting up the pipes
* send and receive commands
* closing the pipes
* shutting down (or kill if needed) the process
The function operates within a mutex.
> Rewrite the serial discovery logic

- commands/board/list.go
The call to the cloud API to get board id from vid/pid has to support concurrent usage to be used within the IDE.
> [skip changelog] sync api query

- .goreleaser.yml
Fix the regex we use to exclude commits from the changelog and add more rules to skip `[ci skip]` and `[skip ci]` that likely you don't want to be on the changelog.
Also removed the sorting by commit message, so commits will be sorted by commit sequence (useful to manually redact the changelog).
> [skip changelog] Fix changelog filters

- legacy/builder/builder_utils/utils.go
Port of https://github.com/arduino/arduino-builder/pull/328
When checking for updated core files, don't scan inside UNIX hidden
directories like .git.  Scanning inside a GIT tree for a large project
with many branches could take many minutes of runtime and multiple GB of
RAM.  This was seen in the Arduino core for the ESP8266, but is probably
also an issue for other core development teams.
Fixes https://github.com/arduino/arduino-builder/issues/327
Signed-off-by: Earle F. Philhower, III <earlephilhower@yahoo.com>
> Don't scan hidden directories in arduino-builder (.git, etc.)

- commands/compile/compile.go
- commands/upload/upload.go
- test/.flake8
- test/__init__.py
- test/common.py
- test/conftest.py
- test/test_board.py
- test/test_compile.py
- test/test_lib.py
- test/test_main.py
This PR adds log lines assertions in a "white box" fashion in the python integration testing suite to allow a more flexible testing
The ~~`is_message_in_json_log_lines`~~ `is_message_sequence_in_json_log_traces` function is not optimized as the log produced for each test is currently very small
> Check json logs entries in compile and upload python integration tests

- README.md
- cli/board/list.go
Fixes #191
Now that #336 has been released, the vicious cycle of not knowing the board name if the corresponding core is not available, and not knowing which core to install without the board name, is finally broken.
To help users who are not familiar with the FQBN concept to better understand which core has to be installed, a new column in the output of `board list` was added to show the name of the core that  supports the detected board.
The README was updated accordingly. 
Note: the core name wasn't added to the JSON output because that would require a non trivial amount of code - provided that the JSON output is supposed to be read by a machine and provided that the name of the core can be easily deduced from the data the CLI already provides, my advice is to avoid making the code too …
> Show core name when listing boards

- .github/workflows/stale.yaml
This workflow will:
* Mark an issue with the `stale` label after 15 days of no activity on issues labelled with `waiting for feedback`
* Close an issue after 30 days with the label `stale` attached.
The `stale` labels is automatically removed as soon as somebody leaves a comment on the issue.
> Add a stale bot to help grooming issues

- .github/workflows/stale.yaml
Scheduled runs are failing because `Mark active` can only work when the trigger event is a comment added to an issue.
> [skip changelog] Only run job on comments activity

- install.sh
Failing the install script because the target folder isn't in the PATH is misleading and not always a problem (for example in a CI where you might launch the cli with a full path).
With this change, if the target folder is not in the PATH, a message is printed to warn the user but the install will succeed nevertheless.
It mitigates #407
> Do not fail if install folder is not in PATH

- .github/workflows/test.yaml
Windows End to End testing evidenced CLI return codes issues that are currently under investigation.
This is an example of the error reported by the `test` pipeline
```
================================== FAILURES ===================================
_________________________________ test_search _________________________________
##[error]test\test_lib.py:82: in test_search
assert run_command("lib update-index")
E   AssertionError: assert <Result cmd='cd C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\ArduinoTestWork7 && D:\\a\\arduino-cli\\arduino-cli\\test\\..\\arduino-cli lib update-index' exited=None>
E    +  where <Result cmd='cd C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\ArduinoTestWork7 && …
```
> Disable e2e test on Github Actions windows agent

- cli/core/search.go
Mirror the same function as `lib search` does.
Use `arduino-cli core search` can list all the cores.
Fixes #354
> List cores with core search

- go.mod
- test/test_board.py
> Add a test case for `core search`

- Taskfile.yml
- version/version.go
The default dummy version `0.3.7-alpha.preview` overlaps with a real version and this creates confusion to developers and contributors.
This PR replaces the default version with an explicit dummy version `0.0.0-git`
> Replace default dummy version

- .github/workflows/test.yaml
- test/conftest.py
- test/requirements.txt
- test/test_compile.py
This PR uses a patched version of `invoke` in order to overcome flaky test issue reported in previous PR https://github.com/arduino/arduino-cli/pull/416, and reported also from other users in the `invoke` repo (https://github.com/pyinvoke/invoke/issues/660). 
This PR applies the following changes:
- Adds the patch (https://github.com/pyinvoke/invoke/pull/661) to `test/requirements.txt` 
- Re-enables the windows e2e python test step in the `test` GH Actions workflow
- updates `pytest` to 3.5.1 in `test/requirements.txt`
> Use patched invoke in e2e requirements

- README.md
> [skip ci] [skip changelog] Add latest links for releases in README.md

- commands/board/list.go
Currently if the board wasn't recognized by neither the core or the api call, the port is discarded altogether.
With this PR, the ports detected are always shown, even if there's some hardware attached that couldn't be recognized.
> Add detected port even if the board couldn't be recognized

- commands/compile/compile.go
- legacy/builder/grpc/rpc.go
- legacy/builder/test/builder_test.go
- legacy/builder/test/create_build_options_map_test.go
- legacy/builder/test/load_vid_pid_specific_properties_test.go
- legacy/builder/test/merge_sketch_with_bootloader_test.go
- legacy/builder/test/store_build_options_map_test.go
- legacy/builder/tools_loader.go
- legacy/builder/types/context.go
The ToolsDirs field has been replaced by BuiltInToolsDirs during the big refactoring in the arduino-builder repo.
The intention was to remove ToolsDirs once done, but for some reasons I forgot to remove it.
This commit completes the transition.
> Replace ctx.ToolsDirs with ctx.BuiltInToolsDirs

- legacy/builder/container_setup.go
(I suggest to disable whitespace diff for review)
> builder: try to setup Sketch only when SketchLocation is provided

- commands/compile/compile.go
Some boards do not produce elf file intermediate (i.e those that use
build.preferred_export_format=axf or the like).  This changes the
logic so that it's not an error for and elf file to be missing.
> Only copy elf file if it exists.

- cli/board/attach.go
> Fix panic on missing sketch path

- legacy/builder/container_find_includes.go
Yet another post-builder regression.
> Fix library-cache-miss regression

- cli/cli.go
- cli/daemon/daemon.go
- client_example/go.mod
- client_example/main.go
This PR:
- updates the gRPC `client_example` to align it with the sketch new latest behavior (see #396 ) 
-  applies little cosmetics to `help` printout
> [skip changelog] gRPC "client_example" refresh

- cli/board/details.go
- cli/board/list.go
- cli/board/listall.go
- cli/cli.go
- cli/config/dump.go
- cli/config/init.go
- cli/core/list.go
- cli/core/search.go
- cli/feedback/exported.go
- cli/feedback/feedback.go
- cli/globals/globals.go
- cli/lib/list.go
- cli/lib/search.go
- cli/output/rpc_progress.go
- cli/version/version.go
- go.mod
- test/test_lib.py
Continuation of #345, extend the `PrintResult` API usage to all those commands that need a complex output rendering.
To reduce boilerplate, `feedback.Print` was changed so that it will serialize strings to JSON when needed; this way, all those commands that don't need to provide a complex output can simply do `feedback.Print("message")` without caring of the output format, see `version` for example.
> Make commands output agnostic

- install.sh
`[  ... == ...  ]` is Bash extension. install.sh should use syntax of standard `test` command.
> Fix bashisms in install.sh

- cli/globals/configs.go
The "new name" given in the error message is not correct - the new file name seems to be arduino-cli.yaml
> Fix wrong config file name in error message

- commands/board/list.go
- commands/board/list_test.go
When the USB vid or pid are obviously wrong, avoid calling the API, sparing users' bandwidth and reducing useless pressure on the backend.
I moved vid/pid validation inside `apiByVidPid` to keep the `List` logic tidy and clean. A specific test case was added to cover the case vid or pid are invalid.
> Avoid calling cloud API if vid or pid are invalid

- README.md
Rearrange install instructions, fix Markdown issues, small language fixes.
> [skip-changelog] Reformat install instructions

- .goreleaser.yml
- go.mod
Add more variants for the expressions used to skip ci and changelog entries
> [skip changelog] better match for skip clauses

- .github/workflows/test.yaml
Also don't run the workflow twice on open PRs
> Run tests on OSX

- .github/workflows/test.yaml
As per [GitHub announcement](https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/) the default shell for Windows steps is `pwsh`.
This causes the `Install Go deps` step [fail on windows](https://github.com/arduino/arduino-cli/runs/274628439). 
```
Install Go deps13s
##[error]Process completed with exit code 1.
Run go get github.com/golangci/govet
go get github.com/golangci/govet
go get golang.org/x/lint/golint
go get github.com/golang/protobuf/protoc-gen-go
shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
env:
GOROOT: C:\hostedtoolcache\windows\go\1.13.3\x64
go: finding github.com/golangci/govet latest
go: downloading github.com/golangci/govet v0.0.0-20180818181408-44ddbe260190
go: extracting …
```
> [skip changelog] Force windows env to use bash as shell instead of powershell

- .github/workflows/test.yaml
Use github token in `Install Taskfile` step after [arduino/actions/setup-taskfile](https://github.com/arduino/actions/pull/7) merged the functionality
> [skip changelog] Use github token in Install Taskfile step

- cli/cli_test.go
- cli/testdata/Blink/Blink.ino
- commands/compile/compile.go
- go.mod
- go.sum
- test/requirements.txt
Previously the compile command copied only the following artifacts:
```
sketch.ino.hex (or .bin)
sketch.ino.elf
```
now also the files matching the glob
```
sketch.ino.*.hex
```
will be copied.
This allows for some 3rd party core, like esp32, to copy also extra files like `sketch.ino.partitions.bin`.
Should fix #163
> Fixed upload issue on esp32 (partitions artifacts copy)

- arduino/builder/sketch.go
Because arduino-cli segfaults when sketchDir is a symbolic link,
a simple walk function is introduced with a twofold effect:
- fix the segfault
- allow to use symlinks
ref: https://www.google.com/search?q=golang+Walk+does+not+follow+symbolic+links
*edit*:
* fixes #424 
* fixes #358
> Use a local Walk function

- .github/workflows/test.yaml
As python 3.8 became available, the following [error](https://github.com/arduino/arduino-cli/runs/279178199#step:14:479) appeared in the `test` workflow:
```
pytest test
Traceback (most recent call last):
File "c:\hostedtoolcache\windows\python\3.8.0\x64\lib\runpy.py", line 192, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\hostedtoolcache\windows\python\3.8.0\x64\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\hostedtoolcache\windows\Python\3.8.0\x64\Scripts\pytest.exe\__main__.py", line 4, in <module>
File "c:\hostedtoolcache\windows\python\3.8.0\x64\lib\site-packages\pytest.py", line 6, in <module>
from _pytest.assertion import register_assert_rewrite
File "c:\hostedtoolcache\windows\python\3.8.0\x64\lib\site-packages\_pytest\assertion\ …
```
> [skip changelog] Pin python version to 3.7 for integration tests

- arduino/cores/packagemanager/package_manager.go
- arduino/cores/packagemanager/package_manager_test.go
- arduino/cores/packagemanager/testdata/extra_hardware/referenced/avr/boards.txt
- arduino/cores/packagemanager/testdata/extra_hardware/referenced/samd/boards.txt
A core is referenced by specifying `build.core=package:core` in board properties. However, the code that handled resolving these, had two problems:
- It used the second part (`core`) rather than the first part (`package`) to look up the package to reference. The most commonly used core reference is `arduino:arduino` which works because both parts are identical. However, when referencing cores where the core name does not equal the package name (e.g. the Adafruit or STM32 cores), there is no way to actually reference such a core properly.
- It also failed to handle a missing architecture, resulting in a segfault.
This PR fixes both problems, and additionally adds a testcase for `ResolveFQBN` that exposes these problems (and tests some other cases as well).
> Fix handling of referenced cores

- arduino/cores/packagemanager/identify.go
- arduino/cores/packagemanager/package_manager_test.go
- arduino/cores/packagemanager/testdata/custom_hardware/test/avr/boards.txt
Even if vid.0/pid.0 is missing.
Fix #456
@intrigus
> Board identification: always check vid.1/pid.1

- .github/workflows/test.yaml
- cli/cli_test.go
- commands/daemon/monitor_test.go
- go.mod
Recent OSX updates make ineffective the mocking strategy from `bou.ke/monkey` on mac platforms, running mocked tests only on other platforms should be ok from the testing perspective and let us keep using the library without refactoring the test cases.
> [skip changelog] Don't run mocked tests on OSX

- README.md
I spent most of my weekend trying to figure out why I was always getting an Unknown for the `arduino-cli board list` regardless of what board I was using. I managed to track down [this issue](https://github.com/arduino/arduino-cli/issues/149) that notes the FTDI will have a generic VID/PID so will always be Unknown. I was under the impression the board list needed to be successful in order to upload, but that is not the case. 
This change makes a clarification note and hopefully saves some people some headaches.
> Added a note to help anyone using an FTDI chip.

- .github/workflows/test.yaml
OSX 10.14 will be decommissioned soon, let's unpin OS versions so we don't need to take any action when this happens.
> [skip changelog] unpin OS version on runners

- arduino/libraries/librarieslist.go
- arduino/libraries/librariesresolver/cpp.go
- arduino/libraries/librariesresolver/cpp_test.go
- go.mod
The closestmatch algorithm may return 'nil' if none of the candidate libraries has enough matching of the name. In this case just return the first library in alphanumeric ordering.
See arduino/Arduino#9242
> Fixed nil pointer exception on some rare case with multiple libs selection

- arduino/cores/packagemanager/loader.go
- arduino/cores/packagemanager/package_manager.go
- legacy/builder/setup_build_properties.go
> re-allow global user-customizable platform.txt

- legacy/builder/print_used_and_not_used_libraries.go
Previously printed:
```
Multiple libraries were found for "DHT.h"
Used: /home/megabug/Workspace/sketchbook-cores-beta/libraries/DHT_sensor_library
Multiple libraries were found for "Adafruit_Sensor.h"
Used: /home/megabug/Workspace/sketchbook-cores-beta/libraries/Adafruit_Unified_Sensor
Using library DHT_sensor_library at version 1.3.8 in folder: /home/megabug/Workspace/sketchbook-cores-beta/libraries/DHT_sensor_library 
Using library Adafruit_Unified_Sensor at version 1.0.3 in folder: /home/megabug/Workspace/sketchbook-cores-beta/libraries/Adafruit_Unified_Sensor 
```
Even if there are no multiple libraries available for the particular header. After this patch we have:
```
Using library DHT_sensor_library at version 1.3.8 in folder: …
```
> Print "multiple libraries found for header.h..." only when it really happens

- legacy/builder/phases/core_builder.go
When build-path and cache-path are on different partitions it will not be possible (on windows) to reference them with a relative path. This commit allows this by automatically disabling the aggressive core caching.
Previously an error was emitted and the build interrupted.
Should fix #464
> Auto-disable (deep) caching of core builds if needed

- .github/workflows/stale.yaml
Invert the time windows, otherwise an issue will be re-marked stale every 15 days, resetting the time window and preventing the closing event (time window is 30 days) to kick in.
With this patch, when it's the case an issue will be closed before it's re-marked stale.
A more comprehensive solution would be filtering out stale issues but that'd require another loop, let's apply this quick fix while we evaluate how useful is the bot.
> [skip ci] fix stalebot

- cli/config/init.go
- go.mod
> Fix config init command docs

- cli/daemon/daemon.go
When running `arduino-cli` as a backend for the IDE, sometimes it happens that the IDE fails to terminate the process. This leaves a "zombie" `arduino-cli` process taking system resources and waiting for commands forever.
This patch adds the `--autoclose` flag to the cli daemon mode. When this option is flagged the cli monitors the 'os.Stdin` pipe and, if the parent process closes it, the cli terminates itself. Usually when the stdin is closed it means that the parent process is dead.
> Terminate daemon command when parent process exits; added "--daemonize" flag to keep old behaviour

- README.md
> [ci skip] Show how to use the configuration file

- install.sh
> [ci skip] Use unzip on Windows in the install script

- arduino/builder/sketch.go
- arduino/builder/sketch_test.go
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/.#sketch.ino
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/TestLoadSketchFolderBothInoAndPde.ino
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/TestLoadSketchFolderBothInoAndPde.pde
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/header.h
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/other.ino
- arduino/builder/testdata/TestLoadSketchFolderBothInoAndPde/src/dont_load_me.ino
- arduino/builder/testdata/TestLoadSketchFolderPde/.#sketch.ino
- arduino/builder/testdata/TestLoadSketchFolderPde/TestLoadSketchFolderPde.pde
- arduino/builder/testdata/TestLoadSketchFolderPde/header.h
- arduino/builder/testdata/TestLoadSketchFolderPde/other.ino
- arduino/builder/testdata/TestLoadSketchFolderPde/src/dont_load_me.ino
Fixes #386 
```
Support .pde extension by compile when only folder specified (#386)
When only specifying folder, the logic will try both <DirName>.ino and
<DirName>.pde as the main sketch file. If both are found, and error is
also thrown (it would break on compile later on).
Added couple of unit tests also.
```
> Look for both .pde and .ino files when compile target is a folder

- arduino/cores/cores.go
- arduino/cores/packagemanager/package_manager.go
- arduino/libraries/librariesmanager/install.go
Fixes #177 
When working with custom boards some corner cases might arise and provide an inconsistent in-memory representation of the cores. This PR introduces more checks for structs and fields that might be `nil` at some point during compilation.
> Avoid panics when compiling for custom boards

- commands/lib/search.go
- test/test_lib.py
fixes #104 
This way the `lib search` behaviour will be the same as the Java IDE.
> Look for query string into more fields when searching for libs

- arduino/libraries/librariesmanager/librariesmanager.go
- test/conftest.py
Now,  the "_" is replaced with a blanket " ", to reslove the
inconsistency problem. However, use the name of the installing
library may be a better solution.
fixes #362 
BTW, when we uninstall libraries, there are no messages to notify the user libraries are successfully uninstalled.
However, when we install libraries message like `Installed LiquidCrystal I2C@1.1.2` is printed to notify  libraries are successfully installed.
> Fix "lib uninstall" when library name contains spaces

- cli/daemon/daemon.go
- configuration/defaults.go
Let user configure which TCP port to use for the gRPC daemon:
* from the config file
* from the command line with `--port`
* by setting the env var `ARDUINO_DAEMON_PORT`
Fixes #485
> Set the daemon TCP port from config file or command line

- cli/lib/list.go
- test/test_lib.py
Also provide an integration test for the fix introduced in #443
> "lib list" now returns an empty json array when there are no libraries installed

- cli/cli.go
- cli/cli_test.go
This PR optimize `searchConfigTree` to speed up performance on Windows, where it was particularly slow.
> [skip changelog] Sliglthly optimize searchConfigTree

- cli/cli_test.go
- cli/compile/compile.go
- cli/upload/upload.go
This changeset marks the fqbn and port CLI flags as required in the compile and upload commands. The error message is thus changed from the generic:
```
Error during Upload: no upload port provided
```
To the more directly actionable:
```
Error: required flag(s) "fqbn", "port" not set
```
Which is followed by the CLI help text.
> Improve error message when port or fqbn flags are not set

- configuration/directories.go
Fix error on `arduino-cli core update-index` with nonexistent ".arduino15" dir:
"Error initializing package manager: cannot initialize package manager: loading hardware packages: loading hardware from /.../.arduino15/packages: /.../.arduino15/packages is not a directory"
> [skip changelog] check if PackagesDir exists when reporting it in HardwareDirectories()

- cli/board/attach.go
- cli/board/details.go
- cli/board/list.go
- cli/board/listall.go
- cli/compile/compile.go
- cli/core/download.go
- cli/core/install.go
- cli/core/list.go
- cli/core/search.go
- cli/core/uninstall.go
- cli/core/update_index.go
- cli/core/upgrade.go
- cli/instance/instance.go
- cli/lib/check_deps.go
- cli/lib/download.go
- cli/lib/install.go
- cli/lib/list.go
- cli/lib/search.go
- cli/lib/uninstall.go
- cli/lib/update_index.go
- cli/lib/upgrade.go
- cli/upload/upload.go
- commands/instances.go
- rpc/commands/commands.proto
Fixes #529 
On `core update-index`, with this PR the CLI creates all the directories needed to work properly in case of a first usage with a fresh install.
This was a regression shipped in 0.7.0, now the code is more robust and errors bubble up correctly (no more `os.exit` from within lower layers).
> Fix update index on fresh installs

- cli/config/init.go
Code in this PR creates the default data dir if it doesn't exist on `config init`.
> Fix config init on fresh installs

- test/test_compile.py
The alternative is to change the code so that `boards` is always a non-null list.
> [skip changelog] Handle non-board serial ports in compile integration tests

- arduino/cores/packageindex/index.go
- arduino/cores/packageindex/index_test.go
- arduino/cores/packagemanager/package_manager_test.go
- cli/cli_test.go
- commands/daemon/daemon.go
- commands/daemon/settings.go
- commands/daemon/settings_test.go
- commands/instances.go
- legacy/builder/test/includes_to_include_folders_test.go
- legacy/builder/tools_loader.go
Remove all the `fmt.Println` instances that were meant temporary with debugging purposes.
> Remove debug prints

- cli/compile/compile.go
- commands/compile/compile.go
- legacy/builder/phases/sizer.go
Fixes #527 
At some point, deep into the `legacy` package, some function returns an error with an empty message, causing the command to fail in suspense with `"Error during build: build failed: `.
This is a workaround, the real fix would be going on a quest in search of the command(s) returning the empty error.
> Improve error message on build failure

- cli/cli_test.go
- cli/compile/compile.go
- cli/upload/upload.go
In attempt to improve the error messages we merged #523 but this broke the `compile` and `attach` commands, complaining for missing FQBN even for sketches that have been previously attached.
Side note, since we merged #536, the error messages with this PR will be ok even with #523 partially reverted.
> Fix regression on compile and upload with attached sketches

- README.rst
Just a minor improvement to use https instead of http in the README example to encourage good habits. :)
The URL is valid, but I wasn't able to test that the tool is able to fetch it because of #546.
> Use https scheme in the README example

- arduino/builder/sketch.go
- arduino/builder/sketch_test.go
- legacy/builder/container_setup.go
- test/test_compile.py
Fixes #522 
The filter we use to ignore files contained in version control systems' cache was applied to the sketch folder itself, thus preventing a sketch to be named like `RCS`.
This PR increases resiliency by avoiding panics if a sketch name couldn't be found and applies blacklist filters only to folders contained in the sketch, i.e. excluding the root folder.
> Allow naming sketches like "RCS" and "CVS"

- README.rst
This PR propose the usage of the config file option as best mode for 3rd party core usage.
The `--additional-urls` flag is now presented as an alternative, adding a complete usage explanation.
> [skip changelog] [skip ci] Clarify additional-urls option usage

- client_example/go.mod
- client_example/go.sum
- client_example/main.go
- Demonstrate `SetValue`, `Merge`, `GetValue`, and `GetAll` (added in https://github.com/arduino/arduino-cli/pull/521).
- Switch from the [deprecated](https://github.com/arduino/arduino-cli/pull/530) `configuration` request field of `Init` to using the `Settings` service to configure arduino-cli's directories.
As requested at https://github.com/arduino/arduino-cli/issues/553#issuecomment-573353246
> [skip changelog] Demonstrate the use of the gRPC Settings interface in client_example

- client_example/go.mod
- client_example/go.sum
- client_example/main.go
`LibraryResolveDependencies` was added in https://github.com/arduino/arduino-cli/pull/351 but the client_example was not updated accordingly.
> [skip changelog] Demonstrate gRPC interface's LibraryResolveDependencies method in client_example

- arduino/builder/sketch.go
- arduino/builder/sketch_test.go
- arduino/sketch/sketch.go
- arduino/sketch/sketch_test.go
- legacy/builder/container_add_prototypes.go
- legacy/builder/container_merge_copy_sketch_files.go
- legacy/builder/preprocess_sketch.go
- legacy/builder/sketch_loader.go
- legacy/builder/types/types.go
When compiling a big sketch, I noticed that `arduino-builder` took up a *lot* of RAM (over 1G, sometimes it even went over 1.7G and crashed with an out of memory error).
Investigating, it turns out that this is because `arduino-builder` and `arduino-cli` load *all* source file contents into memory when loading the sketch. In practice, only the .ino file contents are actually used, so the rest is just dead weight. For sketches that have a lot of extra baggage (we have libraries, a core and some host-system tools in the sketch directory), this can take up a lot of unneeded space.
This PR modifies `sketch.Item` to remove the `Source` string, which is then no longer filled at sketch load time. Instead, the `GetSourceStr()` method loads the contents on demand (which is really only when merging …
> Load contents of source files only when needed

- arduino/cores/packagemanager/loader.go
- arduino/cores/status.go
- cli/lib/search.go
> fix: Fix typo

- test/test_core.py
- test/testdata/test_index.json
Testdata point to an outdated branch that's been deleted. Use master instead.
> [skip changelog] point the master branch in tests data

- arduino/libraries/libraries.go
- arduino/libraries/librarieslist.go
- arduino/libraries/librariesresolver/cpp.go
- arduino/libraries/librariesresolver/cpp_test.go
This PR fixes the priority rules.
Should fix https://github.com/arduino/Arduino/issues/9655
> Fix library priority selection

- commands/lib/resolve_deps.go
- test/test_lib.py
> Libraries dependencies: output error if no valid solution found

- cli/cache/cache.go
- cli/cache/clean.go
- cli/cli.go
- test/test_cache.py
Add command `cache clean` to clean the cache files
depending on the loaction of the caching files
under different OS.
Relates #285
> Add cache clean command

- arduino/libraries/libraries.go
- arduino/libraries/librariesresolver/cpp.go
- arduino/libraries/librariesresolver/cpp_test.go
This PR changes again the lib priority selection to improve backward compatibility. Now the algorithm should be (hopefully) 100% compatible with legacy algorithm used in the `arduino-builder`.
The priority is determined by applying the following rules, one by one in this order, until a rule determine a winner:
1. A library that is architecture compatibile wins against a library that is not architecture compatible
2. A library that has better "name priority" wins (see below for details)
3. A library that is architecture optimized wins against a library that is vanilla
4. A library that has a better "location priority" wins (see below for details)
5. A library that has a name with a better score using "closest-match" algorithm wins
6. A library that has a name that comes first in …
> Fix libraries priority selection (again)

- legacy/builder/constants/constants.go
- legacy/builder/phases/libraries_builder.go
General change:
- library compilation bails out if the precompiled object is found.
This allows mixed libraries that fallback using sources if no suitable precompiled object is found
ARM float specification change:
- Cortex M4+ allows specifying different flags for floating point ABI
This patch introduces a second level of subfolder that MUST be used if -mfpu or -mfloat-abi are specified on the commandline
Since there's no clear specification (unlike build.mcu), the values are extracted from c++ recipe
For example, for a target which commandline contains `-mfloat-abi=hard -mfpu=fpv4-sp-d16` , the precompiled search path will be
`$libfolder/cortex-m4/fpv4-sp-d16-hard`
If that folder doesn't exist the library will be compiled from sources
- Open questions:
While reviewing this I found a …
> Improve precompiled libraries handling

- cli/config/init.go
- test/test_config.py
The option `--save-as` to the command `config init` is a no-op and has been removed.
A new option `--dest-dir` was added that can be used to specify a destination folder where to put the configuration file.
Fixes #570
> Add option --dest-dir to config init, removed noop --save-as

- arduino/cores/cores.go
- arduino/cores/packagemanager/loader.go
- arduino/cores/packagemanager/package_manager.go
Fix https://github.com/arduino/Arduino/issues/9724
> Reduce priority for IDE-bundled platform releases

- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
- .goreleaser.yml
- gon.config.hcl
This PR Integrates the Notarization process in the Arduino CLI Relese pipeline.
As per [Apple announcement](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution):
> Beginning in macOS 10.14.5, software signed with a new Developer ID certificate and all new or updated kernel extensions must be notarized to run. Beginning in macOS 10.15, all software built after June 1, 2019, and distributed with Developer ID must be notarized.
The PR moves the responsibility of GitHub release creation and Arduino servers upload, from `goreleaser` to GH Actions steps, and adds the notarization step leveraging [Gon](https://github.com/mitchellh/gon) (Thanks to @mitchellh and to @zmoog who discovered the tool :smile: )
The `notarize-macos` job must run on a …
> Integrate Apple notarization process into Github Actions release pipeline

- .github/workflows/release.yaml
- gon.config.hcl
In order to force the notarization process to take place, we need to ask `gon` to produce a `.zip` file as output.
As explained here https://github.com/arduino/arduino-cli/pull/578 / https://github.com/arduino/arduino-cli/pull/578#discussion_r377794210 the `gon.config.hcl` "zip" section is not mandatory di per se', but not  having an "output" section at all will not start the notarization submission process for the binary.
For our release process the generated `.zip` file has no use, as we repackage the signed binary that `gon` replaces in-place. The `.zip` is functional for the notary service submission only
Thanks to @zmoog for patiently explaining the whole process to me countless times :bowing_man:
> Force notarization process to take place configuring Gon zip output

- .github/workflows/release.yaml
GitHub Actions does not preserve file permission when a file is shared between jobs as an artifact using the [upload-artifact@v1](https://github.com/actions/upload-artifact) and [download-artifact@v1](https://github.com/actions/download-artifact) actions.
I have empirically observed this behavior in a test workflow, and I've found a few [issues](https://github.com/actions/upload-artifact/issues/38) on GitHub.
According to a [comment](https://github.com/actions/upload-artifact/issues/38#issuecomment-562679842) from a user, GitHub will fix this file permission issue in the v2 version of these actions.
Execution permission is re-added using `chmod`, until this problem is fixed in the actions.
User reported bugs:
* Install script doesn't work properly on v0.8.0 #584
> Restore permission lost during upload/download

- cli/daemon/daemon.go
- Consumers of the CLI have a better exit code when it fails at startup
- Logged message to stdout, so gRPC clients know, it is time to connect
> Added better error handling for the gRPC server.

- commands/debug/debug.go
Hotfix to solve windows platform issues:
- Keep using forward slash in debugger command line parameters
- Use double quotes to handle spaces on windows paths
- Extend connection timeout to gdb server (openocd)
> Fix paths handling for gdb

- arduino/sketches/sketches.go
- cli/board/attach.go
- commands/board/attach.go
- commands/upload/upload.go
If `cpu.port` is present in `sketch.json` use the specified port during the upload.
Also, saves discovered or specifed port in `sketch.json` during `board attach`.
Needs to be tested on Windows.
Please, review.
> Read upload port from sketch.json

- .github/workflows/docs.yaml
Changes to `/cli` and `/rpc` source modules might require a new build of the docs site. We might have false positives but being builds idempotent, let's do it anyways.
> [skip changelog] Run docs build on more path changes

- cli/upload/upload.go
- test/test_upload.py
This PR follows https://github.com/arduino/arduino-cli/pull/454 and:
- removes upload port as required CLI parameter in `upload` command to support `board attach` generated `sketch.json` file
- adds a `board attach` integ test
> Remove upload port as required CLI parameter in "upload" command

- legacy/builder/builder.go
- legacy/builder/builder_utils/utils.go
- legacy/builder/container_setup.go
- legacy/builder/phases/libraries_builder.go
- legacy/builder/types/context.go
- legacy/builder/types/progress_test.go
This PR fix the progress reporting from the builder that was totally wrong.
This patch partially includes https://github.com/arduino/arduino-builder/pull/289/files.
Fix https://github.com/arduino/arduino-builder/pull/289
Fix https://github.com/arduino/Arduino/issues/7138
> legacy: Improved progress report from Compile

- commands/core/search.go
When matching against a Platform#ID, the match must be a
case-insensitive exact match.
Closes #612.
```
akos.kitta@Akoss-MacBook-Pro arduino-cli % ./arduino-cli core search                                               
ID                   Version   Name                                             
Arrow:samd           2.1.0     Arrow Boards                                     
Intel:arc32          2.0.4     Intel Curie Boards                               
Intel:i586           1.6.7+1.0 Intel i586 Boards                                
Intel:i686           1.6.7+1.0 Intel i686 Boards                                
Microsoft:win10      1.1.2     Windows 10 Iot Core                              
arduino:avr          1.8.2     Arduino AVR …
```
> GH-612: `core search` can exact-match Platform#ID too.

- legacy/builder/gcc_preproc_runner.go
This information can be used by the core to turn off certain heavyweight headers (that don't need to be discovered anyway)
> Add macro during lib discovery phase

- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- Dockerfiles/builder/Dockerfile
- arduino/cores/packageindex/testdata/package_Zoubworld_index.json
- arduino/cores/packageindex/testdata/package_infineon_index.json
- client_example/go.mod
- docsgen/go.mod
- go.mod
Fixed faulty json because of new behaviour of encoding/json:
> encoding/json
> Number no longer accepts invalid numbers, to follow the documented behavior more closely.
Signed-off-by: Matteo Suppo <matteo.suppo@gmail.com>
> Bump required go version to 1.14

- docs/CONTRIBUTING.md
- docs/FAQ.md
- docs/getting-started.md
- docs/installation.md
- docs/library-specification.md
- docs/platform-specification.md
- docs/sketch-build-process.md
Fixes https://github.com/arduino/arduino-cli/pull/616#pullrequestreview-375141652
> [skip changelog] Fix typos in documentation

- cli/config/init.go
Improved output message with config file creation 
Fix #586
> Improve output message with config file creation

- cli/lib/install.go
Changed the short description from "Installs one of more [...]" to "Installs one or more [...]", thus matching the long one.
Docs update.
"Installs one of more specified libraries into the system."
"Installs one or more specified libraries into the system."
It shouldn't, as the only change is to a command description string.
It's just a typo fix, "one of more" was written instead of "one or more" on the short description, but it was correct in the long one, so now both are correct.
---
See [how to …
> Typo fix in short description of installCommand

- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
- **Bugfix**: Replace $PWD with github actions workspace variable to solve invalid chars issue in container volume binding (https://github.com/arduino/arduino-cli/runs/569994650?check_suite_focus=true#step:3:65)
- **Bugfix**: Add semver tool to enable pre-release flag in release creation. We lost this bit of functionality (https://github.com/actions/create-release/issues/9) when we moved the github release creation from goreleaser to github actions
- **Refactoring**: Removed `get_tag` step in release workflow, adding the tag parse directly in `Notarize binary` step
Nightly and Release workflow fail
Release workflow now …
> [skip changelog] Github Actions bugfixes

- test/test_lib.py
Bug Fix -
The `test_search_paragraph` searches for an outdated string as the new version of ArduinoJSON is released [6.15.1](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.15.1)
This changes the sentence making the existing test fail.
`test_search_paragraph` under `test_lib.py` fails as it returns an empty json
The tests now pass as the search term has been updated
---
> update search paragraph command to match ArduinoJSON latest release

- cli/board/board.go
- cli/board/list.go
- cli/cli.go
- cli/compile/compile.go
- cli/config/config.go
- cli/core/core.go
- cli/core/download.go
- cli/core/install.go
- cli/core/uninstall.go
- cli/sketch/sketch.go
- cli/version/version.go
docs update
Multiple typos in the command line help text.
No
> [skip changelog] Fix typos in command line help text

- legacy/builder/utils/utils.go
It happened on MacOSX, but I do not exclude it may happen in other OS too: when building some large sketch for Arduino Due, the system libsam_xxx.a library is transformed to relative path, in particular the path
`/Users/cmaglie/Library/Arduino15/packages/arduino/hardware/sam/1.6.12/variants/arduino_due_x/libsam_sam3x8e_gcc_rel.a`
is made relative to the build folder
`/var/folder/x8/ttjf_wrd63823894128467832/T/arduino_build_988374/`
but since both paths resides in different partitions the result is:
`../../../../../../Users/cmaglie/Library/Arduino15/packages/arduino/hardware/sam/1.6.12/variants/arduino_due_x/libsam_sam3x8e_gcc_rel.a`
so it traverse from `/var/..../arduino_build_988374` to the root and descend back into `/Users/...`
This is bad for two reasons:
1) the resulting "relative" …
> Fixed path-relativization error when traversing different partitions

- docs/CONTRIBUTING.md
docs update
`go get -U github.com/golang/protobuf/protoc-gen-go` is an invalid command due to the incorrect case of the `-u` flag.
I fixed the command and a couple other minor typos.
No.
> [skip ci] [skip changelog] Fix typos in CONTRIBUTING.md

- configuration/configuration.go
Previously the config value `IDE.Bundled` was set to `false` when it should be `true`:
https://github.com/arduino/arduino-cli/blob/d80f1199eec9d4a92f6d256ced0836aabe76f9ee/configuration/configuration.go#L175-L179
Anyway `IsBundledInDesktopIDE()` return the wrong result only when it's called the second time and the cached value is returned without performing the check again.
This PR fixes this problem and simplify a bit the function.
> Fixed wrong IDE bundle-detection result caching

- arduino/cores/packagemanager/download.go
- arduino/libraries/librariesmanager/download.go
- arduino/resources/helpers.go
- arduino/resources/helpers_test.go
- arduino/resources/resources_test.go
- cli/cli.go
- cli/core/download.go
- cli/core/install.go
- cli/core/upgrade.go
- cli/daemon/daemon.go
- cli/globals/globals.go
- cli/instance/instance.go
- cli/lib/download.go
- cli/lib/install.go
- cli/lib/upgrade.go
- commands/board/list.go
- commands/bundled_tools.go
- commands/core/download.go
- commands/core/install.go
- commands/core/upgrade.go
- commands/daemon/daemon.go
- commands/download.go
- commands/instances.go
- commands/lib/download.go
- commands/lib/install.go
- commands/lib/upgrade.go
- configuration/defaults.go
- go.mod
- go.sum
This PR makes a bunch of changes:
- ~~use `downloader.SetDefaultConfig()` to set globally the user-agent: this allows to avoid passing headers back and forth~~
- ~~previously in the `core update-index` command user agent headers wasn't set when downloading: with the global `downloader.SetDefaultConfig(...)` this is no more a problem.~~
- added support for network proxy configuration
- refactored the function that generates the user-agent to add a subcomponent part (we use it in the `daemon` mode).
- that showed we make an http API call in `board list` without using `downloader` library, so it ignores the global network settings. I've added a TODO for missing proxy usage.
> Added configuration option for proxy usage

- commands/board/attach.go
Fixes bug on windows related to `board attach` command
The message
```
Attach board error: no supported board found at serial://COM7
```
is returned even if a board is attached to COM7 port
```
C:\Users\umber\Downloads\empty>..\arduino-cli.exe board list
Port Type              Board Name            FQBN                     Core         
COM3 Serial Port       Unknown
COM4 Serial Port       Unknown
COM7 Serial Port (USB) Arduino MKR WiFi 1010 arduino:samd:mkrwifi1010 arduino:samd
```
There is already an integration test that uses board attach …
> Fix serial port URI parsing in board attach command

- docs/sketch-specification.md
- mkdocs.yml
docs update
The documentation already contains the Arduino library and platform specifications, but was missing an Arduino sketch specification.
No.
Built page: https://per1234.github.io/arduino-cli/sketch-specification/
> [skip changelog] Add sketch specification to documentation

- docs/library-specification.md
- docs/package_index_json-specification.md
- docs/platform-specification.md
- docs/sketch-build-process.md
docs update
The documentation imported from the arduino/Arduino wiki was mostly written when Arduino's only official development software was the Arduino IDE. This resulted in many statements that mentioned the Arduino IDE specifically, when they actually apply to other development software as well. Conversely, there were Arduino-IDE specific statements which were not qualified as such.
No
I've used the term "Arduino development software" in documentation that applies to Arduino IDE, Arduino Pro IDE, Arduino Web Editor, and Arduino CLI all.
In the Sketch build process document, …
> [skip changelog] Fix incorrect software specificity/non-specificity in documentation

- .github/tools/fetch_athena_stats.sh
- .github/workflows/arduino-stats.yaml
No
This PR introduces a cron action that will gather download statistics from Arduino CDN and push results to Datadog.
This PR is a twin PR for https://github.com/arduino/arduino-cli/pull/665
---
> [skip changelog] Add stats fetching from Arduino CDN using AWS Athena

- .github/workflows/github-stats.yaml
- .github/workflows/stats.yaml
No changes to the Arduino CLI
This PR introduces a cron action that will gather download statistics from GitHub releases and push results to Datadog.
---
> [skip changelog] Gather downloads stats from GitHub releases

- .github/workflows/nightly.yaml
No changes to the CLI
Send an error event when nightly builds fail
---
> [skip changelog] Add alert when nightly build fails

- .github/workflows/github-stats.yaml
No CLI changes
No need to collect stats every five minutes. Also changed workflow name so it's easier to understand which had issues between github/arduino in case of failure
---
> [skip changelog] Collect download stats less often

- test/test_board.py
Solves flaky board details test
---
> [skip changelog] Fix flaky board details test

- arduino/cores/fqbn.go
- commands/compile/compile.go
- commands/upload/upload.go
Small cleanups that keeps coming.
Let's push them to master so we can get rid of them on other PRs.
> [skip changelog] Small cleanups

- arduino/sketches/sketches.go
- arduino/sketches/sketches_test.go
- arduino/sketches/testdata/Sketch1/Sketch1.ino
- commands/compile/compile.go
- test/test_compile.py
This PR makes `sketches.NewSketchFromPath` tolerant to different input paths:
1. `sketch := sketches.NewSketchFromPath(paths.New("path/to/sketch"))`
2. `sketch := sketches.NewSketchFromPath(paths.New("path/to/sketch/sketch.ino"))`
Previously the function would return different `Sketch` struct with different `Name` fields:
1. `sketch.Name == "sketch"`
2. `sketch.Name == "sketch.ino"`
now it will return the same `Name` consistently in both cases:
1. `sketch.Name == "sketch"`
2. `sketch.Name == "sketch"`
This PR solves the different treatment of sketch path argument between `compile`, `upload` and `debug`. In particular, using the combined `compile + upload` with a sketch path containing `.ino` previously produced a sucessful compile followed by an upload error (because upload will not find …
> Fix sketch metadata loader

- rpc/commands/commands.pb.go
- rpc/commands/commands.proto
- rpc/commands/common.pb.go
- rpc/commands/common.proto
Add explanatory comments for common and general components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for common and general components of the gRPC interface

- client_example/main.go
Replace BoardDetailsResp.GetRequiredTools() call in gRPC client example with the new equivalent method `GetToolsDependencies()`.
`GetRequiredTools()` was removed in https://github.com/arduino/arduino-cli/pull/674 so the client example now fails:
```
.\main.go:448:42: details.GetRequiredTools undefined (type *commands.BoardDetailsResp has no field or method GetRequiredTools)
```
client example works.
No
> [skip changelog] Replace obsolete BoardDetailsResp.GetRequiredTools() call in gRPC client example

- rpc/settings/settings.pb.go
- rpc/settings/settings.proto
Add explanatory comments for the Settings service gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
There is very little explanation of the gRPC interface in the documentation.
Improved documentation of the Settings service interface.
No
Generated docs:
https://per1234.github.io/arduino-cli/rpc/settings/
> [skip changelog] Add documentation for Settings service

- rpc/commands/commands.pb.go
- rpc/commands/commands.proto
- rpc/commands/core.pb.go
- rpc/commands/core.proto
Add explanatory comments for the platform components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for platform components of the gRPC interface

- rpc/monitor/monitor.pb.go
- rpc/monitor/monitor.proto
Add explanatory comments for the Monitor service of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for gRPC Monitor service

- legacy/builder/i18n/i18n.go
This PR serializes access to underlying streams.
Should solve:
```
WARNING: DATA RACE
Write at 0x00c04c8c5a88 by goroutine 61:
bytes.(*Buffer).grow()
/usr/local/go/src/bytes/buffer.go:147 +0x27f
bytes.(*Buffer).Write()
/usr/local/go/src/bytes/buffer.go:172 +0x154
fmt.Fprintln()
/usr/local/go/src/fmt/print.go:265 +0xb2
github.com/arduino/arduino-cli/legacy/builder/i18n.LoggerToCustomStreams.Fprintln()
/go/pkg/mod/github.com/arduino/arduino-cli@v0.0.0-20200324101224-985b2c99c8a4/legacy/builder/i18n/i18n.go:50 +0x125
Previous read at 0x00c04c8c5a88 by goroutine 9:
bytes.(*Buffer).grow()
/usr/local/go/src/bytes/buffer.go:143 +0x19d
bytes.(*Buffer).Write()
/usr/local/go/src/bytes/buffer.go:172 +0x154
fmt.Fprintln()
/usr/local/go/src/fmt/print.go:265 +0xb2 …
```
> Fixed race condition in legacy i18n.LoggerToCustomStreams

- rpc/commands/commands.pb.go
- rpc/commands/commands.proto
- rpc/commands/compile.proto
Add explanatory comments for the compile components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
I followed the style convention of using comments at the end of the code line that had been previously established in compile.proto. This resulted in compile.pb.go not being changed, since protoc …
> [skip changelog] Add documentation for compile components of the gRPC interface

- rpc/commands/commands.pb.go
- rpc/commands/commands.proto
- rpc/commands/upload.pb.go
- rpc/commands/upload.proto
Add explanatory comments for the upload components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for upload components of the gRPC interface

- arduino/cores/packagemanager/download.go
- arduino/libraries/librariesmanager/download.go
- arduino/resources/helpers.go
- arduino/resources/helpers_test.go
- arduino/resources/resources_test.go
- cli/globals/globals.go
- commands/board/list.go
- commands/download.go
- commands/instances.go
- go.mod
- go.sum
- httpclient/httpclient.go
- httpclient/httpclient_config.go
- httpclient/httpclient_test.go
- httpclient/httpclient_transport.go
A default HTTP client for the cli which handles proxy configuration and default HTTP headers (User-Agent)
HTTP calls in the cli that don't use the downloader are not using the proxy configuration or the user-agent header
All HTTP calls in the cli are proxy-enabled and submit the cli User-Agent
No
---
> add cli httpclient with support for proxy configuration

- .github/workflows/docs.yaml
- .gitignore
- Taskfile.yml
- docs/build.py
- docs/css/version-select.css
- docs/js/version-select.js
- mkdocs.yml
- requirements_docs.txt
This PR introduces [Mike](https://github.com/jimporter/mike) to wrap Mkdocs execution so that we can build different docs for each different Arduino CLI version.
At the moment docs are built and published at every merge on `master`, meaning that the docs might contain unreleased features.
We'll add:
* a special `latest` version of the docs pointing to the most recent Arduino CLI release: these docs will be shown by default when landing to https://arduino.github.io/arduino-cli/
* a special `dev` version of the docs, documenting whatever we have on `master` at every commit
* a selector to pick the right version of the …
> Add versioning to docs

- docs/installation.md
Improve the installation instructions for Windows users.
The installation instructions are not very friendly to Windows users.
The installation process for Windows is documented a little bit better.
No.
Resolves (partially?) https://github.com/arduino/arduino-cli/issues/705
> [skip changelog] Clarify installation instructions for Windows

- .github/workflows/docs.yaml
- Taskfile.yml
- docs/build.py
- docs/js/version-select.js
- requirements_docs.txt
This PR fixes the generation pipeline for versioned docs.
Most of the feature is implemented in master but docs are never pushed to the `gh-pages` branch. Also there's a bug in the version selector component that breaks it when docs are not at the root path `/`.
This PR implements several bugfixes:
* versioned docs are now pushed to `gh-pages`
* the docs pipeline is now triggered when changes are made to the GH workflow itself
* The command line interface of the `build.py` script has been expanded to simplify the code needed from within the workflow yaml definition
* The javascript component implementing the version …
> [skip changelog] Configure git push from CI

- docs/js/version-select.js
Bugfix in docs website
When users select the docs version from the recently added selector control, the relative URL is used and browser is pointed to `https://arduino.github.io/<version>` instead of `https://arduino.github.io/arduino-cli/<version>/` resulting in a 404
Use the absolute url `https://arduino.github.io/arduino-cli/` as a prefix for the destination URL
No changes to the CLI
---
> [skip changelog] use absolute URL in docs version selector

- docsgen/go.mod
Cause the command line interface documentation generation system to use  the `github.com/arduino/arduino-cli` module from the local path.
As reported in https://github.com/arduino/arduino-cli/issues/714, previously, the generated documentation for the command line interface did not reflect recent development work. This is caused by [`docsgen`](https://github.com/arduino/arduino-cli/tree/master/docsgen) using a pinned version of the `github.com/arduino/arduino-cli` module, which resulted in the the documentation only applying to the interface of the pinned version of Arduino CLI.
The generated command line interface …
> [skip changelog] Use local path for github.com/arduino/arduino-cli module dependency of docsgen

- commands/upload/upload.go
Previously, if there were many serial port connected, multiple `Performing 1200-bps touch reset on serial port /dev/ttyACMxx` were printed due to misplacement of the verbose print.
> Fixed verbose '1200-bps touch' notice

- cli/lib/install.go
Bug fix. Return non-zero exit code if library install fails due to dependency resolution.
Fixes #712 
Failure to resolve library dependency is logged, but does not exit with non-zero status code to indicate the error.
If it is not possible to resolve the dependency of a library, the error is logged and the process exits with an error code.
The lib install command will now exit with a non-zero code if a library dependency cannot be resolved. 
---
> lib install command will exit with non-zero status code if library dependency could not be resolved

- requirements_docs.txt
It pins `mike` version at 0.5.1 in the requirements file
`mike` version is not pinned and it gets the latest at each docs build. We're having a problem with latest version 0.5.2 as seen here https://github.com/arduino/arduino-cli/runs/716092672#step:11:103
While we investigate why 0.5.2 fails, pin 0.5.1 that was proven to work
No CLI changes
---
> Pin mike at version 0.5.1

- rpc/debug/debug.pb.go
- rpc/debug/debug.proto
Add explanatory comments for the Debug service of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for gRPC Debug service

- .codecov.yml
For some reasons the changes in #727 have been ignored. Reading the codecov docs one possibility is that the file format is wrong, so I validated it with the webservice provided by codecov.
Before the patch:
```
$ curl --data-binary @.codecov.yml https://codecov.io/validate
Path: coverage->status->project->default->threshold
<shared.validation.helpers.PercentSchemaField object at 0x7f172d3e5a10>.validate(None) raised TypeError('expected string or bytes-like object')
```
After the patch:
```
$ curl --data-binary @.codecov.yml https://codecov.io/validate
Valid!
{
"comment": false,
"coverage": {
"status": {
"patch": false,
"changes": false,
"project": {
"default": {
"target": 30.0
}
}
}
}
}
```
Let's see if after this change the new configuration will get through...
> Fixed codecov.yml file

- Taskfile.yml
Pass an extra option, `-u` when invoking `mike deploy`.
We use an alias called `latest` to point to the most recent of the docs. Problem is when we do `mike deploy`, it produces an error as `latest` is already taken.
By passing `mike deploy -u` we can "move" the alias as we produce newer versions.
No changes to the CLI
Tested locally
---
> [skip changelog] Update latest tag at mike deploy

- Taskfile.yml
- docs/CONTRIBUTING.md
- i18n/README.md
- i18n/cmd/commands/transifex/pull_transifex.go
Fetches available translation languages directly from transifex, removes the language configuration list. Adds documentation.
Supported i18n languages need to be listed as configuration values.
Supported i18n languages will be fetched from translation resources at transifex
---
> I18n fetch language codes from transifex

- .codecov.yml
This commits excludes:
- generated files
- i18n tooling for generating translations files that are not used in the final build of the cli.
> Excluding some modules from code coverage analisys

- legacy/builder/phases/linker.go
As discussed in: https://github.com/arduino/arduino-cli/issues/639
This change has no effects on all board with MCU != Atmega2560.
AFAIU the `--relax` option should be no more needed with the latest available avr compilers.
> Removed automatic '--relax' hack for compiles on Atmega2560 MCU

- rpc/commands/commands.pb.go
- rpc/commands/commands.proto
- rpc/commands/lib.pb.go
- rpc/commands/lib.proto
Add explanatory comments for the library components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
> [skip changelog] Add documentation for library components of the gRPC interface

- docs/configuration.md
- docs/getting-started.md
- docs/integration-options.md
- mkdocs.yml
Add page to documentation describing the various options for configuring Arduino CLI.
The ability to configure Arduino CLI via environment variables is only documented by a mention in the integration options article, which is not an obvious place to look for that information. Other aspects of configuration are undocumented.
Since this information didn't fit well in any of the existing pages, it makes sense to add a dedicated page, and add some documentation for the other two configuration methods as well. Although there is existing documentation for the other configuration methods elsewhere in the docs, it is missing …
> [skip changelog] Document Arduino CLI's configuration methods

- cli/daemon/daemon.go
Previously the daemon would listen to all interfaces, now it will listen only to localhost.
/cc @luigigubello
> Daemon listen to localhost

- install.sh
Usage:
to install the latest version:
```
./install.sh
```
to install a specific version:
```
./install.sh 0.9.0
```
> Added support for version pinning in install.sh

- docs/installation.md
Documentation PR for https://github.com/arduino/arduino-cli/pull/766: installation script now supports a "version parameter"
> Update install script documentation to document version pinning

- install.sh
Expand the grep pattern used by the installation script to scrape the latest tag from the GitHub release page to something that should only ever occur once on an HTML page.
GitHub changed the HTML of the release page, which resulted in grep finding multiple instances of the pattern, causing the installation script to fail when no version parameter was provided:
```
$ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
Installing in /home/per/temporary/bin
ARCH=64bit
OS=Linux
Using curl as download tool
TAG=0.11.0
0.11.0
0.11.0
CLI_DIST=arduino-cli_0.11.0
0.11.0
0.11.0_Linux_64bit.tar.gz
Downloading …
```
> [skip changelog] Fix installation script's latest tag determination code

- arduino/cores/packagemanager/package_manager.go
From now on, we log with the `debug` level instead of `info`. Without this change, the daemon log was full of this information when customing the CLI features via gRPC.
Closes #680
----
Reduces the log-level of the package-manager from `info` to `debug`
Now, when I consume the CLI in the Pro IDE, I do not see the daemon log full of:
```
[INFO] current best: arduino:avr@1.8.2 [bundle: false, managed: true, version: 1.8.2]
[INFO] current best: arduino:avr@1.8.2 [bundle: false, managed: true, version: 1.8.2]
[INFO] current best: arduino:avr@1.8.2 [bundle: false, managed: true, version: 1.8.2]
[INFO] …
```
> GH-680: Reduced the log level in package manager

- commands/upload/upload.go
- go.mod
- go.sum
- legacy/builder/phases/libraries_builder.go
notified here: https://github.com/arduino/ArduinoCore-avr/pull/52#issuecomment-650999390
and here: https://github.com/arduino/go-properties-orderedmap/commit/7e1498ef4c30c1569a3557c5f95131a411a06740#commitcomment-40162715
> [skip changelog] fixed typos

- cli/config/init.go
Documentation correction.
Documentation of `arduino-cli config init` doesn't accurately or fully match its behavior (which can be somewhat unintuitive under certain conditions):
- Configuration filename is now arduino-cli.yaml, not "cli-config.yml"
- Default configuration file location is no longer correctly described as "$EXE_DIR". It is now directories.data.
- Location of the written configuration file location may be customized via --dest-dir.
- Current configuration is written, not the default configuration.
- If configuration file already exists, it is updated with the current configuration.
Documentation of …
> [skip changelog] Correct documentation re: arduino-cli config init behavior

- docs/integration-options.md
Replace content duplicating low level details from the configuration documentation with a link to that content.
Low level details about the configuration system are present in a general overview of the three methods for using Arduino CLI
A link is provided for people interested in the details of the configuration system to get more information.
No.
> [skip changelog][skip ci] Replace duplicate content with link to config docs

- docs/library-specification.md
Remove incorrect prohibition on leading or trailing spaces in the library.properties `name` field.
The library specification includes an unnecessary prohibition against leading or trailing spaces in the library.properties `name` field.
Leading and trailing space is correctly trimmed on all fields of library.properties, including `name`.
The unnecessary extra verbosity in the name specification may cause people to miss the other important restrictions.
The `name` specification only contains the true requirements.
No.
> [skip changelog][skip ci] Correct lib name specification re: leading/trailing space

- docs/platform-specification.md
The documentation for the keywords.txt formatting should be maintained in one location.
Docs update
keywords.txt formatting documentation content is duplicated in the platform specification.
keywords.txt formatting documentation content is maintained in a [single location](https://arduino.github.io/arduino-cli/latest/library-specification/#keywordstxt-format).
No.
> [skip changelog] Remove duplicate content re: keywords.txt from platform specification

- cli/debug/debug.go
- cli/globals/args.go
- cli/upload/upload.go
- client_example/main.go
- docs/CONTRIBUTING.md
- docs/installation.md
- docs/package_index_json-specification.md
- docs/platform-specification.md
The documentation contains some minor typos.
A more serious typo resulted in the link for macOS in the "nightly" download table pointing to the latest stable release for that OS.
The typos in the documention are fixed.
No.
> [skip changelog] Correct typos in documentation

- test/README.md
Docs update.
Contributing guidelines link on tests readme is broken.
Contributing guidelines link on tests readme is not broken.
No
Linked to the Markdown file rather than the documentation site page so the link will always point to the matching docs.
> [skip changelog][skip ci] Fix contributing guidelines link on tests readme

- docs/sketch-build-process.md
Custom libraries paths may be specified via arduino-cli compile --libraries.
- [s] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls) before creating one)
- [s] The PR follows [our contributing guidelines](https://arduino.github.io/arduino-cli/CONTRIBUTING/#pull-requests)
- [s] Docs have been added / updated (for bug fixes / features)
Custom libraries paths may be specified via `arduino-cli compile --libraries`. Priority of all other libraries paths are documented in the sketch build process documentation, but not custom libraries paths. …
> [skip changelog][skip ci] Document location priority of custom libraries paths

- docs/sketch-specification.md
Sketch specification's metadata section only mentions the ability to associate an FQBN with a sketch.
The ability to associate a port with a sketch is now documented.
No.
> [skip changelog] Update sketch specification to reflect support for port attachment

- docs/command-line-completion.md
- docs/installation.md
This PR updates the documentation regarding command line completion using homebrew and fixes some inaccuracies
no
---
> Update command line completion docs

- commands/core/install.go
Previously the error was silently discarded
Fix https://github.com/arduino/arduino-cli/issues/755
> Emit error if a tool is not available for current OS

- docs/CONTRIBUTING.md
Docs update
Hardware requirements for running integration tests are not fully documented.
Contributors running integration tests may be surprised to find that a sketch was uploaded to every Arduino board attached to their computer.
Hardware requirements and effects of running integration tests are fully documented.
No.
> [skip changelog][skip ci] Document full hardware requirements and effects of running integration tests

- docs/getting-started.md
Docs update
The Getting started page contains some content that is unclear or unnecesarily detailed for the target audience.
The getting started page is more friendly to people getting started with using Arduino CLI.
No.
> [skip changelog] Make "Getting started" page more friendly to new users of Arduino CLI

- docs/platform-specification.md
The description of the use of platform.txt's name property in the Arduino IDE was vague and potentially confusing.
Use of platform.txt's name property by Arduino development software is more clear.
No.
> [skip changelog] Clarify use of platform.txt's name property in Arduino development software

- docs/platform-specification.md
Docs update.
The platform specification contains a "TODO" note about adding an example of using multiple custom board options. This note clutters the documentation.
Although it would be easy enough to add the suggested example of multiple custom board menus, I don't see that this is really necessary to document the feature. My opinion is that the existing documentation already does a great job of explaining this feature and I haven't seen evidence to the contrary while providing support to 3rd party platform authors. For that reason, I chose to simply remove the "TODO" note from the platform specification.
* **Does …
> [skip changelog] Remove unnecessary "TODO" note from platform specification

- docs/platform-specification.md
The Arduino IDE has a useful, previously undocumented, feature that allows hiding boards from the Tools > Board menu.
The Arduino IDE has a useful feature that allows control over the visibility of boards in the **Tools > Board** menu via a property in boards.txt, but this feature is undocumented.
The hide property of boards.txt is documented.
No.
> [skip changelog] Document boards.txt hide property

- mkdocs.yml
Documentation fix.
- Incorrect name for the `arduino-cli` command is shown in the command reference section of the documentation's navigation pane.
- `arduino-cli burn-bootloader` is missing from the command reference section of the documentation's navigation pane.
Command reference section of the documentation's navigation pane correctly shows all commands.
No.
> [skip changelog] Fix issues with command reference section of the documentation's navigation pane

- docs/platform-specification.md
The Arduino IDE has a useful feature where a board can be configured to use the "Upload Using Programmer" behavior when the user does an Upload, but this isn't documented.
The feature is documented.
No.
> [skip changelog] Document Arduino IDE's default to Upload Using Programmer feature

- docs/platform-specification.md
Documentaiton update.
Manual platform installation alone was specifically described in the platform specification introduction, which might cause new platform authors to think the specification is only for manually installed platforms. Boards Manager was only mentioned in passing, deep within the document.
Boards Manager installation is also mentioned, with a link to the package_index.json specification.
No.
> [skip changelog] Mention Boards Manager installation option in platform specification intro

- docs/platform-specification.md
The meaning of "upload" is not clearly defined in the platform specification. Outside Arduino's circle, the process we refer to as "upload" may be known by other terms such as "write", "program", or even "download", so it's a good idea to provide a specific definition of what this word means in the Arduino world.
A definition of the termi "upload" is provided in the appropriate section of the Arduino platform specification.
No.
> [skip changelog] Document meaning of "upload" in platform specification

- .github/workflows/release.yaml
update CI
Add a new CI step to automatically update tag & revision of [arduino-cli](https://github.com/Homebrew/homebrew-core/blob/master/Formula/arduino-cli.rb) homebrew formula when a new version of the CLI is released. It should automatically open a PR to the homebrew repo.
no
@rsora remember to add the secret in the settings!
---
> [skip-changelog] Add ci step to automatically update arduino-cli homebrew formula

- .github/workflows/nightly.yaml
Feature?
macOS nightly builds are not notarized.
macOS nightly builds are notarized.
No.
Nightly build from testing: https://downloads.arduino.cc/arduino-cli/nightly/arduino-cli_nightly_test-20200708_macOS_64bit.tar.gz
> [skip changelog] Notarize nightly macOS build

- .github/workflows/release.yaml
The formula should not be updated on pre-releases.
Bug fix.
The "release" GitHub Actions workflow will update the Homebrew formula on every tag, including release candidates.
The "release" GitHub Actions workflow will update the Homebrew formula only on production release tags.
No.
> [skip changelog] Make Homebrew formula update only run on stable releases

- docs/library-specification.md
- docs/platform-specification.md
Docs update
The library and platform specifications are described as "3rd party", yet they apply to all libraries and platforms, including official ones.
The library and platform specifications aren't described as being for "3rd party".
No
> [skip changelog] Remove inaccurate "3rd party" descriptions from documentation

- docs/package_index_json-specification.md
Docs update
Some of the indentation of the example snippets in the package_index.json specification is inconsistent.
All indentation of example snippets in the package_index.json specification is consistent.
No.
> [skip changelog] Use consistent indentation style in example snippets of package_index.json specification

- docs/package_index_json-specification.md
Docs update.
package_index.json specification contains gender-specific grammar.
package_index.json specification uses singular "their" in place of gender-specific grammar.
No.
This violates traditional rules of grammar. I don't think that's a problem, but there is the altenative of rewording the sentence to dodge the issue entirely:
>Many different index files coming from different vendors may be in use, so vendors should name their own index files in a way that won't conflict with others.
However, I feel this makes the meaning of the sentence …
> [skip changelog] Replace gender-specific grammar in package_index.json specification

- docs/library-specification.md
Sources of additional information about the example sketches of libraries are not readily available to library authors.
Links to additional information are provided in the relevant section of the Arduino library specification.
No.
> [skip changelog] Add links to additional information in the examples section of the library specification

- docs/library-specification.md
- docs/platform-specification.md
Arduino IDE and Arduino Web Editor use the term "sketchbook", while Arduino CLI and Arduino Pro IDE use the term "user directory". In order for the documentation to be friendly to all users of Arduino's development software, both terms must be used in the documentation.
docs update
In a couple places, the documentation uses only the term "sketchbook". Arduino IDE and Arduino Web Editor use the term "sketchbook", while Arduino CLI and Arduino Pro IDE use the term "user directory". In order for the documentation to be friendly to all users of Arduino's development software, both terms must be used.
"User directory" is …
> [skip changelog] Always mention "user directory" along with "sketchbook" in documentation

- httpclient/httpclient_config.go
This workaround must be here until viper can UnSet properties:
https://github.com/spf13/viper/pull/519
> Allow empty network.proxy settings

- install.sh
---
Bug fix
---
The installation script's check for a conflicting prior installation in `$PATH` was prone to false positives. For example, any of these examples result in a spurious "An existing arduino-cli was found at..." error:
- Paths differ by a redundant slash in `$PATH`:
```sh
$ export PATH="$PATH:$PWD/bin/"
$ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
..
An existing arduino-cli was found at /home/foo/bin//arduino-cli. Please prepend /home/foo/bin to your $PATH or remove the existing one.
Failed to install arduino-cli
```
- Paths differ by a redundant slash on custom installation path:
```sh
$ …
```
> [skip changelog] Improve install script's check for conflicting installation in $PATH

- docs/platform-specification.md
Previously, only the serial.port property was documented. However, serial.port.file is in widespread use (e.g., Arduino SAMD Boards).
Docs update.
Despite being in widespread use, the `{serial.port.file}` property is not mentioned in the Arduino platform specification.
The `{serial.port.file}` property is documented in the Arduino platform specification.
No.
> [skip changelog] Document serial.port.file property

- docs/library-specification.md
Docs update.
Many of the things documented in the library specification are used as determining factors in library dependency resolution. An understanding of how the components of a library influence dependency resolution priorities can be very helpful to a library developer. However, they might not think to look for valuable information about libraries in the "Sketch build process" documentation.
The "See also" section of the Arduino library specification consists of only a single link.
A link to the relevant section of the sketch build process documentation is provided by the Arduino library specification.
The "See …
> [skip changelog] Add link to library dependency resolution process docs from library specification

- cli/lib/list.go
- test/test_lib.py
Installed libraries' sentences are now shown in `arduino-cli lib list` output.
Now:
```shell
$ ./arduino-cli lib list
Name         Installed Available Location Sentence                                                                      
ArduinoJson  6.11.0    6.15.2    user     An efficient and elegant JSON library for Arduino.                            
AudioZero    1.1.1     -         user     Allows playing audio files from an SD card. For Arduino Zero and MKR1000 only.
Sodaq_HTS221 1.0.0     -         user     An Arduino library for the HTS221 sensor.                                     
```
Before:
```shell
$ ./arduino-cli lib list
Name         Installed Available Location
ArduinoJson  6.11.0    6.15.2    user
AudioZero …
```
> Add Sentence field to lib list output

- .github/workflows/test.yaml
So I've investigated the issue about the CI skip and the required Checks to merge PRs, I've made some tests in a separate repo.
In the `test.yaml` I've added the following config:
```    paths-ignore:
- "docs/**"
- ".github/workflows/docs.yaml"```
Both when pushing on `master` and PRs creation if only `docs.yaml` or anything inside the `docs` folder is modified the Workflow is not run at all.
We discovered that this is an issue because the repo is configured to require the 3 checks generated by the `test-matrix` job to merge a PR.
So I tried to skip conditionally the whole job `test-matrix`, problem is that the required checks are not on `test-matrix` but on `test-matrix (ubuntu-latest)`, `test-matrix …
> [skip changelog] Fix test workflow not running when editing docs

- docs/platform-specification.md
The boards.txt `vid` and `pid` properties are not documented. These properties are becoming increasingly important as the modern Arduino development software takes advantage of them for features based on automatic board detection (e.g., Arduino Web Editor's automatic board selection, `arduino-cli board attach <port>`)
The `vid` and `pid` properties of boards.txt are documented in the platform specification.
No.
> [skip changelog] Document the boards.txt vid and pid properties

- docs/package_index_json-specification.md
Docs update
The complex and important concept of referencing tools in a package index is not explained to a sufficient degree.
The aspects of tools referencing that were previously unclear are now more thoroughly covered by the documentation.
No.
> [skip changelog] Improve documentation re: referencing tools in a package index

- docs/platform-specification.md
Docs update
Documentation of the auto-set property makes it sound like a convenience feature, with the `build.board` property only needed if you prefer a custom value for some reason. However, the resulting warning (`Warning: Board foo:bar:baz doesn't define a 'build.board' preference. Auto-set to: BAR_BAZ`) can cause confusion and act as a "red herring" for users of board definitions that don't define a `build.board` property.
The platform specification mentions that not defining a `build.board` property results in a warning.
No
> [skip changelog] Document that use of auto-set build.board property results in warning

- mkdocs.yml
Bug fix.
The [`pymdownx.magiclink`](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/) Python-Markdown extension adds support for GitHub-style auto-linked issue/PR/commit/user references in the documentation. In order for the issue/PR/commit references to work correctly in the case where no repository is specified, the extension must be configured with the owner and repository name of the repository that is using it. As a result of not having been updated after it was copied, the extension was previously configured for the `squidfunk/mkdocs-material` repository, which would result in any references that didn't specify a …
> [skip changelog] Use correct configuration for MkDocs pymdownx.magiclink extension

- docsgen/main.go
Feature?
By default, Cobra automatically adds a date stamp to the generated command line reference content. Having a date stamp is not necessarily a bad thing, though it's doubtful that it is useful enough to justify its presence. However, the formatting of this date stamp causes it to be shown as an item in the table of contents of each command reference page, inappropriately located under the "SEE ALSO" heading. This clutters up the documentation without providing any benefits at all.
---
---
Cobra has provided an option to disable the automatic insertion of the date …
> [skip changelog] Disable date stamp in command line reference documentation

- docs/platform-specification.md
Docs update
[ArduinoCore-API](https://github.com/arduino/ArduinoCore-API) is an important resource for core authors, but they may not be aware of its existence. Aspiring platform authors are very likely to read the Arduino platform specification, but it contains no mention of ArduinoCore-API.
The existence and purpose of ArduinoCore-API is mentioned in the "Cores" section of the Arduino platform specification.
No.
> [skip changelog] Mention ArduinoCore-API in the "Cores" section of the platform specification

- docs/library-specification.md
Docs update.
Previously, the `precompiled` field of library.properties only supported one value: `true`. As it became apparent that there were two distinct use cases for this feature (https://github.com/arduino/arduino-builder/issues/353), it was necessary to add a new `full` option so that both use cases could be fully supported (https://github.com/arduino/arduino-cli/pull/611). However, the `full` option is not documented.
The `precompiled` field of library.properties' `full` value is documented in the appropriate section of the Arduino library specification.
No.
* …
> [skip changelog] Document library.properties precompiled field's "full" option

- docs/platform-specification.md
Docs update
The Arduino platform specification provides no documentation for the precompiled libraries system.
Documentation on what is required for platforms to support precompiled libraries is provided by the platform specification.
No.
I'm unsure on what the best approach is for documenting which recipes can use `{compiler.libraries.ldflags}` (and properties in general).  This property is only used by official platforms in `recipe.c.combine.pattern`, so I documented it in that section, but that gives the impression that it's only accessible in …
> [skip changelog] Document compiler.libraries.ldflags property in platform specification

- docs/platform-specification.md
Docs update.
serial.disableDTR and serial.disableRTS properties of boards.txt are undocumented.
serial.disableDTR and serial.disableRTS properties of boards.txt are documented under the "boards.txt" section of the Arduino platform specification.
No.
> [skip changelog] Document serial.disableDTR and serial.disableRTS properties of boards.txt

- docs/library-specification.md
Docs update.
Arduino CLI supports the use of a specific folder structure to provide precompiled library binaries for different ARM floating point ABI configurations, but this feature is not documented.
The ARM floating point ABI folders for precompiled Arduino libraries feature is documented in the Arduino library specification.
The documentation was restructured a bit by creating a new section for information about the precompiled library folder structure so that this feature could be fully documented without harming the readability of the section that documents the library.properties fields.
* **Does this PR …
> [skip changelog] Document floating point ABI configuration folders for precompiled libraries

- .github/workflows/jira-issue.yaml
Whenever a new issue is created in this repository this new workflow is triggered, it creates a new issue on Jira with the same content as the GH one and add labels to both. This is done to ease grooming of new issues.
Newly created issues on Github are processed manully.
Newly created issues on Github are mirrored on Jira to ease grooming.
No.
None.
---
> [skip changelog] Add workflow to mirror issue on Jira to ease grooming

- .github/workflows/jira-issue.yaml
Fixes indentation in the Jira grooming workflow.
---
> [skip changelog] Fix indentation of Jira grooming workflow

- legacy/builder/gcc_preproc_runner.go
- legacy/builder/setup_build_properties.go
Previously we added `-DARDUINO_LIB_DISCOVERY_PHASE` to the gcc command line during the library discovery phase: unfortunately this has an incompatiblity with compilers using non-standard `-d` flag instead of `-D` as reported here: https://github.com/arduino/arduino-cli/pull/633#issuecomment-659529026
To fix this behaviour this PR adds a new build variable `{build.library_discovery_phase}` that is set to `1` during library discovery or to `0` during normal build.
The platforms that wants to use it may add in their `platform.txt` something like:
```
build.library_discovery_phase=0
build.library_discovery_phase_flag=-DARDUINO_LIBRARY_DISCOVERY_PHASE={build.library_discovery_phase}
```
and use `{build.library_discovery_phase_flag}` inside the `gcc` command line.
This way the gcc command line …
> Fix ARDUINO_LIB_DISCOVERY_PHASE automatic flag incompatiblity

- cli/cli.go
- cli/outdated/outdated.go
- cli/update/update.go
- cli/upgrade/upgrade.go
- mkdocs.yml
- test/test_outdated.py
- test/test_update.py
- test/test_upgrade.py
Add three new commands:
* `outdated`
* `update`
* `upgrade`
Those commands don't exist.
* `arduino-cli outdated` returns a list of cores and libraries that are outdated, showing the currently installed version and the newly available one.
* `arduino-cli update` downloads and installs the index for installed cores and libraries if new ones are available.
* `arduino-cli upgrade` downloads and installs all available upgrades for installaed cores and libraries.
Nope.
None.
---
> Add outdate, update and upgrade commands

- .github/workflows/jira-issue.yaml
Adds new workflow to mirror issue from Github to Jira when an authorized user adds a certain label to it.
---
> [skip changelog] Add workflow to mirror issue on Jira when labeled

- docs/platform-specification.md
Docs update.
Despite being in widespread use, the builder's behavior of generating a default `recipe.preproc.macros` when the platform author doesn't define one is undocumented.
The builder's behavior of generating a default `recipe.preproc.macros` when not defined is documented in the Arduino platform specification.
No
Reference: https://github.com/arduino/arduino-cli/blob/3775f51183dd8b40afa9f9b1b4bebcc1db7709cb/legacy/builder/gcc_preproc_runner.go#L67-L70
---
See [how to …
> [skip changelog] Document automatic generation of recipe.preproc.macros

- docs/platform-specification.md
Some global predefined properties are undocumented:
- `{software}`
- `{name}`
- `{_id}`
- `{build.fqbn}`
- `{build.source.path}`
- `{extra.time.utc}`
- `{extra.time.local}`
- `{extra.time.zone}`
- `{extra.time.dst}`
The Arduino platform specification documents all global predefined properties.
No
> [skip changelog] Add previously undocumented global predefined properties to platform specification

- docs/platform-specification.md
Docs update.
Despite being in widespread use, the upload verification system of Arduino platforms is undocumented.
The upload verification system is documented in the Arduino platform specification.
No
References:
- https://github.com/arduino/Arduino/pull/4873
- https://github.com/arduino/Arduino/pull/5427
> [skip changelog] Document the upload verification system

- docs/platform-specification.md
Docs update
Bundled libraries are a very important component of most Arduino platforms, but this capability only has a brief mention in https://arduino.github.io/arduino-cli/dev/platform-specification/#referencing-another-core-variant-or-tool and https://arduino.github.io/arduino-cli/dev/sketch-build-process/#location-priority, with no explanation of what they are or how they are used.
Even fairly advanced Arduino users are often confused by the fact that Arduino libraries are stored in multiple locations.
Platform bundled libraries are documented in the Arduino platform specification.
- **Does …
> [skip changelog] Document platform bundled libraries

- docs/platform-specification.md
The platform referencing documentation content in the Arduino platform specification falls into four categories:
- general
- core
- variant
- tool
but it's not obvious where the content for each category began and ended.
The referencing documentation content is clearly separated into its areas of applicability.
No.
> [skip changelog] Add headings to delineate the platform referencing documentation

- test/test_compile.py
- test/test_core.py
Bug fix.
The `test_compile_without_precompiled_libraries` integration test fails due to a release of the arduino:mbed platform that introduces an incompatibility with the Arduino_LSM9DS1 library used by that test. This failure has nothing to do with any change to Arduino CLI and doesn't indicate any problem with Arduino CLI, so it's not helpful.
Where appropriate, platforms used by tests are pinned. This fixes the spurious test failure.
In some integration tests, using the latest version of a platform is appropriate and useful. In those cases, the platform was not pinned.
- **Does this PR introduce …
> [skip changelog] Pin platform versions used in integration tests

- docs/platform-specification.md
Docs update.
The `build.library_discovery_phase` property is undocumented.
The `build.library_discovery_phase` property is documented in the Arduino platform specification.
No.
Introduction of `ARDUINO_LIB_DISCOVERY_PHASE` macro: https://github.com/arduino/arduino-cli/pull/633
Introduction of `build.library_discovery_phase` property: https://github.com/arduino/arduino-cli/pull/838
Note: I am guessing that the next release versions will be:
- Arduino CLI: 0.12.0
- Arduino Builder: 1.6.0
- Arduino IDE; 1.8.14
If things go …
> [skip changelog] Document build.library_discovery_phase property in platform specification

- Taskfile.yml
Bug fix.
We now use Prettier to enforce a formatting standard on the Arduino CLI documentation. The generated documentation is not compliant with this standard, which causes some problems:
- Incorrect list formatting of gRPC reference's table of contents. Prettier uses a two space indent. Because the stock Python-Markdown renderer requires a four space indent for nested lists, it was necessary to start using the [`mdx_truly_sane_lists` extension](https://github.com/radude/mdx_truly_sane_lists) to support the Prettier indent size. The use of the extension caused the four space indent used in the generated gRPC interface …
> [skip changelog] Format generated documentation

- cli/update/update.go
- test/test_update.py
Small feature change.
To show outdated cores and libraries after running `update` you must use the flag `--outdated`.
To show outdated cores and libraries after running `update` you must use the flag `--show-outdated`.
Not really.
---
> Change update --outdated flag to --show-outdated

- docs/platform-specification.md
Docs update.
The sketch debugging system for platforms is undocumented.
The sketch debugging system is documented in the Arduino platform specification.
No.
References:
- `debug.tool`, `tools.TOOL_NAME.debug.pattern`
- https://github.com/arduino/arduino-cli/pull/590
- https://github.com/arduino/ArduinoCore-samd/commit/e6af98a744637d19bd9896150cbddf36b06e2883
- `compiler.optimization_flags`
- https://github.com/arduino/arduino-cli/pull/593
- https://github.com/arduino/ArduinoCore-samd/commit/cf72acfe1b74c2e00d77dcba65f664bd09582 …
> [skip changelog] Document debug system in platform specification

- docs/FAQ.md
Docs update.
Users may wonder whether Arduino CLI provides Serial Monitor functionality, or why not.
The FAQ contains an explanation of why Arduino CLI doesn't provide a Serial Monitor.
No
Related: https://github.com/arduino/arduino-cli/issues/876
---
> [skip changelog] Add FAQ item re: Serial Monitor

- .github/workflows/test.yaml
Feature.
An outdated version of the `codecov/codecov-action` GitHub Actions action is pinned in the `test` workflow. This outdated version imposes a requirement for an upload token. This token is defined by a repository secret, which causes two issues:
- The `test` workflow fails when run in forks of the repository because they are missing this secret. This spurious failure will cause confusion to contributors who are checking to be sure their contribution will pass CI.
- We are prevented from configuring the workflow to trigger on `pull_request` events because GitHub Actions disables secrets when a workflow is triggered by an …
> [skip changelog] Remove unnecessary token input from Codecov upload steps of test workflow

- .github/workflows/docs.yaml
- .github/workflows/link-validation.yaml
- .github/workflows/test.yaml
Bug fix.
CI workflows use the `v1.0.0` ref of the [`arduino/setup-protoc` action](https://github.com/arduino/setup-protoc). This presents two issues:
- Because that version of the action is missing metadata for its `repo-token` input, an  `Unexpected input(s) 'repo-token', valid inputs are ['version']` warning is displayed in every workflow run summary, which could result in confusion for contributors.
- Pinning to a specific version results in either not benefiting from ongoing development, or the need to update the workflows on every release.
The `v1` ref of the action is specified, which has two …
> Use v1 ref of arduino/setup-protoc action

- .github/workflows/link-validation.yaml
- .github/workflows/publish-docs.yaml
- .github/workflows/python-lint.yaml
- .github/workflows/test.yaml
- .github/workflows/validate-docs.yaml
Feature.
Contributors should run CI in their feature branch to make sure it's passing before submitting a PR. However, the CI workflows are configured to run only on pushes to the `master` branch, meaning that contributors need to modify the workflows just to get them to run on a feature branch. It's very unlikely that a contributor would do that, so they are more likely to just submit the PR, then if CI on the PR fails push fixup commits until CI is passing.
Workflows that are useful to contributors are configured to be triggered by pushes to any branch.
The `docs` workflow had two distinct uses: …
> [skip changelog] Run CI workflows that are useful to contributors on pushes to any branch

- README.md
- docs/CONTRIBUTING.md
Bug fix.
The docs workflow was split into two workflows: publish-docs and validate-docs, but the references to the original workflow were not updated. This resulted in two problems:
- The "docs" badge in the readme won't reflect the true state of the documentation publishing system
- Broken link in CONTRIBUTING.md
All references to the `docs` workflow have been updated to point to the `publish-docs` workflow.
No
> [skip changelog] Update broken or outdated references to docs workflow

- .github/workflows/arduino-stats.yaml
- .github/workflows/github-stats.yaml
- .github/workflows/i18n-nightly-push.yaml
- .github/workflows/i18n-weekly-pull.yaml
- .github/workflows/link-validation.yaml
- .github/workflows/nightly.yaml
These workflows use resources that are only available when run in the arduino/arduino-cli repository, so would always fail when they run in a repository. They are of no value to fork repositories. They are triggered by the schedule event, so they cause regular annoying and confusing workflow failure notifications for every fork owner.
Bug fix.
It's extremely annoying to have a fork of this workflow with GitHub Actions workflows enabled because there are multiple workflows that are triggered by `schedule` events which rely on secrets that are only defined when run in the upstream repository. This causes the fork owner to get lots …
> [skip changelog] Disable scheduled workflows that would always fail from running in forks

- .github/workflows/test.yaml
When running the `test.yaml` workflow successfully a build artifact is uploaded to ease testing of new features and PR changes.
---
> [skip changelog] Build is now uploaded as artifact when running tests workflow

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Bugfix
Readme and template for PR have links pointing to an older version of the documentation
---
> [skip changelog] fix docs links pointing to an older version

- docs/installation.md
Bug fix.
Prettier is configured to wrap lines in Markdown files at 120 characters. The reference definitions for the [nightly ARM download links](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds) happen to be longer than 120 characters, and so get wrapped.
With the modern Markdown specification, this is permitted:
https://spec.commonmark.org/0.29/#link-reference-definitions
> A link reference definition consists of a link label, indented up to three spaces, followed by a colon (:), optional whitespace …
> [skip changelog] Prevent Prettier from wrapping nightly download link definitions

- commands/upload/upload.go
- executils/executils.go
- executils/null.go
Some tools detects if the program is running from terminal by looking at the stdin/out bindings.
Previously stdin wasn't bound to any custom stream, this fact lead `avrdude` to think it was run from terminal (instead of a script) and start it in "safe-mode". This turn out to be a problem in some cases, see #844 
From the avrdude source code:
```
if (isatty(STDIN_FILENO) == 0)
safemode  = 0;       /* Turn off safemode if this isn't a terminal */
```
So we need to ensure that `isatty(STDIN_FILENO)` returns `0` when we run tools.
I've tried to run the following test program:
```c
#include <stdio.h>
#include <unistd.h>
#include <io.h>
int main(void) {
printf("%d\n", isatty(STDIN_FILENO));
return 0;
}
```
compiled with:
```
x86_64-pc-cygwin-gcc test.c -o test-cygwin
```
and 
``` …
```
> Fix tools tty detection (fix avrdude running in safe mode)

- commands/bundled_tools_serial_discovery.go
Fixes `board list` always failing.
`board list` fails.
`board list` doesn't fail.
Nope.
No other info.
---
> Fix board list failing because stdin is already set

- .gitignore
When I build the CLI on Windows, I do not want to see the executable as
an outgoing Git change. Same as on POSIX.
Running `git check-ignore -v arduino-cli` on macOS shows which line is used to ignore the executable:
```
.gitignore:2:/arduino-cli	arduino-cli
```
This PR adjusts the `.gitignore` file, to improve the contributing experience for Windows devs.
Feature.
When I run `go build` on Windows, I have a git outgoing change.
After building the CLI from the sources, and running `git status -s` it returns with nothing. Previously, it was:
```
git …
```
> Git-ignore the `arduino-cli.exe` on Windows.

- cli/compile/compile.go
- docs/library-specification.md
- docs/package_index_json-specification.md
- docs/platform-specification.md
- docs/sketch-build-process.md
Docs update
Some of the wording of the documentation is less clear or readable than it might be.
The wording of the documentation is improved without any significant changes to the informational content.
No
> [skip changelog]Make general minor improvements to the wording of the documentation

- docs/CONTRIBUTING.md
- docs/FAQ.md
- docs/index.md
- docs/integration-options.md
- docs/library-specification.md
- docs/package_index_json-specification.md
- docs/platform-specification.md
- docs/sketch-build-process.md
- docs/sketch-specification.md
- rpc/commands/board.pb.go
- rpc/commands/board.proto
- rpc/monitor/monitor.proto
Docs fix.
There are some minor typos and formatting issues in the documentation.
The documentation has no (or at least less) typos and the formatting is slightly improved.
No
> [skip changelog]Fix typos and formatting in the documentation

- cli/instance/instance.go
- test/test_board.py
- test/test_core.py
update
When users run a command requiring `package_index.json` to be already there (for example `core install arduino:samd@1.8.6`) the CLI was giving this error: `Error installing: There were errors loading platform indexes`
https://github.com/arduino/arduino-cli/issues/792
Now it should download automatically the `package_index.json` when it's not already in place and it is required by the command the user is running.
no, the user can still use …
> Package index is now downloaded automatically when is required

- commands/core/install.go
Follows https://github.com/arduino/arduino-cli/pull/893#issuecomment-673556652
> Does it really add anything to add an isTrusted flag here? AFAICS, an "untrusted" platform can still provide custom compiler binaries and compiler commands in platform.txt, so this trusted flag would only prevent running untrusted code at platform install time, as soon as you actually use the platform to compile a sketch, untrusted code will be ran in any case?
/cc @luigigubello @rsora
> Allow post_install for untrusted platforms

- cli/upload/upload.go
docs update
The upload command documentation does not specify that the sketch isn't compiled prior to upload. I thought this would be a helpful clarification since that's the behavior in the Arduino IDE.
The upload command documentation clarifies that the upload command does not compile the specified sketch.
No, doc changes.
> [skip changelog] Clarify in documentation that the upload command will not compile beforehand

- arduino/cores/packagemanager/install_uninstall.go
- commands/bundled_tools_serial_discovery.go
- commands/debug/debug.go
- commands/upload/upload.go
- executils/executils.go
- executils/process.go
- test/test_board.py
This helper should avoid common pitfalls arising mainly after the adoption of the `avrdude-stdin-hack`, for example see #904.
It also streamlines some of the most common operations (like process Kill or Signal).
> `executils` refactoring

- cli/cli.go
Docs update.
In order to specify multiple Boards Manager URLs via a single `--additional-urls` option, they must be in a comma-separated list. However, this is not at all clear from the current documentation:
>--additional-urls strings   Additional URLs for the board manager.
The format of of the list of URLs passed via the `--additional-urls` option is documented.
No
> [skip changelog] Specify list format for --additional-urls option

- docs/platform-specification.md
---
Docs update
---
The system of support for external programmers in Arduino platforms, although complex and in widespread use, is essentially undocumented.
---
The programmers features of Arduino platforms are fully documented:
- platform.txt
- "Burn Bootloader"/`erase` and `bootloader` actions
- "Upload using Programmer/`program` action
- Programmer inheritance from referenced platforms
---
No
This pull request takes into …
> [skip changelog] Document the programmers system of Arduino platforms

- README.md
- cli/cli.go
- cli/core/search.go
- configuration/defaults.go
- docs/configuration.md
- docs/getting-started.md
- docs/index.md
Docs update
The term "Boards Manager" has been well established in the Arduino development tools and documentation. Perhaps influenced by the mismatch with the singular term used for its companion "Library Manager", Arduino CLI's documentation has diverged from this standard by sometimes (but not always) referring to it as "Board Manager".
Boards Manager is always referred to by the standardized term in the documentation.
No …
> [skip changelog]Use standardized term for Boards Manager in documentation

- docs/CONTRIBUTING.md
Docs update.
The arduino/arduino-cli repository's automatic changelog generation system adds a changelog item for every commit, except those that start with "[skip changelog]". This is useful for keeping the changelog to only mentioning the changes that are significant to the user.
All pull requests are merged using GitHub's "Squash & Merge" feature.
The behavior of "Squash & Merge":
- If the PR only contains a single commit, the pre-filled squash commit message is taken from the commit, not the PR.
- If the PR contains …
> [skip changelog] Fix contributing instructions re: skipping changelog

- docs/platform-specification.md
Docs update
The inherited resources resulting from a core reference are clearly documented. However, the variant reference mentioned the non-inheritance of platform.txt properties alone. For me, this left it unclear whether the lack of mention of the other resources implied that variant and tool references resulted in their inheritance, and that it was only considered necessary to document it once in the platform reference documentation.
One option for resolving this would be to remove the …
> [skip changelog] Completely document resources not inherited from referenced platform

- docs/platform-specification.md
Docs update
The platform post-install script is undocumented. This feature has recently been [made available to 3rd party platforms](https://github.com/arduino/arduino-cli/pull/911), so documenting it becomes even more important.
The platform post-install script is documented
No
References:
- https://github.com/arduino/arduino-cli/pull/893
- https://github.com/arduino/arduino-cli/pull/911
> [skip changelog] Document platform post-install script in platform specification

- arduino/cores/packagemanager/identify.go
- arduino/cores/packagemanager/package_manager_test.go
- arduino/cores/packagemanager/testdata/custom_hardware/test/avr/boards.txt
This allows both uppercase and lowercase properties (e.g. vid and pid)
from boards.txt and matches what the Java IDE does:
https://github.com/arduino/Arduino/blob/5e30bec23/arduino-core/src/cc/arduino/packages/BoardPort.java#L185
Bugfix
USB ids or other identifying properties from a (serial) port are matched case sensitively, so if boards.txt specifies uppercase usb ids, `board list` does not match the port with the corresponding board.
Properties are matched case insensitively, just like the …
> Match port properties (e.g. USB vid/pid) case insensitively against board.txt values (in e.g. board list)

- arduino/resources/install.go
- test/test_core.py
- test/testdata/test_index.json
Add check of the package checksum when installing a package.
No check on the checksum is performed.
The checksum is checked before installing a new package.
---
> Add checksum check before installing a package

- poetry.lock
- pyproject.toml
- test/common.py
- test/conftest.py
- test/pytest.ini
- test/test_board.py
- test/test_compile.py
- test/test_core.py
- test/test_lib.py
- test/test_outdated.py
- test/test_update.py
- test/test_upgrade.py
- test/test_upload.py
Optimizes integration tests so that they're a bit faster to run.
---
> [skip changelog] Optimize a bit integration tests

- docs/platform-specification.md
Arduino CLI (and thus Arduino Pro IDE as well) provides the very interesting capability to modify referenced tool recipes via overrides in the referencing platform's platform.txt but this is undocumented.
The equivalent capabilty is mentioned in the core reference documentation, so the lack of mention of it in the tools referencing section could be seen as implying that it's not supported.
Overrides don't apply to referenced variants, so this is not a universal capability that can be documented in the general purpose …
> [skip changelog] Document ability to override properties of referenced tools

- arduino/serialutils/serialutils.go
- commands/upload/upload.go
So they can be reused in other projects.
> Factoring out serial subrotuines to perform board reset

- docs/sketch-build-process.md
Docs update
Although Arduino Web Editor uses the same build system as the other Arduino development software, the cloud-based nature can make it more difficult to determine library locations.
Although very convenient, Arduino Web Editor having every one of the thousands of Library Manager libraries pre-installed does result in a higher incidence of header filename collisions. This means it is especially important for Arduino Web Editor users to understand library location priorities. However, the sketch build process …
> [skip changelog] Document library location priorities in Arduino Web Editor

- arduino/libraries/libraries.go
- arduino/libraries/loader.go
- commands/lib/list.go
- test/test_lib.py
Otherwise, automatic library discovery would be affected.
Fix #960
> Do not overwrite full headers list with declared 'includes' in library.properties

- README.md
This makes it easier for contributors to participate by beta testing Arduino CLI.
Docs update.
It may not be obvious how to find the nightly builds of Arduino CLI.
It is easy to find nightly builds and participation in the project by beta testing is encouraged.
No
> [skip changelog] Add nightly builds link to readme

- cli/config/dump.go
- cli/config/init.go
- commands/daemon/settings_test.go
- configuration/configuration.go
- configuration/configuration_test.go
- main.go
- test/test_config.py
Changes the behaviour of `config init` and `config dump` when using the `--config-file` flag.
`config init --dest-file <some_path_file>` doesn't initialize a new config file using the specified path and always overrides existing file in default config path.
Calling `config init --dest-file <path> --dest-dir <path>` creates a new config file in path specified by `--dest-dir`.
Calling `config dump --config-file <some_path_file>` always prints the default configurations.
Calling `config init …
> Change behaviour of --config-file flag with config commands

- docs/CONTRIBUTING.md
Docs update.
Pull requests are only one of the possible ways to contribute to Arduino CLI, yet they are the only one mentioned in
the "how to contribute" documentation.
Multiple contribution options are documented, providing more opportunities to
assist in this project.
No
Based on https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md
> [skip changelog] Document all contribution options in contributing guidelines

- docs/platform-specification.md
Docs update.
`upload.maximum_data_size` and `upload.maximum_size` are properties used by the build system to fail
compilation when memory usage exceeds a threshold and to calculate the relative memory usage for display in the console.
These important properties, used in most boards platforms are undocumented.
`upload.maximum_data_size` and `upload.maximum_size` are documented.
No
> [skip changelog] Document available memory build properties

- docs/package_index_json-specification.md
Docs update
The old tool definition example in the package_index.json specification was quite outdated. It did not demonstrate the
ARM hosts that have become more important since the specification was written. The macOS host value was antiquated.
This could lead to the reader being left with no clear idea of how to create the tool definitions for those hosts.
The example uses the current tool definition, demonstrating all common hosts.
No
> [skip changelog] Update the tool definition example

- docs/platform-specification.md
Docs update
The "Build process" section of the Arduino platform specification contains a short summary of the Arduino sketch build
process. The "Sketch build process" page of the documentation provides much more detailed information, which wouldn't be
appropriate in the platform specification, but could well be of interest to a platform developer.
Adding a link to the "Sketch build process" documentation from that section of the Platform specification makes all
relevant information easily …
> [skip changelog] Link to Sketch build process docs from Platform specification

- .flake8
Bug fix.
Flake8/pycodestyle has a pair of mutually exclusive checks:
- [`W503`](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes:~:text=W503%20(*)%09line%20break%20before): line break before binary operator
- [`W504`](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes:~:text=W504%20(*)%09line%20break%20after): line break after binary operator
Having both these checks enabled results in a failed check when there is a line break at a binary operator, which can't be
resolved by moving the operator. …
> [skip changelog] Resolve impossible to satisfy Flake8 configuration

- commands/core/search.go
- commands/core/search_test.go
- commands/core/testdata/package_index.json
- test/test_core.py
- test/testdata/test_index.json
Fixes `core search` command.
`core search` command doesn't search in a Platform's Package name, maintaner or website fields.
`arduino-cli core search retro --additional-urls https://www.retrokits.com/rk002/arduino/package_retrokits_index.json` doesn't find any core.
`arduino-cli core search rk --additional-urls https://www.retrokits.com/rk002/arduino/package_retrokits_index.json` finds the expected Retrokit core.
`core search` command now searches in a Platform's Package name, maintaner or …
> Fix core search command not searching through package terms

- arduino/cores/cores.go
- arduino/cores/cores_test.go
- test/test_core.py
Bug fix.
The platform tool dependency check was giving false negatives due to comparing pointers instead of version values.
This caused tools to be removed during platform uninstallation even when another installed platform had a dependency on
that tool.
The `semver` package's `Equal` method is used for the comparison, resulting in accurate tool dependency determination.
No
Steps to reproduce the bug fixed by this PR:
``` …
```
> Fix platform tool dependency determination

- .github/workflows/i18n-nightly-push.yaml
- .github/workflows/i18n-weekly-pull.yaml
- .github/workflows/link-validation.yaml
- .github/workflows/publish-docs.yaml
- .github/workflows/test.yaml
- .github/workflows/validate-docs.yaml
- docs/CONTRIBUTING.md
This changes the version of Go used in the CI from 1.15 to 1.14. 
The cross compilation container we use to compile the project doesn't support Go 1.15 in OS X for now, thus the revert to an older version.
---
> [skip changelog] Change CI Go version from 1.15 to 1.14

- arduino/cores/packagemanager/loader.go
- arduino/cores/packagemanager/package_manager_test.go
- cli/cache/clean.go
- cli/cli.go
- cli/compile/compile.go
- cli/config/dump.go
- cli/config/init.go
- cli/daemon/daemon.go
- commands/board/list_test.go
- commands/compile/compile.go
- commands/core/search_test.go
- commands/daemon/settings.go
- commands/daemon/settings_test.go
- commands/instances.go
- configuration/configuration.go
- configuration/configuration_test.go
- configuration/defaults.go
- configuration/directories.go
- docsgen/main.go
- httpclient/httpclient_config.go
- i18n/i18n.go
- main.go
- telemetry/telemetry.go
- test/test_config.py
Refactors how the configs are initialized and fixes `config init`.
Configs are managed using the `viper` package singleton, `config init` command reads from existing settings when initializing a new config file.
Configs are not managed anymore with the `viper` package singleton but using a global variable internal to the `configuration` package of the `arduino-cli`.
The `config init` command now initializes new config files using the default values without reading from existing files.
- **Does …
> Refactored config to not use viper singleton instance

- commands/upload/upload.go
- commands/upload/upload_test.go
This PR comes as a regression fix after seeing the comment from @janjongboom https://github.com/arduino/arduino-cli/issues/765#issuecomment-699678646.
In arduino-cli 0.12.0 (and previous) using `--input-dir path/to/firmware` with a directory containing:
```
path/to/firmware/firmware.ino.bin
path/to/firmware/some_other_firmware_name.ino.bin
```
will not produce any error and the CLI will successfully upload using `firmware.ino.bin` (because the containing folder had the same name `firmware` as the file used for upload `firmware.ino.bin`).
After reintroducing the `--input-file` flag in #777 we had to change the search algorithm in the build-path folder, but to avoid regressions we also implemented a [very long unit-test coverage](https://github.com/arduino/arduino-cli/blob/master/commands/up …
> Further refine the cases handled by --input-dir

- cli/board/list.go
- cli/feedback/exported.go
- cli/feedback/feedback.go
- commands/board/list.go
- commands/bundled_tools_serial_discovery.go
Adds a new flag to an existing command.
`board list` command shows only the connected boards when called.
`board list` can now be called with the `--watch` or `-w` flag to keep it running and print an updated list of connected boards as soon as the discovery tools detects a change.
No.
I don't we have a reliable way of testing this with automated tests.
---
See [how to …
> Add flag to board list command to watch for connected and disconnected boards

- cli/core/search.go
- cli/lib/search.go
- test/test_core.py
- test/test_lib.py
Enhances existing commands.
Calling `core search` or `lib search` doesn't update indexes before searching.
Calling `core search` or `lib search` now updates indexes before searching.
No.
This fixes #984.
---
> Core and lib search command now update indexes first

- test/test_core.py
A small fix in the integration tests.
Tests might fail some times if indexes update is slower than usual.
Tests should not fail anymore if indexes update is slow.
No.
None.
---
> [skip changelog] Fix core search tests

- mkdocs.yml
Docs fix.
The `core update-index` command is incorrectly written as "core update index" in the title of the command reference documentation page:
https://arduino.github.io/arduino-cli/latest/commands/arduino-cli_core_update-index/
The command is correctly written `core update-index` in the title of the page.
No.
> [skip changelog] Correct command name command reference page title

- test/test_core.py
Fixes some tests failing.
`core search` tests are sometimes failing.
Tests should not failing anymore.
No.
None.
---
> [skip changelog] Fix core search command tests

- cli/lib/list.go
- test/test_lib.py
Clarifies output of an existing command.
Calling `lib list --updatable` command outputs `No libraries installed.`.
Calling `lib list --updatable` command outputs `No updates available.`.
No.
None.
---
> Change lib list --updatable output to be clearer if no lib is updatable

- cli/compile/compile.go
- test/test_compile.py
Bug fix.
Setting either `sketch.always_export_binaries` in config file or `ARDUINO_SKETCH_ALWAYS_EXPORT_BINARIES` as env var to `true` would not export binaries when `compile` command is run.
Setting both `sketch.always_export_binaries` in config file and `ARDUINO_SKETCH_ALWAYS_EXPORT_BINARIES` as env var to `true` works as expected and binaries are export when `compile` command is run.
No.
None.
---
See [how to …
> Fix binaries not being exported when using settings or env var

- version/version.go
Updates `version` command.
Alpha is not specified when printing version.
Calling `version` command specifies that we're in alpha.
Example: `arduino-cli alpha Version: 0.0.0-git Commit: 83abde23`
No.
None.
---
> Add alpha to version

- arduino/discovery/discovery_test.go
- arduino/discovery/testdata/cat/.gitignore
Running command through `go run ...` will introduce artificial delays and this affects the test on `discoveries` because it relies on timeouts.
Now the test program is built for real instead of being run through `go run ...`
> Fixed discovery tests timeouts

- go.mod
- go.sum
- legacy/builder/merge_sketch_with_bootloader.go
This patch includes https://github.com/facchinm/gohex/commit/be2a6be257904703762abd66e6ce630074e3ca01 , which allows supporting .hex sections bigger than 64KB. 
Should fix https://github.com/arduino/ArduinoCore-avr/issues/366 and https://github.com/arduino/arduino-cli/issues/1009
See linked issues
The produced `with_bootloader.hex` and `with_bootloader.bin` can be flashed and are functional
---
See [how to …
> Temporary fix for incorrect merge sketch+bootloader

- docs/library-specification.md
- docs/sketch-specification.md
The recent implementation of DDoS countermeasures required the update of `arduino.cc` links in the documentation that caused CI checks t fail
Link updates for Arduino Reference pages
---
> [skip changelog] Update arduino.cc links to https://www.arduino.cc in documentation

- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
update the CI
The CI now uses a `.p12` certificates and uses an action to handle keychain unlocking. Other improvements have been added.
Now gon is installed through homebrew.
The `Notarize binary, re-package it and update checksum` step has been split in two different steps: one simple step to notarize and sign and the other one to change permission, calculate the checksum and repackage the binary
no
---
See [how to …
> [skip changelog] Update notarization job, now usable with p12 cert format

- .github/workflows/check-certificates.yml
If the certificates fail verification, a notification will be posted on the #team_tooling Slack channel.
If the certificates expire in less than 30 days, a notification will be posted on the #team_tooling Slack channel.
Feature
It's possible that the macOS code signing certificate could expire before the maintainers notice that it needs to be renewed.
A scheduled CI workflow checks the CI certificate for validity and pending expiration. If the certificate is found to be invalid or will expire in …
> [skip changelog] Add workflow to check for problems with certificates

- cli/lib/install.go
- configuration/defaults.go
- test/test_lib.py
Changes an existing command flags.
`--git-url` and `--zip-file` flags can be freely used in `lib install`.
`--git-url` and `--zip-file` flags are now hidden by default and must be explicitly enabled by setting `library.enable_unsafe_install` to `true` in `arduino-cli.yaml` or by using the env var `ARDUINO_ENABLE_UNSAFE_LIBRARY_INSTALL`. 
Yes, but I suppose it won't be an issue since the feature has been added recently and released only on nightlies. …
> lib install --git-url and --zip-file must now be esplicitly enabled

- legacy/builder/resolve_library.go
- test/test_compile.py.orig
- test/testdata/sketch_with_multiple_custom_libraries/sketch_with_multiple_custom_libraries.ino
Fixes a bug.
Including multiple custom libraries with identical name but different sources makes the `compile` to remain stuck in a loop.
`compile` command doesn't stuck in a loop anymore when including multiple custom libraries.
Nope.
Fixes #973.
---
> Fix compile command stuck in a loop when including multiple custom libraries

- legacy/builder/builder_utils/utils.go
- legacy/builder/ctags_runner.go
- legacy/builder/phases/linker.go
- legacy/builder/phases/sizer.go
- legacy/builder/preprocess_sketch.go
- legacy/builder/recipe_runner.go
- legacy/builder/utils/utils.go
This is another refactoring of the `legacy` package.
As for #1064:
> These are smaller/medium changes that are preparatory for other bigger PR.
> 
> I found myself juggling those small patches here and there in other branches, so I've decided to bite the bullet and put them in a smaller PR and merge them once for all.
>
> Each commit has a self-contained change, they should be fairly easy to review.
> Some small refactoring on legacy package (part 2)

- .github/workflows/arduino-stats.yaml
- .github/workflows/github-stats.yaml
- .github/workflows/i18n-nightly-push.yaml
- .github/workflows/i18n-weekly-pull.yaml
- .github/workflows/link-validation.yaml
- .github/workflows/nightly.yaml
- .github/workflows/publish-docs.yaml
- .github/workflows/python-lint.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yaml
- .github/workflows/test.yaml
- .github/workflows/validate-docs.yaml
- .github/workflows/verify-formatting.yaml
> Bump actions version

- cli/config/add.go
- cli/config/config.go
- cli/config/delete.go
- cli/config/init.go
- cli/config/remove.go
- cli/config/set.go
- cli/config/validate.go
- test/test_config.py
New feature!
To change your config file you must edit it manually.
There are 4 new sub command to `config`:
* `add` to add one or more values to a setting key that contains a list
* `remove` to remove one or more values from a existing key that contains a list
* `set` to change the value of a setting key
* `delete` to delete a key and all its sub keys
All these commands accept only the CLI config values, you can't set your own settings with these. …
> Add new commands to edit config files

- docs/configuration.md
Docs update.
The  `library.enable_unsafe_install` configuration key is undocumented.
The  `library.enable_unsafe_install` configuration key is documented in the configuration documentation page.
No
Reference: https://github.com/arduino/arduino-cli/pull/1075
> [skip changelog] Document `library.enable_unsafe_install` configuration key

- cli/lib/install.go
- test/test_lib.py
Better feedback for the user.
Using `--git-url` or `--zip-file` flags with `lib install` command doesn't give great feedback to the user.
Using `--git-url` or `--zip-file` flags now tells the user to visit the documentation for more information.
No.
None.
---
> Update warning message for --git-url and --zip-file lib install flags

- cli/feedback/feedback.go
- test/test_board.py
Fixes all commands output.
JSON output doesn't print a newline at the end.
JSON output prints a newline at the end.
No.
None.
---
> Fix JSON output not printing newline

- arduino/cores/packageindex/index.go
- cli/cli.go
- cli/config/validate.go
- commands/daemon/testdata/arduino-cli.yml
- commands/instances.go
- configuration/configuration.go
- configuration/configuration_test.go
- configuration/defaults.go
- docs/configuration.md
- docs/getting-started.md
It introduces a new flag `additional-paths` that allows to provide package indexes from absolute file paths. In this case, the signature will not be checked. This can be useful for third party cores, since they will not be requested to upload their package indexes to a server. However it can also be useful for Arduino internal usage during testing phases.
Package indexes can be downloaded only from URL. In case of Arduino cores, the signature is always checked and if a valid signature is not found, the core installation fails. …
> Provide package indexes from file paths using "additional-paths" flag

- .goreleaser.yml
- Taskfile.yml
- version/version.go
Enhanced an existing command.
`version` command doesn't print datetime of the build in use.
`version` command prints datetime of the build in use if set. 
`ldflags` are used to set build datetime with `-X github.com/arduino/arduino-cli/version.date`.
No.
None.
---
> Add build datetime to version command output

- arduino/utils/url.go
- arduino/utils/url_test.go
- cli/cli.go
- cli/config/validate.go
- commands/daemon/testdata/arduino-cli.yml
- commands/instances.go
- configuration/configuration.go
- configuration/configuration_test.go
- configuration/defaults.go
- docs/configuration.md
- docs/getting-started.md
- test/test_core.py
Changes an unreleased feature.
User can set `board_manager.additional_paths` to set paths to local indexes.
User must now set `board_manager.additional_urls` with the `file://` schema to set paths to local indexes.
No.
Solves #664.
---
> Add support for file:// schema to set local additional URLs

- docs/UPGRADING.md
Docs update.
Not applicable.
Updated the `docs/UPGRADING.md` file with instructions on how to handle certain breaking changes.
No.
None.
---
> [skip changelog] Update UPGRADING.md with new breaking changes

- arduino/sketches/sketches.go
- arduino/sketches/sketches_test.go
- commands/debug/debug_info.go
- commands/debug/debug_test.go
- test/test_debug.py
Fixes an existing feature.
`debug` command doesn't work if binaries are not exported to sketch folder.
`debug` command works correctly even if binaries are not exported to sketch folder.
No.
Fixes #1102.
---
> Fix debug command not finding sketch build folder

- arduino/cores/tools.go
- arduino/cores/tools_test.go
This PR adds support for installing native tools for:
- `windows,amd64`
- `darwin,arm64`
it also adds compatibility fallback for:
- `windows,amd64` if not available will try to fallback to `windows,386`
- `darwin,arm64` if not available will try to fallback to `darwin,amd64` and, if still missing, with `darwin,386`
> Extended support for various OS / CPU

- arduino/cores/cores.go
- arduino/cores/packageindex/index.go
- arduino/cores/packagemanager/loader.go
- commands/bundled_tools_serial_discovery.go
- commands/instances.go
Just cosmetic fixes, no behavioral changes.
> [skip-changelog] Small cosmetic fix

- docs/FAQ.md
Docs update.
Despite the Arduino Nano being the sole active official Arduino board without a custom VID/PID, it is not mentioned in the FAQ item about this type of board.
The classic Nano is explicitely mentioned in the FAQ item and the wording is slightly improved.
No
Related:
- https://github.com/arduino/arduino-cli/issues/986 …
> [skip changelog] Improve wording of FAQ re: boards w/o dedicated VID/PID

- table/table.go
This patch will not allow the column width to be less than the headers.
Fix #1040
> Fixed odd column width of tables in command outputs

- commands/upload/upload.go
For example if we have bossac 1.7.1 and 1.9.0 installed, this will result in the following properties available during upload:
`{runtime.tools.bossac-1.7.0-arduino3.path} => /path/to/bossac/1.7.0`
`{runtime.tools.bossac-1.9.0-arduino3.path} => /path/to/bossac/1.9.0`
`{runtime.tools.bossac.path} => /path/to/bossac/1.9.0`
some platforms fail to correctly specify the version of the tool in the package_index.json but they do the correct specification in the recipes. This patch allows to not fail in this latter case.
> Always set the versioned runtime.tool property for all installed tools

- docs/UPGRADING.md
Adds a missed breaking change introduced before the breaking changes policy.
After merge I'll cherry pick this commit to `0.14.x` branch to update the documentation.
Fixes #1109.
> [skip changelog] Add missing breaking change in UPGRADING.md

- cli/config/validate.go
- cli/daemon/daemon.go
- commands/compile/compile.go
- configuration/configuration_test.go
- configuration/defaults.go
- docs/UPGRADING.md
- docs/configuration.md
- docs/getting-started.md
- metrics/metrics.go
- test/test_config.py
- test/test_daemon.py
Changes all occurences of the term `telemetry` to `metrics`.
No behaviour changed.
Same as before.
Yes, the `UPGRADING.md` file has been updated accordingly.
None.
---
> [breaking] Rename telemetry to metrics

- cli/cli.go
- inventory/inventory.go
Enhances error messages.
If there are invalid paths for certain settings in the config file multiple errors are returned but are not clear enough, also certain commands still keep going forward.
Full invalid paths in the config file are now printed in full and only one error is shown, execution also stops for all commands if an error is returned.
No …
> Enhance error messages if config paths are not valid

- .github/workflows/github-stats.yaml
Fixes an outdated API request in a workflow.
Workflow fails.
Hopefully it doesn't fail anymore.
Nope.
None.
---
> [skip changelog] Fix workflow collecting GH download stats

- mkdocs.yml
docs update
The name of [the specification is "package_index.json specification"](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/). Only the primary official package index
is allowed to be named package_index.json, but this specification applies to all package indexes. So the current naming might cause confusion. It also doesn't roll off the toungue so well when speaking about this topic.
The specification is renamed to "Arduino package index specification" (shortened …
> [skip changelog] Use generally applicable name for package index specification

- docs/library-specification.md
docs update
Previously, the Arduino library specification required the library.properties `name` field value to start with a letter.
Before Arduino IDE 1.8.4, library folder names starting with a number were not supported (https://github.com/arduino/Arduino/commit/4545283ae773b6351d089e37b6d4080905ea8fd5). Because the library folder for
Library Manager installations is named according to the library.properties name value, it was necessary to apply the
same restriction to the name value.
It was …
> [skip changelog] Allow library names to start with a number

- cli/cache/clean.go
The terms "cache" and "clean" might bring compilation to mind, but the `arduino-cli cache clean` command has nothing to
do with compilation. Many users will likely not even be aware of the existence or purpose of the `directories.downloads`
folder. For this reason, it's important to make the purpose of this command clear.
docs update
The terms "cache" and "clean" might bring compilation to mind, but the `arduino-cli cache clean` command has nothing to
do with compilation. Many users will likely not even be aware of the …
> [skip changelog] Make the command documentation of cache clean more clear

- legacy/builder/phases/linker.go
- test/test_compile.py
Fixes https://github.com/arduino-libraries/ArduinoIoTCloud/runs/1693000682?check_suite_focus=true#step:7:277
Once merged https://github.com/arduino-libraries/ArduinoIoTCloud/pull/222 can be reverted
@ubidefeo @per1234 @cmaglie 
This patch fixes a corner case when the commandline is too long and the "archiver" kicks in.
Since archiving an archive is not really supported, we leave it as-is and just append to the list of existing archives to be linked
Compilation on ArduinoIoTCloud + ESP8266/ESP32 fails due to the huge amount of …
> Don't archive preexisting archives if commandline is too long

- go.mod
- go.sum
Previously overwriting a file will not truncate it, so if the download size was less than the file size already on disk then the resulting file will end up with a "corrupted" piece at the end.
> Updated go-downloader to v2.1.1

- legacy/builder/phases/libraries_builder.go
- test/test_compile.py
If a folder meant to contain precompiled libraries is empty (or only contains other folders) it can be safely skipped
The folder is not skipped, so libraries with `src/$architecture/$fp_specs` will try to use `src/$architecture/` as precompiled base folder, even if it doesn't contain any library
The folder is skipped and the library can be compiled from sources
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#break …
> Precompiled libraries: only select a folder if it contains files

- arduino/libraries/librariesmanager/install.go
- cli/lib/install.go
- poetry.lock
- pyproject.toml
- test/test_lib.py
Fixes a bug with an existing command.
Calling `arduino-cli lib install --git-url .` is executed successfully but the library is installed in the wrong folder, to be precise it's installed directly inside the `<sketch_book_dir>/libraries` folder, so the whole content of the library ends there.
Calling `arduino-cli lib install --git-url .` now correctly deduces the library name from the given path and installs it in the `<sketch_book_dir>/libraries/<lib_name>` folder.
- **Does this PR introduce a …
> Fix lib install with git url

- arduino/libraries/librariesmanager/install.go
- test/test_lib.py
Enhances the behaviour of `lib install` when using the `--git-url` or `--zip-file` flags.
Previously installing from a zip file would extract the content directly into the user library folder, this could have caused problem if the zip file wasn't structured correctly.
Installing from a git repository would clone the repo directly to the user library folder and leave it as it is. Also it would fail if the library is already installed and would not reinstall it.
When using the `--zip-file` flag we now extract to a temp directory to verify that the zip is structured correctly and to infer the name of …
> Enhance lib install from git url and zip file

- cli/lib/install.go
- test/test_lib.py
Enhances an existing command.
When calling `lib install` with the `--git-url` or `--zip-path` flags only one library at a time can be installed, subsequent arguments are ignored.
```
arduino-cli lib install --git-url https://github.com/arduino-libraries/WiFi101.git https://github.com/arduino-libraries/ArduinoBLE.git
arduino-cli lib install --zip-path /path/to/ArduinoBLE.zip /path/to/WiFi101.zip
```
Calling `lib install` with `--git-url` or `--zip-path` flags will install all libraries specified. …
> Add multiple libraries installation when using --git-url or --zip-path flags

- arduino/libraries/libraries.go
- commands/compile/compile.go
- commands/lib/list.go
- test/test_lib.py
Fixes a regression when calling `lib list`.
`lib list --all --fqbn arduino:avr:uno --format json` doesn't return the `provides_includes` property for the libraries installed together with the specified core, `arduino:avr` in this case.
If the `includes` property found in the `library.properties` file is empty we would return nothing.
`lib list --all --fqbn arduino:avr:uno --format json` now correctly return `provides_includes` property for all libraries.
Now if the `includes` property in the `library.properties` file is empty we walk the library's folders to gather the headers file names.
- **Does …
> Fix lib list --all not returning library includes in json output

- .github/workflows/test.yaml
Changes the environment used for testing in workflows from `ubuntu-latest` to `ubuntu-20.04`.
Integration tests are failing when running on `ubuntu-latest`/ `ubuntu-18.04`.
Integrations tests are now running successfully.
No.
None.
---
> [skip changelog] Upgrade workflow ubuntu env

- arduino/builder/compilation_database.go
- commands/compile/compile.go
* BuildPath field in `compile` json output is always populated, even if the build is not successful.
* `compile_commands.json` now always contains a json array, even if the Contents field array is empty. (before `null` was written in the file)
> Always output build path in compile json-output / Always write a valid compilation database

- arduino/libraries/librariesmanager/install.go
- test/test_lib.py
Fixes a bug when installing libraries.
`lib install --zip-path` doesn't keep a library folder structure when installing it.
`lib install --zip-path` now keeps the library folder structure when installing.
No.
Fixes #1150.
---
> Fix lib install --zip-path not preserving folders structure

- arduino/globals/globals.go
- arduino/libraries/loader.go
- arduino/sketches/sketches.go
- arduino/sketches/sketches_test.go
- arduino/sketches/testdata/SketchMultipleMainFiles/SketchMultipleMainFiles.ino
- arduino/sketches/testdata/SketchMultipleMainFiles/SketchMultipleMainFiles.pde
- arduino/sketches/testdata/SketchPde/SketchPde.pde
- cli/compile/compile.go
- cli/sketch/archive.go
- cli/upload/upload.go
- commands/sketch/archive.go
- commands/upload/upload.go
- docs/sketch-specification.md
- test/test_compile.py
- test/test_debug.py
- test/test_lib.py
- test/test_sketch.py
- test/test_upload.py
- test/testdata/sketch_multiple_main_files/sketch_multiple_main_files.ino
- test/testdata/sketch_multiple_main_files/sketch_multiple_main_files.pde
- test/testdata/sketch_pde_main_file/sketch_pde_main_file.pde
This PR brings back the support for sketches ending with `.pde` extension. 
Also we deprecate it.
Trying to `compile`, `upload`, or `archive` a sketch with a `.pde` main file always fails.
Also examples' libraries with `.pde` extensions are not shown when calling `lib examples`.
`compile`, `upload`, or `archive` a sketch with a `.pde` main file now works correctly and shows a warning message recommending the user to rename all `.pde` files `.ino`.
Examples' libraries with `.pde` extensions are now correctly shown when calling `lib examples`. …
> Add back support for sketches with .pde extension and deprecate it

- Taskfile.yml
The current release process uses git to get the tag at the current
commit. It might happen that are are multiple tags when calling that
command, in cases the rc and the final release are done on the same
commit, that would make the build process to fail.
This fixes that issue by taking only one tag.
> [skip changelog] Fix release process

- client_example/README.md
- client_example/main.go
- client_example/squid.conf
Adds some examples to the `client_example` project used to "test" gRPC comunication.
---
> [skip changelog] Update client_example with proxy testing

- client_example/main.go
- commands/daemon/settings.go
- commands/daemon/settings_test.go
Bug fix.
Calling the gRPC interface Merge function to merge existing configs with new ones would ignored empty values.
This fix adds the possibility to set empty values with the Merge gRPC function, previously they would have been ignored.
Because of this change I had also to modify the GetValue() function since it would first check if the value was set using the Viper.InConfig() function that wouldn't check for values set with Viper.Set().
- **Does this PR introduce a breaking change, and is [titled …
> Fix gRPC interface function to merge configs

- cli/core/list.go
- cli/core/search.go
- cli/core/upgrade.go
- commands/core/list.go
- commands/core/search.go
- commands/core/search_test.go
- commands/daemon/daemon.go
Refactors some commands internals.
`cli/core` commands are currently calling `commands/core` function without using `rpc` Requests structs.
All `cli/core` commands now call `commands/core` functions using the `rpc` Requests structs.
Nope.
We don't fix any issue with this PR but we'll avoid breaking the CLI and the gRPC interface alignment.
This adds more output to `core list --format json` but it doesn't break anything.
This …
> [skip changelog] Fix core commands skipping gRPC interface

- test/conftest.py
Fixes integration tests failing on CI.
Folders used by integration tests are not deleted, this causes disk space filling up in the CI and make it fail.
Folders are now deleted when they reach the end of their scope. This way the disk space won't fill up and the CI won't fail.
Nope.
I actually thought that this was already done …
> [skip changelog] Fix integration tests not deleting folders when test finishes

- commands/compile/compile.go
- test/test_compile.py
Otherwise an empty `build/fqbn/...` folder is created if `always-export-binaries` option is set via config file.
> Do not try to export binaries if --only-compilation-database is set

- commands/upload/upload.go
Before:
```
$ arduino-cli upload -b arduino:avr:gemma -p /dev/ttyACM0
avrdude: invalid baud rate specified '{upload.speed}'
Error during Upload: uploading error: uploading error: exit status 1
$
```
After:
```
$ arduino-cli upload -b arduino:avr:gemma -p /dev/ttyACM0
Error during Upload: a programmer is required to upload for this board
$
```
> Better error message for boards without bootloader

- .github/workflows/release.yaml
Updates a workflow action.
`create-changelog` action has a bug that causes the whole `git log` to be used as changelog.
New version of `create-changelog` action generate the changelog correctly from current to past tag.
Nope.
None.
---
> [skip changelog] Update create-changelog action in release workflow

- arduino/sketch/sketch.go
- arduino/sketch/sketch_test.go
- legacy/builder/container_setup.go
- legacy/builder/types/context.go
This is required to ensure backward compatibility for `arduino-builder` that doesn't enforce this check.
In particular, since `arduino-builder` is used in the Arduino IDE, if the user tries to compile an unsaved sketch, the Arduino IDE will create a temporary copy of the sketch in a temp dir with a random name: in this case if the folder name check is enabled the compile will fail.
This flag is for internal use only (basically only on `arduino-builder`) it will be removed once `arduino-builder` will be completely replaced by `arduino-cli` in the Arduino IDE.
> Added flag to disable check for sketch foldername matching sketch name

- arduino/libraries/librariesindex/index.go
- arduino/libraries/librariesindex/index_test.go
- arduino/libraries/librariesmanager/install.go
- test/test_lib.py
- test/test_outdated.py
- test/test_update.py
- test/test_upgrade.py
Fixes a bug that caused several commands to crash.
Some commands crash with a `nil` pointer dereference when an installed library has an invalid or empty version in its `library.properties` file.
Installed libraries with invalid or empty version in `library.properties` file won't cause those commands to crash with a `nil` pointer deference. Also if a library version can't be determined we assume it's outdated.
No breaking changes here.
* **Other …
> Fix some commands crashing when an installed library has invalid version

- arduino/resources/checksums.go
- arduino/resources/helpers.go
- arduino/resources/resources_test.go
User experience improvement
Trying to install packages with `core install <fqdn>` is not helpful when:
- Index file has incorrect size for a package file
- Index file has no checksum for a package file
This PR improves the errors printed when the package file contains incorrect values
no
Tested with index file …
> Make archive validation error messages friendlier

- docs/library-specification.md
- docs/sketch-specification.md
docs update
The library and sketch specifications say that spaces are allowed in library and sketch folder names, but this is not supported by the Arduino IDE. Use of spaces in the folder name will result in a warning on IDE startup and the project not being recognized.
The previous mention of spaces as one of the characters allowed in library and sketch folder names was a copy/paste
error originating in the allowed characters in library.properties `name` properties. This specific part of the `name`
property specification …
> [skip changelog] Correct library+sketch specifications re: spaces in folder name

- README.md
- docs/index.md
docs update
The introductory sentence of the documentation homepage is the first thing the user may see when discovering Arduino
CLI. For this reason, it's important for it to quickly and clearly convey what Arduino CLI is. It's possible the current wording could be improved to do a better job of this.
The wording of the sentence is improved via the following changes:
- Use more understandable terms
- Rearrange features list in the order of typical usage (install dependencies, compile, upload)
- …
> [skip changelog] Improve wording of docs introduction

- docs/platform-specification.md
docs update
Since the time the documentation for the initial experimental debugging configuration system was added to the Arduino
Platform Specification (https://github.com/arduino/arduino-cli/pull/882), the system has changed significantly, resulting in some of the documentation no longer being applicable to the current version of Arduino CLI.
The outdated information is removed, leaving the parts that are still correct.
Since the documentation is versioned, users of older Arduino CLI versions …
> [skip changelog] Remove outdated information re: debug system from platform spec

- test/test_core.py
Fixes failing tests.
Tests are failing because the number of cores in the index is changed.
Tests won't fail anymore since the expected number of cores is not a fixed number.
Nope.
None.
---
> [skip changelog] Fix core integration tests

- commands/bundled_tools_serial_discovery.go
This updates the tool to v1.2.1, changelog:
* added support for macosx big-sur
* fixed wrong USB serial number detection in Windows for USB composite devices
> Update serial discovery

- go.mod
- go.sum
- legacy/builder/merge_sketch_with_bootloader.go
Since https://github.com/marcinbor85/gohex/pull/2 has been merged there is no more reason to keep the fork.
\o/ \o/
> Drop gohex fork and use upstream library again

- docs/configuration.md
docs update
The existence and meaning of the `sketch.always_export_binaries` configuration key (https://github.com/arduino/arduino-cli/pull/1042) is undocumented.
The `sketch.always_export_binaries` configuration key is documented in the Arduino CLI Configuration page of the documentation website:
https://arduino.github.io/arduino-cli/dev/configuration/ …
> [skip changelog] Document `sketch.always_export_binaries` configuration key

- commands/core/install.go
User experience improvement
Trying to install packages with `core install <fqdn>` is not helpful when downloading of the core file fails
Download errors are displayed to the user
no
---
> Bubble platform download error

- commands/core/install.go
- commands/core/uninstall.go
- commands/core/upgrade.go
- commands/instances.go
- test/test_core.py
- test/test_upgrade.py
Fixes an existing command.
`core install`, `core upgrade` and `upgrade` commands don't remove necessary tools used by the previously installed core version but unused by the newly installed one.
`core install`, `core upgrade` and `upgrade` commands now remove unused tools if the core that is being upgraded doesn't need them in the new version.
Nope.
* …
> Fix core upgrading not uninstalling unused tools

- arduino/builder/sketch.go
Improves error messages.
This is the patch from @oschonrock #707 rebased on `master`.
> Add #line tags to AdditionalFiles when copying to build directory

- .dependabot/config.yml
- .github/workflows/stale.yaml
Bug fix.
The Arduino Tooling repositories now use a "category: name" format for all repository labels. Dependabot and the
"stale-bot" workflow use label names that do not comply with the new format ("component/dependencies" and "stale").
The Dependabot and "stale-bot" configurations are updated to use the standardized label name format.
>Does this PR …
> [skip changelog] Update automation configs to use new label format

- .github/workflows/stale.yaml
Bug fix
The "waiting for feedback" label was renamed "status: waiting for information" to comply with the standardized tooling
label system, but this label name was missed when updating the workflow to reflect the change (https://github.com/arduino/arduino-cli/pull/1213).
The correct issue label is used to enable the stale bot.
No breaking change.
* …
> [skip changelog] Update "stale bot" GHA workflow to use new enabling label

- arduino/cores/packagemanager/loader.go
- test/test_core.py
Fixes a bug when loading installed cores.
`core list` doesn't return a core's name if that core folder doesn't contain an `installed.json` file and has been installed via CLI. Manually installed cores have their name correctly shown.
This also affects the gRPC interface.
`core list` now returns all cores' names even if `installed.json` file is not found. This also fixes the gRPC interface.
[titled …
> Fix core name not showing if installed.json is not found

- arduino/builder/sketch.go
- arduino/globals/globals.go
- arduino/sketch/sketch.go
- legacy/builder/builder.go
- legacy/builder/create_cmake_rule.go
Fixes a bug with sketch files parsing.
Both `.s` and `.S` extensions are accepted as Sketch assembly files.
Now only `.S` extensions are accepted as Sketch files.
Nope.
This will also enforce lowercase for other files extensions.
---
> Fix casing of assembly sketch files

- arduino/builder/sketch_test.go
- arduino/globals/globals.go
- arduino/sketch/sketch_test.go
Enhances gRPC interface.
`LoadSketch` gRPC interface function doesn't return Sketch files in the root folder that have `.json`, `.adoc` or `.md` extension.
`LoadSketch` gRPC interface function now returns Sketch files in the root folder that have `.json`, `.adoc` or `.md` extension.
This only affects the gRPC interface.
Nope. …
> Add support for json, adoc and md sketch files extensions

- cli/core/search.go
- test/test_core.py
Changes an existing command.
Calling `core search` always updates the indexes.
Calling `core search` now only updates indexes if one or more of them are older than 24 hours. 
It's still possible to force an update by calling `core update-index` or `update`.
Nope.
None.
---
See [how to …
> Change `core search` to update indexes only after 24h from last edit

- commands/upload/upload.go
There are some particular boards where the serial port is required only to switch the board in bootloader mode but the actual upload is performed in other ways.
This patch allows to upload when the board is already in bootloader mode, otherwise, the cli will exit with the error:
```
no upload port provided
```
Previously the CLI would exit with an error anyway, so this change should not make any harm to other boards.
> upload: do not give up if no port is specified for 1200 bps touch

- cli/feedback/feedback.go
A small enhancement for future work.
`feedback.Errorf` doesn't unwrap gRPC status errors.
`feedback.Errorf` now unwraps gRPC status errors.
Nope.
Relates to #1251 .
---
> [skip changelog] Add gRPC status unwrapping in error feedback

- arduino/serialutils/serialutils.go
- commands/upload/upload.go
> Experimental: optimized touch + wait

- arduino/libraries/librariesresolver/cpp.go
- arduino/libraries/librariesresolver/cpp_test.go
- test/test_compile.py
- test/testdata/sketch_with_conflicting_libraries_include/sketch_with_conflicting_libraries_include.ino
A library may be stored in a directory that doesn't match the library name, for example we had a case in the wild where the directories:
```
libraries/onewire_2_3_4/...
libraries/onewireng_1_2_3/...
```
were used instead of:
```
libraries/OneWire/...
libraries/OneWireNg/...
```
this lead to an incorrect selection of `onewireng_1_2_3` when using `OneWire.h` (because `OneWireNg` had an `architecture=avr` that had priority over the `architecture=*` of `onewire_2_3_4`).
This commit will restore priority straight.
> Improved lib detection: check for matching name in library.properties 

- commands/board/list.go
- commands/core/list.go
- commands/core/search.go
- test/test_core.py
Fixes an existing feature.
The `core list`, `core search` and `board list` commands return results sorted in alphabetical order but taking into account capitalized platform names and boards FQBNs.
For example:
```
$ arduino-cli core search
ID                    Version   Name                                                                    
arduino:avr           1.8.3     Arduino AVR Boards                                                                                    
arduino:sam           1.6.12    Arduino SAM Boards …
```
> Fix sorting of platforms and boards

- docs/UPGRADING.md
- Fixed arduino-cli path for Windows specified in the v 0.15.0 changes in UPGRADING.md file
> Fix Arduino path on Windows in version notes

- .github/workflows/release.yaml
CI fix.
Creating a new tag for a Release Candidate creates a changelog with the whole git log tree.
Creating a new tag for a Release Candidate doesn't create a changelog with the whole git log tree anymore.
Nope.
None.
---
> [skip changelog] Fix tag regex for release changelog generation

- docs/sketch-specification.md
docs update
[The Arduino Sketch Specification](https://arduino.github.io/arduino-cli/latest/sketch-specification/#sketch-root-folder) only documents the requirements for sketch folder names. Since the primary sketch filename must match the folder name, this appears at a glance to be self-evident. However, sketches may consist of multiple code files, and so the specification was ambiguous regarding the naming requirements for additional files.
The specification documents that the same naming …
> [skip changelog] Document sketch filename requirements

- cli/config/validate.go
Fixes a bug.
Calling `arduino-cli config add network.proxy http://<login>:<password>@myproxy.ext:port` returns `Settings key doesn't exist` error.
Calling `arduino-cli config add network.proxy http://<login>:<password>@myproxy.ext:port` sets correctly the `network.proxy` value.
Nope.
Fixes #1273
---
See [how to …
> Fix `network` settings uneditable with config command

- arduino/libraries/librariesresolver/cpp.go
- arduino/libraries/librariesresolver/cpp_test.go
- test/test_compile.py
- test/testdata/sketch_with_conflicting_libraries_include/sketch_with_conflicting_libraries_include.ino
Reverts a fix that is causing unforeseen consequences.
Sketch compilation is broken for ESP32 boards when using a library that is installed both in the Sketchbook folder and the core folder. 
The reverted commit changed the way libraries are resolved so that the name set in the `library.properties` is checked to understand which library to included; the libraries included in the ESP32 core have a different name in `library.properties` because of legacy reasons from the Java IDE.
Compiling a Sketch that includes `OneWire.h` with …
> Revert "Improved lib detection: check for matching name in library.properties (#1276)"
