commands/upload/upload.go
No functional modification for standard flow (compile+upload without -i flag)
=> Don't bail out if trying to upload external binary

README.md
=> Point build status to Travis

cli/core/install.go
Resolves issue #205 that was originally submitted from pull request #206 but needed to be redone as suggested by @masci
=> Fixing documentation issue with core install command

cli/cli_test.go
Latest version switched to using fancy urls in imports
=> Use fancy url for monkey

README.md
Fixes https://github.com/arduino/arduino-cli/issues/260
Also reported at https://github.com/arduino/arduino-cli/issues/258
=> Fix download link for Mac OSX

go.mod, go.sum
Some users are reporting problems while `go get -u`-ing the project, this won't help in all cases but it's still good to consolidate the mod status.
=> Tidy go mods

.dependabot/config.yml
Let the bot use the right label
=> Change label name used by dependabot

test/.flake8, test/README.md, test/common.py, test/conftest.py, test/requirements.txt, test/test_board.py, test/test_lib.py, test/test_main.py
Rearrange integration tests so they run in isolation and can be executed one at a time.
Also provide a test for https://github.com/arduino/arduino-cli/pull/315
=> Make tests independent from each other

.editorconfig
=> [skip ci] add editorconfig file

README.md
=> [skip changelog] Add Appveyor badge to the readme

.drone.yml, .goreleaser.yml
=> add nightly pipeline

.github/ISSUE_TEMPLATE/bug_report.md
Minor improvement on the issue template
=> [skip changelog] ask for the full command line

README.md
Sample README here: https://github.com/cmaglie/arduino-cli/tree/code-cov-badge
=> Add code-cov badge to README

legacy/builder/resolve_library.go
This increase backward compatibility with arduino_builder
=> Output library resolution details only on verbose build

legacy/builder/phases/core_builder.go
=> Check if variantFolder exists and is a folder

.gitignore
Please merge if you find this useful. Otherwise, close. Thanks!
=> [skip changelog] Added .DS_Store to the .gitignore.

.github/workflows/nightly.yaml
=> [skip changelog] Strip dist from upload prefix from nightly build s3 upload step

.github/workflows/test.yaml
add missing condition to skip codecov jobs on workflows from forks
=> [skip changelog] fix codecov job

.codecov.yml, .github/workflows/test.yaml, Taskfile.yml
Since we run legacy tests, let's make them contribute to the overall coverage.
=> [skip changelog] Add coverage for legacy tests

.github/workflows/stale.yaml
=> Use the right variable

go.mod, go.sum
* updated go-paths to fix a bug in arduino-builder
* using tagged versions for go-paths
* added appengine (this is continuosly popping up on my local go.mod, so let's commit it)
=> Updated some dependencies

cli/core/download.go, cli/core/install.go, cli/core/upgrade.go, cli/globals/globals.go, cli/instance/instance.go, cli/lib/download.go, cli/lib/install.go, cli/lib/upgrade.go, commands/board/list.go
=> Removed globals.HTTPClientHeader global

README.md
Addressing https://github.com/arduino/arduino-cli/issues/275 feature request, 
I am finally very proud to contribute my part to your awesome project
In the recent days I opened a pr to homebrew for arduino-cli 0.5.0 new formula: https://github.com/Homebrew/homebrew-core/pull/44948 (the pr is closed but it was actually merged a few minutes ago)
Cheers!
Efrat
=> install arduino-cli via homebrew

README.md
=> [skip ci] [skip changelog] Add contributors reference in README.md

commands/lib/install.go
=> [skip changelog] Typo fix

README.md
Also add a dedicated badge to show nightlies status
=> [ci skip] fix README badges

CONTRIBUTING.md
Also reformat markdown contents
=> Mention style check in contributing guidelines

CONTRIBUTING.md, Taskfile.yml
This also adds some documentation showing how this works.
=> Allow running specific unit tests

.goreleaser.yml
=> [skip changelog] Do not ship readme with packages

legacy/builder/i18n/i18n.go
Fix #493
Fix https://github.com/arduino/Arduino/issues/9287
=> Fixed wrong escaping on legacy MachineLogger

.github/workflows/docs.yaml, README.md
* Fix wrong or missing links on the README
* Fix the GH workflow that keeps skipping docs publishing
=> [skip changelog] Fix README links

.github/workflows/arduino-stats.yaml
Fixed schedule rule for `arduino-stats.yaml` pipeline
Changed name to workflow into `arduino-stats` for consistency
---
=> [skip changelog] [skip ci] Fix cron configuration

rpc/commands/board.pb.go, rpc/commands/board.proto, rpc/commands/commands.pb.go, rpc/commands/commands.proto
Add explanatory comments for the board components of the gRPC interface to the source code. These comments will be included in the [generated gRPC interface documentation](https://arduino.github.io/arduino-cli/rpc/settings/).
No
=> [skip changelog] Add documentation for board components of the gRPC interface

.github/workflows/docs.yaml, docs/build.py
Remove leftover dependency
no changes to the CLI
---
=> Remove unused import

docs/build.py
=> [skip-changelog] Fix subprocess invocation

README.md
Adding the Security Policy link and the Security Team contact in the README file.
=> Adding Security Policy link

docs/installation.md
Fixes broken link in the documentation.
=> [skip changelog] Fix broken link to CONTRIBUTING docs

test/requirements.txt, test/test_daemon.py
This PR fixes the flaky daemon telemetry test
=> [skip changelog] Add retry to telemetry daemon test

arduino/cores/tools.go, commands/upload/upload.go
Previously the app crashed.
See https://github.com/arduino/arduino-cli/issues/755
=> Print a friendly message if a tool is not available

docs/FAQ.md
Docs update.
The documentation doesn't provide guidance for Arduino CLI users who need additional assistance.
The FAQ page of the documentation directs users to the Arduino CLI board of the Arduino forum for support requests.
No.
=> [skip changelog] Add forum link to FAQ

.github/workflows/python-lint.yaml
Fix the badly formatted Python linting workflow again.
=> [skip changelog]  Fix Python lint workflow formatting again

.github/workflows/test.yaml
Test workflow now is not run if only documentation files are modified in a PR or in a commit.
---
=> [skip changelog] Avoid running CI tests if only docs are modified

docs/CONTRIBUTING.md
Fixed missing links in documentation.
---
=> [skip changelog] Fix missing links in documentation

cli/upload/upload.go
This is dead-code, leftover from previous experiments.
=> Removed leftover from legacy --burn-bootloader flag

cli/config/init.go, commands/daemon/settings_test.go, configuration/configuration.go, configuration/configuration_test.go, main.go, test/test_config.py
Reverts arduino/arduino-cli#957 due to #1018
=> Revert "Change behaviour of --config-file flag with config commands"

commands/bundled_tools_serial_discovery.go
This fixes an issue on MacOSX wrt continuous port monitoring.
=> Update serial_discovery to v1.1.0

go.sum, test/test_sketch.py
Fixes sketch tests.
Certain sketch tests fail on Window and are skipped when on CI.
Sketch tests are all run on CI and Windows.
No
None.
---
=> [skip changelog] Fix sketch tests on Windows

legacy/builder/test/hardware_loader_test.go
Fixes tests.
Some legacy tests are failing, this is probably caused by a parallelization issues.
They should run smoothly and with no issues now.
Nope.
None.
---
=> [skip changelog] Fix failing legacy testing

commands/daemon/term_example/main.go
Required changes after merging #1223
=> Fixed term grpc example

test/test_core.py
Fixes broken tests.
Nope.
None.
---
=> [skip changelog] Fix core search integration test

.github/workflows/publish-docs.yaml
Fixes a workflow.
`publish-docs` fails.
`publish-docs` doesn't fail anymore. Hopefully.
Nope.
None.
---
=> [skip changelog] Fix publish docs workflow

commands/bundled_tools_ctags.go, commands/bundled_tools_serial_discovery.go, commands/instances.go
Also fixed a bug that prevented tools-reload after auto-install in some rare circumstances (almost impossible to trigger actually).
=> Refactored bundle tool initialization

DistTasks.yml
- moved vars section to top https://taskfile.dev/#/styleguide?id=use-the-correct-order-of-keywords
- removed wrapping spaces in variables https://taskfile.dev/#/styleguide?id=dont-wrap-vars-in-spaces-when-templating
=> Applied taskfile lint rules to DistTask.yml

test/test_upload_mock.py
Adds integration tests to avoid regressions.
N/A
N/A
Nope.
Add integration test to avoid breaking behaviour fixed by #1312 and closes #1198.
---
=> Add test for runtime.os upload property

cli/daemon/interceptors.go
Simple improvement on daemon logging.
No
=> Slightly improved daemon gRPC logging

commands/bundle_tools_test.go, commands/bundled_tools_ctags.go
Added a test to check bundled tools availability, CRC and size metadata.
No
=> [skip changelog] Added tests to check for bundled tools availability

i18n/data/en.po
Updates the `en.po` translations base source file.
N/A
N/A
Nope.
None.
---
=> Update i18n en source file

.github/workflows/check-mkdocs-task.yml, .github/workflows/check-python-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, poetry.lock, pyproject.toml
Updates the Python version used in integration tests and some workflows.
We pinned the Python version used in different places to `3.9.6` to avoid a bug with a library introduced by a low level change in `3.9.7`.
New versions after `3.9.7` have been released that fix the bug, so we revert the changes from #1470 and #1478 to use the latest `3.9.x` available.
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking) …
=> Update Python version in integration tests

docs/library-specification.md
=> Fixed link in docs

docs/pluggable-discovery-specification.md
Fixed error in pluggable discovery protocol specification
**Other information**:
Fix #1653
=> Fixed error in pluggable discovery spec

.github/label-configuration-files/labels.yml
new labels
Add new labels useful to better categorize issues.
nop
=> [skip-changelog] Update labels.yml

internal/integrationtest/testdata/installed.json
`installed.json` used in core tests is up to date.
No
=> [skip-changelog] Update `installed.json` file used in tests

internal/integrationtest/testdata/installed.json
=> Fixed integration test

.gitignore
Add `.vscode` folder to gitignore.
=> Added `.vscode` to gitignore

arduino/resources/install.go
Remove a comment in the codebase introduced after a refactoring. The suggested piece of code is no longer needed as we checksum is done when we extract the zip.
=> Remove no longer needed comment

.github/workflows/check-markdown-task.yml, .github/workflows/check-mkdocs-task.yml, .github/workflows/check-protobuf-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
=> [skip-changelog] bump setup-protoc to v3

internal/arduino/cores/packagemanager/package_manager.go, internal/arduino/discovery/discovery_client/main.go, internal/arduino/discovery/discoverymanager/discoverymanager.go
Just a small code refactoring.
=> Removed dep from `configuration` package in DiscoveryManager

README.md, docs/UPGRADING.md, docs/getting-started.md, docs/versioning.md
=> Preparing docs for `1.0.0` release

docs/library-specification.md
Fixes a link in the documentation.
=> Fixed link in docs.

internal/integrationtest/board/board_test.go
Fixed tests after a recent change from `http` to `https` in the package index.
=> Fixed URL http -> https in integration tests.

README.md, docs/FAQ.md
Removed direct links to gnu.org because the site is often down and it makes the link-check job fail.
=> Removed direct links to gnu.org because the site is often down

DistTasks.yml, debian/Dockerfile, debian/arduino-cli/DEBIAN/control, debian/arduino-cli/DEBIAN/copyright
Ship .deb packages for all supported linux archs
=> Build and distribuite deb packages

DistTasks.yml, go.mod
=> [skip changelog] Update golang to 1.24.4
