arduino/arduino-cli

arduino/libraries/loader.go
go.mod
go.sum
test/conftest.py
test/test_compile.py

Fixes issues with testing on Windows.
The Workflow runners use 8.3 style naming convention for paths on Windows, see an example below.
Libraries install directory path is saved using the 8.3 style, this causes problems when trying to verify that a certain path is returned in the output of certain commands on Windows.
```
C:\\Users\\RUNNER~1\\AppData\\Local
C:\\Users\\runneradmin\\AppData\\Local
```
All libraries install directory paths are canonicalized so the 8.3 style path is not printed on …

[skip changelog] Libraries install dir path is now canonical

---

test/test_compile.py
test/testdata/sketch_with_sd_library/sketch_with_sd_library.ino

Adds some integrations tests.
N/A
N/A
Nope.
These is related to #1290.
---

[skip changelog] Add integration tests to avoid breaking compilation for esp cores

---

.github/workflows/i18n-nightly-push.yaml
.github/workflows/i18n-weekly-pull.yaml
.github/workflows/link-validation.yaml
.github/workflows/nightly.yaml
.github/workflows/publish-docs.yaml
.github/workflows/python-lint.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.github/workflows/validate-docs.yaml
.github/workflows/verify-formatting.yaml

enhancement
An unmaintained, deprecated, and outdated version of the action used to install Task is in use in the CI/CD workflows.
-  **What is the new behavior?**
The GitHub Actions action for installing [Task](https://taskfile.dev/#/) has graduated from its original home in [the experimental `arduino/action`repository](https://github.com/arduino/actions) with a move to a dedicated permanent repository at [`arduino/setup-task`](https://github.com/arduino/setup-task).
A [1.0.0 release](https://github.com/arduino/setup-task/releases/tag/v1.0.0) has been made and [a `v1` ref](https://github.com/arduino/setup-task/tree/v1) that will …

[skip changelog] Use new arduino/setup-task action name in CI/CD workflows

---

install.sh

Fixes an issue where during installation using wget an
uninitialized variable was read which caused the process to
get stuck.
Bug fix
When installing using wget the process gets stuck because output is redirected
incorrectly and an initialized variable is read.
Installation using wget now works properly.
Does not introduce a breaking change.
* **Other …

Fixes installation using wget

---

.github/workflows/arduino-stats.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml

Bug fix
Unquoted variables in shell commands can result in very confusing bugs caused by unexpected interpretation of characters
in the variable contents by the shell, such as [globbing and word splitting](https://github.com/koalaman/shellcheck/wiki/SC2086).
The immediate motivation for this change is that the unquoted certificate password for the macOS notarization [guaranteed someone a headache](https://github.com/arduino/arduino-lint/pull/140) when the password wasn't so well behaved as the author of the previously fragile …

[skip changelog] Quote all variables in GitHub Actions workflow shell commands

---

.github/workflows/test.yaml

Bug fix
There are two steps in the test workflow for the Linux ARM64 artifact upload:
- https://github.com/arduino/arduino-cli/blob/5115d44c70ebd1356fda7f3b5a8ca612e9499742/.github/workflows/test.yaml#L179
- https://github.com/arduino/arduino-cli/blob/5115d44c70ebd1356fda7f3b5a8ca612e9499742/.github/workflows/test.yaml#L185
Although it does no real harm since it simply replaces the artifact from the first upload with a duplicate, it does slow down the workflow and makes the workflow slightly more difficult to maintain.
* **What …

[skip changelog] Remove redundant artifact upload from test workflow

---

docs/library-specification.md

Docs update
The [library.properties](https://arduino.github.io/arduino-cli/dev/library-specification/#library-metadata) `includes` field specifies a custom list of files to be added to the sketch by the IDE as `#include` directives. Library authors sometimes add filenames from library dependencies to this field. However, that doesn't make any sense because all Arduino development software versions with support for the `includes` field also have support for resolution of the dependencies of libraries, meaning that there is no …

[skip changelog] Specify that `includes` field items should be in library

---

docs/library-specification.md

Replace "Arduino Pro IDE" with proper link to Arduino IDE 2.0

---

arduino/libraries/librariesmanager/download.go
arduino/libraries/librariesmanager/librariesmanager.go
commands/instances.go
docs/UPGRADING.md
test/test_lib.py
test/test_update.py

This PR implements the check for library_index.json.sig.
It has been implemented also the download of the gzipped version of the index to reduce bandwidth usage.

Check gpg signature for library_index.json

---

commands/upload/upload.go

Fixes an upload bug.
If a platform has set `upload.wait_for_upload_port` property to `true` in the `boards.txt` without setting also `upload.use_1200bps_touch` to `true` the CLI waits for the port anyway even if it's not necessary.
`upload.wait_for_upload_port` property now defaults to `false` and is set only if `upload.use_1200bps_touch` is `true` as is documented right now: https://arduino.github.io/arduino-cli/dev/platform-specification/#1200-bps-bootloader-reset
- **Does this PR introduce a …

Fix upload waiting for port without 1200bps touch

---

arduino/cores/packagemanager/loader.go
test/test_core.py

Bug fix.
If a platform installed manually in the Sketchbook hardware folder doesn't have a `platform.txt` file its name will be empty.
```
$ arduino-cli core list                                                                                                                                                                                     
ID                            Installed Latest Name …
```

Fix empty name on manually installed platforms without platform.txt

---

cli/burnbootloader/burnbootloader.go

Fixes a command example.
`arduino-cli burn-bootloader --help` prints this as an example:
```
Examples:
arduino-cli burn-bootloader -b arduino:avr:uno -P atmel-ice
```
The programmer ID `atmel-ice` doesn't exist.
`arduino-cli burn-bootloader --help` now prints the correct programmer ID in the example:
```
Examples:
arduino-cli burn-bootloader -b arduino:avr:uno -P atmel_ice
```
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CON …

[skip changelog] Fix burn-bootloader command example

---

commands/board/list.go
commands/board/list_test.go
commands/bundled_tools_serial_discovery.go

Removed now useless boilerplate code for BoardList.
No changes in behavior.
No breaking changes.

Removed now useless boilerplate code for BoardList

---

arduino/cores/board.go
arduino/cores/board_test.go
arduino/cores/cores.go
arduino/cores/packagemanager/identify.go
arduino/cores/packagemanager/loader.go
arduino/cores/packagemanager/loader_test.go
commands/board/list_test.go

The implementation follows the pluggable discovery specification.
Now the board identification is done on `myboard.upload_port.N.PROP` definitions in `boards.txt` so, the old:
```
myboard.vid.0=0x1234
myboard.pid.0=0x4567
```
should be changed to:
```
myboard.upload_port.0.vid=0x1234
myboard.upload_port.0.pid=0x4567
```
Anyway, to keep backward compatibility all the existing non-pluggable platforms are automatically and transparently converted to the new format.

Implemented pluggable discovery board matching

---

arduino/builder/sketch_test.go
arduino/builder/testdata/TestSketchWithIppFile/TestSketchWithIppFile.ino
arduino/builder/testdata/TestSketchWithTppFile/TestSketchWithTppFile.ino
arduino/globals/globals.go
arduino/sketch/sketch_test.go
arduino/sketch/testdata/SketchWithIppFile/SketchWithIppFile.ino
arduino/sketch/testdata/SketchWithTppFile/SketchWithTppFile.ino
test/test_compile.py
test/testdata/sketch_with_ipp_file_include/sketch_with_ipp_file_include.ino
test/testdata/sketch_with_tpp_file_include/sketch_with_tpp_file_include.ino

This is an update for known file extensions list to support C++'s '.tpp' files.
Currently if we include a lib, which contains tpp's, from 'src' folder (within sketch dir) compiler does not copy template files, so the build is failing.
.tpp files should be copied on a verify/upload event to build temp folder along with other .cpp/.h etc.
No, tpps will be …

added '.tpp' file ext to known list

---

arduino/discovery/discovery.go
arduino/discovery/discovery_test.go
commands/bundled_tools_serial_discovery.go

Enhances pluggable discovery.
The discovery process is started when a `PluggableDiscovery` is created.
The discovery process is now started when calling `Run`.
This should avoid starting discoveries when not necessary, for example when running commands that don't need discoveries. It will also be easier to tests the loading and creation of third party pluggable discoveries.
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRI …

[skip changelog] Change discoveries not starting when created

---

test/conftest.py

bug fix
The key names used in Arduino CLI's JSON output were made consistent and standardized (https://github.com/arduino/arduino-cli/pull/1223). One of the helper functions for
the integration tests was not updated accordingly. This was missed because it is only used when running the tests locally
due to requiring a board to be connected to the computer. That caused the test to have a spurious failure:
```
ERROR test\test_upload.py::test_upload - AttributeError: 'NoneType' object has no attribute 'split'
```
* **What is the …

[skip changelog] Update JSON output key name in integration test helper

---

docs/sketch-specification.md

Updates the Sketch specifications docs with missing information.
The Sketch specifications docs don't list `.tpp` and `.ipp` as supported code files extensions.
The Sketch specifications docs list `.tpp` and `.ipp` as supported code files extensions.
Nope.
These extensions have been added with #1316 but docs weren't updated …

[skip changelog] Add missing file extensions to Sketch specifications docs

---

commands/daemon/daemon.go

bug fix
In the early days of Arduino CLI's gRPC interface, the protocol buffer compilation was done via[ `go generate`](https://golang.org/pkg/cmd/go/internal/generate/), configured
by a directive comment. [The `protoc:compile` task](https://github.com/arduino/arduino-cli/blob/35bec19a2576d63487363c6674e087a66fc20c9f/Taskfile.yml#L86) is now used instead, but the old directive was left in place, where it became outdated through changes to the repository structure.
This directive no longer functions or serves a purpose and might …

[skip changelog] Remove obsolete go generate directive

---

Taskfile.yml

This PR fixes a bug in `Taskfile.yml`.
If the user has configured `git` to always show commit signatures in `git log`, then `task` *could* emit malformed arguments to the `go build` command generated from `task build`.
For example, in my `git` config file:
```gitconfig
[log]
showSignature = true
```
And then running `task build` you will see rather confusing output:
```sh
arduino-cli $ task build
task: [build] go build -v -ldflags ' -X github.com/arduino/arduino-cli/version.versionString=git-snapshot -X github.com/arduino/arduino-cli/version.commit=gpg: Signature made Thu Jul  1 12:22:24 2021 CDT
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
1b055e5e -X github.com/arduino/arduino-cli/version.date=2021-07-01T22:25:11Z '
task: Failed to run …
```

task: Sanitize git log output when building COMMIT variable

---

arduino/cores/cores.go
arduino/cores/cores_test.go
arduino/cores/packageindex/index.go
arduino/cores/packageindex/index_test.go
arduino/cores/packagemanager/download.go
arduino/cores/packagemanager/package_manager.go
arduino/cores/status.go
commands/board/details.go

This PR adds the parsing of the `discoveryDependencies` field in `package_index.json` as specified in Pluggable Discovery RFC.
No breaking changes.

Added discoveries support in package_index.json

---

Taskfile.yml

Bug fix
For the sake of portability of tasks, [Task](https://taskfile.dev/#/) uses[ `mvdan.cc/sh`](https://pkg.go.dev/mvdan.cc/sh/v3) to provide an command interpreter that is independent of the environment. While one of the great strengths of Task, this produces unexpected results in some rare cases. This is one of those cases. There is some unusual interaction between `mvdan.cc/sh`, Windows, and running the `rice embed-go` command from the subshell created by the parentheses in this command:
```
$ task i18n:update
←[32mtask: …
```

[skip changelog] Make `i18n:generate` task Windows compatible

---

docs/UPGRADING.md
i18n/i18n.go
main.go

Code restructuring
The user can configure their locale preference via the undocumented `locale` [configuration key](https://arduino.github.io/arduino-cli/dev/configuration/#configuration-keys). This information is given priority by the `github.com/arduino/arduino-cli/configuration` package over the automatically detected locale.
Previously, the `i18n` package got the configuration setting from the `github.com/arduino/arduino-cli/configuration` package, but this will result in an import cycle when the `i18n` package is used to …

[breaking] Pass user locale preference directly to i18n package

---

.github/dependabot.yml

Management of the actions dependencies of the repository's GitHub Actions workflows is done manually. Outdated action versions will only be discovered if a review is done by a maintainer, which is not likely to happen often. The workflows do follow the practice of using the major version ref of the action whenever one is provided, which means that the latest version of the action is used up until such time as there is a major version bump. But after that the workflow will be using an outdated action. …

[skip changelog] Configure Dependabot to check for outdated actions used in workflows

---

.github/workflows/check-certificates.yml

Infrastructure update
We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, but have not yet been pulled into this repository.
Workflow is synced with the state of the art from upstream.
Notable:
- Trigger workflow run on modification to facilitate testing. …

[skip changelog] Sync certificate check CI workflow with template

---

.github/dependabot.yml

Dependabot is configured to submit pull requests for updates to the GitHub Actions actions used in the repository's workflows whenever a new version is available. These commits will create entries in the automatically generated draft changelog, but will not result in any user facing changes and so have no place there. The release manager's time will be wasted by cleaning them out of the raw changelog.
The message title of the commits generated by Dependabot will be …

[skip changelog] Add skip changelog prefix to Dependabot workflow update commits

---

client_example/go.sum
docsgen/go.mod
docsgen/go.sum
go.mod
go.sum

Fix some outstanding CVEs. No apparent breakage.

Update github.com/miekg/dns lib to v1.1.43

---

docs/CONTRIBUTING.md

Docs update/fix
This content is for maintainers, and is not of interest to the average contributor. It makes an already overly long
contributor guide even more overwhelming, and thus likely to be skipped.
---
Links in the contributor guide to documentation system assets were broken by changes to the file names during the sync to the "template" assets.
The documentation versioning and publishing system is now maintained in a centralized repository hosting a collection of
reusable project assets. …

[skip changelog] Move website versioning information out of CONTRIBUTING.md

---

Taskfile.yml

Infrastructure clean up
The "gRPC reference" section of the documentation website is automatically generated from the repository's protocol
buffer files. In order to make this generation process easy for developers to run, the necessary commands are defined in
a task.
For some reason, there were two tasks for this purpose, with different names and descriptions, but identical commands.
This makes the taskfile more difficult to understand and more difficult to maintain.
One of the tasks, …

Remove duplicate task for protobuf docs generation

---

commands/core/install.go

The code tried to log the wrong error, which was nil, and resulted in a
nil dereference.
This would occur for example when a version of the core was already
installed manually in the sketchbook, and you would try to install
another version using arduino-cli, uninstalling the previous version
would fail (not managed by package manager) and the nil dereference
would happen:
$ arduino-cli core install arduino:avr@1.8.2
Tool arduino:avr-gcc@7.3.0-atmel3.6.1-arduino5 already installed
Tool arduino:avrdude@6.3.0-arduino17 already installed
Tool arduino:arduinoOTA@1.3.0 already installed
Downloading packages...
arduino:avr@1.8.2 already downloaded
Upgrading arduino:avr@1.8.3 with arduino:avr@1.8.2...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: …

Fix nil dereference when core uninstall fails during upgrade

---

.github/dependabot.yml

The Dependabot configuration specifies that the message title of the commits generated by Dependabot will be prefixed with "[skip changelog]" in order to cause them to be automatically excluded from the generated changelog (https://github.com/arduino/arduino-cli/pull/1381).
It turns out there is an undocumented maximum length of 15 characters for the Dependabot commit prefix:
https://github.com/arduino/arduino-cli/network/updates
```
Dependabot encountered the following error when parsing your …
```

[skip changelog] Revert "Add skip changelog prefix to Dependabot workflow update commits (#1381)"

---

.github/workflows/check-go-task.yml
Taskfile.yml

The repository contains multiple Go modules. The CI workflow that lints and checks the formatting of the repository's Go code only checks the primary module in the root of the repo.
This workflow is now expanded to cover all Go code through the use of a dedicated matrix job for each of the modules.
Arbitrary Go module paths can be specified to the tasks by defining the `GO_MODULE_PATH` environment variable. If this
variable is not defined, the default root module path …

[skip changelog] Run formatting and linting CI checks on all Go modules

---

.github/workflows/release-go-task.yml

Infrastructure update
We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, but have not yet been pulled into this repository.
Notable:
- Replace changelog file read, deprecated `actions/create-release`, and asset upload steps with[ the comprehensive `ncipollo/release-action` …

[skip changelog] Sync "Release" CD workflow with template

---

.editorconfig
.github/tools/fetch_athena_stats.sh
docs/installation.md
install.sh

Infrastructure update
We have assembled a collection of reusable project assets:
https://github.com/arduino/tooling-project-assets
These assets will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" installation script, and those are
introduced to this repository via this pull request.
Workflow is synced with the state of the art from upstream.
Notable:
- [ShellCheck …

[skip changelog] Sync install script with template

---

.github/workflows/test-go-task.yml

Bug fix
The "Test Go" workflow uploads code coverage data to Codecov. There will occasionally be spurious upload failures caused
by transient network outages. These will typically succeed after the workflow is re-run, but the option to re-run is not
offered when the workflow run passes.
Because it's important that the data be complete, the `codecov/codecov-action` action is configured to fail the workflow
run if the upload does not succeed. However, the upload will never be able to succeed for workflow runs in a fork where
the owner has not set up Codecov.
This can cause confusion to contributors who have enabled GitHub Actions in …

[skip changelog] Don't require Codecov upload success for test run in fork

---

.github/workflows/check-go-task.yml
.github/workflows/check-i18n-task.yml
.github/workflows/check-protobuf-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/test-go-integration-task.yml
.github/workflows/test-go-task.yml

The [trunk-based development](https://trunkbaseddevelopment.com/) strategy is employed by this repository. This means that the release branch may contain a subset of the history of the default branch.
The status of the GitHub Actions workflows should be evaluated before making a release. However, this is not so simple as checking the status of the commit at the tip of the release branch. The reason is that, for the sake of efficiency, the [workflows are configured](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) to run only when the processes are relevant to the trigger event (e.g., no need to run the Go …

[skip changelog] Run relevant workflows on release branch creation

---

.github/workflows/github-stats.yaml

The `actions/github-script` GitHub Actions action dependency of the "github-stats" workflow is pinned to the patch version. This means it must be updated every time a release of the action is made.
Use of the major version ref will cause the workflow to automatically benefit from ongoing development to its `actions/github-script` GitHub Actions action dependency at each patch or minor release without any intervention from a maintainer, up until such time as a new major …

[skip changelog] Use major version ref for `actions/github-script` action

---

commands/upload/upload.go

Bug fix for #1198
`arduino-cli upload` command failed.
`runtime.os` property is not substituted for properties in `upload` sub-command execution.
`arduino-cli upload` command will succeed.
`runtime.os` property substitute for properties.
* **Other information:**
When you upload a program, it works as expected within Arduino IDE (V1.18.X) environment.
This fix improves the compatibility of the Arduino IDE (V1.18.X).

add runtime.os property in `upload` sub-command

---

commands/board/search.go
test/test_board.py

Fixes a bug with an existing command and related gRPC function.
`board search` command and related gRPC function don't return board FQBNs belonging to an installed core if it's not the latest version available.
```
$ arduino-cli core list
ID           Installed Latest Name                                        
arduino:samd 1.8.10    1.8.11 Arduino SAMD Boards (32-bits ARM Cortex-M0+)
$ arduino-cli board search arduino:samd:mkrwifi1010
Board Name FQBN Platform ID 
$ arduino-cli board search mkr wifi 1010
Board Name …
```

Fix board search not returning boards if installed core is not latest version

---

commands/upload/upload.go
commands/upload/upload_test.go
docs/platform-specification.md

Fixes a bug with pluggable upload.
Board upload properties that are specific to a certain protocol don't override the default property when protocol is specified.
Board upload properties that are specific to a certain protocol now override the default one.
Using the following properties:
```
leonardo.upload.speed=256                                                                                                                           
leonardo.upload.serial.speed=57600 …
```

Fix upload properties not overridden by protocol specific ones

---

commands/compile/compile.go
test/test_compile.py

Fix a bug in a command and relative gRPC interface.
Calling `arduino-cli compile --build-path ../build-path -b arduino:avr:uno ~/Arduino/Blink` fails with an unclear error cause of the relative build path:
```
Couldn't deeply cache core build: Rel: can't make ../build-path relative to /tmp/arduino-core-cache                                                
Running normal build of the core...                                                                                                                
Error during build: Rel: …
```

Fix compile --build-path not working with relative paths

---

test/conftest.py
test/test_compile.py
test/test_core.py
test/test_upload_mock.py

Fixes some integration tests.
Upload integration tests are failing on OS X because `board list` command returns also bluetooth devices.
Also some tests are failing cause they're using too old versions of `esp32` platform.
Boards without an FQBN are now skipped in integration tests.
We also updated the package index URL for `esp32` and some platform version used for testing.
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRI …

[skip changelog] Fix integration tests on OS X

---

test/conftest.py
test/test_board.py
test/test_cache.py
test/test_compile.py
test/test_completion.py
test/test_config.py
test/test_core.py
test/test_debug.py
test/test_lib.py
test/test_main.py
test/test_outdated.py
test/test_sketch.py
test/test_update.py
test/test_upgrade.py
test/test_upload.py
test/test_upload_mock.py

Enhances the integration tests for Windows to make them work with path that contain spaces.
Integration test can't run on Windows if the user has a space in its name, thus having paths with spaces.
Integration test can now run on Windows correctly also if the user has a path in its name.
None.
This brings it in line with …

[skip changelog] Fix Windows integration tests

---

.github/workflows/test-go-integration-task.yml

A bug introduced in the 3.9.7 release of Python causes [a spurious failure](https://github.com/arduino/arduino-cli/pull/1440/checks?check_run_id=3561952128#step:8:916) of the `test\test_lib.py::test_install_git_invalid_library` integration test:
https://bugs.python.org/issue45121
As a workaround, the Python version used by the "Test Integration" CI workflow that runs the integration tests is pinned to the last working version: 3.9.6.
- **Does this PR introduce a breaking …

[skip changelog] Temporarily full pin Python in integration test CI workflow

---

arduino/cores/packagemanager/package_manager_test.go
arduino/cores/tools.go

- some code makeup
- simplified `Tool.LatestRelease()` (now it doesn't depend on `tool.FindReleaseWithRelaxedVersion` anymore, this fact will help with another refactoring later)

simplified `Tool.LatestRelease()` and some code makeup

---

commands/bundled_tools_mdns_discovery.go

bug fix
A typo in the checksum definition for the `arm-linux-gnueabihf ` host version of the mdns-discovery tool caused installation to fail on that target:
```
Installing builtin:mdns-discovery@0.9.2...
Error initializing instance: installing builtin:mdns-discovery@0.9.2 tool: Cannot install tool builtin:mdns-discovery@0.9.2: testing local archive integrity: testing archive checksum: invalid checksum format: SHA-256cc1096936abddb21af23fa10c435e8e9e37ec9df2c3d2c41d265d466b03de0af
```
The tool …

Correct typo in mdns-discovery archive checksum

---

.github/workflows/arduino-stats.yaml
.github/workflows/github-stats.yaml

Changes two workflows.
`arduino-stats.yaml` and `github-stats.yaml` workflows can't be triggered manually.
`arduino-stats.yaml` and `github-stats.yaml` workflows can be triggered manually.
Nope.
None.
---

[skip changelog] Add workflow and repo dispatch triggers to stats collection workflows

---

arduino/libraries/librariesmanager/install.go

Fixes an issue with handling of git URLs when installing libraries using `--git-url`.
When using `arduino-cli lib install` with the `--git-url` flag too many characters may be stripped from the end of the library name. Internally the librarymanagers [`parseGitURL`](https://github.com/arduino/arduino-cli/blob/master/arduino/libraries/librariesmanager/install.go#L243) function is incorrectly using `strings.TrimRight` instead of `strings.TrimSuffix`.
Example:
```
strings.TrimRight("NTPClient.git", ".git") => "NTPClien" …
```

Fix an issue with arduino-cli lib install stripping too many characters from library names in git URLs

---

.github/tools/fetch_athena_stats.sh
.github/workflows/arduino-stats.yaml

Add partition load query before fetching metrics and schedule extraction 3 times a day, in order to get more granular datapoints
---

[skip changelog] Add partition load query before fetching metrics and schedule extraction 3 times a day

---

poetry.lock
pyproject.toml

Fixes an issue with Python integration tests.
Integration tests are failing because a library has issue with Python 3.9.7.
Failing workflow: https://github.com/arduino/arduino-cli/runs/3698900893?check_suite_focus=true
Constrain maximum Python version usable to be equal or greater than `3.8` and older than `3.9.7` to stop integration tests from failing. …

[skip changelog] Fix integration tests by setting a maximum python version

---

.github/tools/fetch_athena_stats.py

Fixes Python script that fetches downloads data from Athena.
Athena partitions are not loaded before the query byt the script that fetches download data, this may lead to potential losses of downloads count.
Athena partitions are now loaded before the query byt the script that fetches download data.
Nope.
None.
---
See [how to …

[skip changelog] Add missing partitioning query in Athena script

---

.github/workflows/check-mkdocs-task.yml
.github/workflows/check-python-task.yml
.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml

Bug fix
A bug introduced in the 3.9.7 release of Python causes a spurious failure of the
`test\test_lib.py::test_install_git_invalid_library` integration test:
https://bugs.python.org/issue45121
As a workaround, the last working version of Python must be used: 3.9.6. In order to ensure this is done when running the
integration tests locally, this version is specified in the Poetry configuration (https://github.com/arduino/arduino-cli/pull/1470). Even though only the integration tests
require this version limitation, the Poetry …

[skip changelog] Temporarily full pin Python in all GitHub Actions workflows

---

docs/installation.md

Documentation enhancement and fix
A defect fix and multiple improvements have been made to the upstream "template" installation documentation which this project's installation docs are based on:
https://github.com/arduino/tooling-project-assets/blob/main/other/installation-script/installation.md
The defect is present in this repository's installation instructions and the improvements are not.
This repository's installation documentation is at the state of the art.
- **Does this PR introduce a …

[skip changelog] Sync install docs from "template"

---

README.md
docs/index.md

Unlike the IDE and Web Editor, Arduino CLI is intended to be used directly only by advanced users. However, all types of
users are likely to visit the repository and documentation website. Some of these readers will not be familiar with the
meaning of the acronym "CLI".
The previous documentation introduces Arduino CLI as:
> an all-in-one solution that provides [wonderful things] to use any Arduino compatible board and platform
Which sounds like something every Arduino user would be interested in. …

[skip changelog] Mention interfaces in documentation introduction

---

commands/instances.go

Adds a way for gRPC consumers to refresh the CLI locale without restarting the daemon process.
gRPC consumers have no way of changing the language of the CLI without restarting the daemon process.
gRPC consumers can now call the `Init` function to refresh the locale in use. 
Nope.
None.
---
See [how to …

Locale is now refreshed on Init

---

version/version.go

generic change
`arduino-cli version` prints an "alpha" suffix
alpha is not printed anymore
yep
---

remove the alpha suffix

---

cli/upload/upload.go
test/test_upload.py

partially revert "refactor sketch path calculation" in `upload.go`
fix regression
The test `test/test_upload.py::test_upload_with_input_dir_flag` was failing
fixed the regression introduced by reverting a change made in #1542 
no
---

fix a regression introduced in #be5022e. `--input` flags were ignored

---

legacy/builder/container_add_prototypes.go
legacy/builder/container_find_includes.go
test/test_compile_part_4.py
test/testdata/sketch_with_missing_include/sketch_with_missing_include.ino

Makes the generation of the "compilation database" more resilient.
the database generation fails if the sketch cannot compile.
The database is generated anyway unless there are critical components missing or the platform is misconfigured.
No

Do not give-up on `compile --only-compilation-database` if prototypes generation fails

---

test/README.md

Fix a link in a markdown file.
`tests/README.md` contains a malformed link: `../docs/CONTRIBUTING.md/#integration-tests`
`tests/README.md` link is now correct: `../docs/CONTRIBUTING.md#integration-tests`
Nope.
The check is now failing cause the new recent release of `markdown-link-check` correctly indentifies the link as broken. …

[skip changelog] Fix link in tests README.md

---

arduino/discovery/discovery.go

Bug fixing.
If the user has installed a core that comes with a pluggable discovery that doesn't send an `ok` message after a discovery command is received the `arduino-cli` might panic when running some commands.
The `arduino-cli` doesn't panic anymore but just logs the error if a discovery doesn't send an `ok` message after receiving a discovery command.
Nope.
None.
---
See [how to …

Fix panic when discovery doesn't send an ok message after a command

---

.github/workflows/test-go-integration-task.yml
.github/workflows/test-go-task.yml

The **Test Go** workflow on Windows is broken after the newest release of Task (3.9.1) and was working fine with 3.9.0
The problem should be linked to the upgrade in `mvdan/sh` they did in 3.9.1.
The bug is present only on Windows, apparently the PATH env variable is not expanded correctly under subcommands. Log attached for further details
To mitigate the problem, we decided to pin the task version used to 3.9.0 in the workflows
- **Does this PR introduce a breaking change, …

Pin task version to 3.9.0 because of the PATH on win bug

---

.github/workflows/check-i18n-task.yml
Taskfile.yml

Enhances the `i18n:check` task to also verify that translations files other than `en.po` are up to date.
`i18n:check` verifies that `en.po` has the same data and formatting as the one generated by `i18n:update`.
`i18n:check` task used to verify only if the source `en.po` file was up to date. The new process instead verifies that all translations are up to date by downloading them directly from Transifex.
The previous process was causing some issues since after uploading the `en.po` file Transifex …

Enhance `i18n:check` task

---

.github/workflows/test-go-integration-task.yml
.github/workflows/test-go-task.yml

This reverts commit 55ad9ecb424cbc816890897d0b6af081f45f7d40.
infrastructure update
https://github.com/arduino/tooling-project-assets/pull/186
nope
---

[skip-changelog] Revert "Pin task version to 3.9.0 because of the PATH on win bug (#1576)"

---

cli/daemon/daemon.go

Adds json output to an existing command.
Calling `arduino-cli daemon --format json` would produce no output.
Calling `arduino-cli daemon --format json` now prints the IP and port used:
```
$ arduino-cli daemon --format json
{
"IP": "127.0.0.1",
"Port": "50051"
}
```
This might be useful when the client lets us choose the port used randomly by setting it to `0`:
```
$ arduino-cli daemon --port 0 --format json 
{
"IP": "127.0.0.1",
"Port": "44885"
}
$ arduino-cli daemon --port 0 --format json 
{ …
```

Add json output to daemon command

---

cli/cli.go
cli/feedback/feedback.go
cli/version/version.go

Adds a new output format.
The `arduino-cli` supports two output formats as of now: `text` (default) and `json`.
`json` is always pretty printed, this might make it difficult for some to parse it correctly, it also make the output much more longer than necessary with lots of empty space.
The `arduino-cli` now supports three output formats as of now: `text` (default), `json` and `jsonmini`.
Example output:
```
$ arduino-cli board list
Port         Protocol Type              Board Name …
```

Add minified json output format

---

.github/workflows/sync-labels.yml

Infrastructure enhancement.
The [`carlosperate/download-file-action` action](https://github.com/carlosperate/download-file-action) is used in the "Sync Labels" GitHub Actions workflow as a convenient way to download external resources.
Due to it being the only option other than using an unstable version from the branch tip, the workflow does a full pin of the action version, meaning that the workflow must be updated after every new release of the action (e.g., https://github.com/arduino/arduino-cli/pull/1601).
* **What is the …

[skip changelog] Use major version ref of `carlosperate/download-file-action`

---

cli/cli.go
cli/feedback/feedback.go
cli/version/version.go

This pr enhances the `feedback` package by allowing to use also the YAML format.
For the YAML marshal It's been selected a YAML dependency already present in `go.mod`
---

Add YAML to feedback formats

---

install.sh

Infrastructure fix.
The installation script checks for an existing installation in the PATH in order to provide appropriate advice to the
user about adding the installation to their their PATH environment variable.
This check is done using `command -v`. It turns out that the exit status is shell dependent in the event the command is
not found, so that it might be either 1 or 127 depending on the user's system. The script previously assumed that the
exit status would be 1 when the command was not found in PATH, which resulted in …

Fix install script's check for previous installation

---

commands/monitor/monitor.go

The `arduino-cli monitor -c ....` flag wasn't working, this PR fix the problem
Port settings are not applied.
Port settings are applied.
No
Fix #1562

Bugfix: apply monitor settings on monitor opening

---

arduino/errors.go
cli/arguments/reference.go
cli/arguments/reference_test.go
cli/core/download.go
cli/core/install.go
cli/core/uninstall.go
cli/core/upgrade.go
docs/UPGRADING.md
test/test_core.py

Feature
installing / uninstalling / upgrading / downloading cores is not case insesitive
now it is's case-insensitive, so it works if you try to `core install Arduino:samd`
no
---

Optimize `core` operations, improving on the user input

---

legacy/builder/hardware_loader.go

The change is mainly on the legacy package and influence how the `arduino-builder` behaves.
If an installed platform has errors that prevent its loading, the builder will abort the compilation, even if the platform is not needed for the build and is not compiled at all.
The error is ignored (just printed on the output), and the compile continues.
No

Do not abort compile if loading errors happens for not compiled platforms

---

commands/upload/upload.go

Previously we checked the upload recipe for the variable `{serial.port}` to determine if the upload requires a serial port, but this is not sufficient because we must check also for the variable `{serial.port.file}`.
No breaking changes.
Current output:
```
$ arduino-cli upload --dry-run -v -b arduino:samd:adafruit_circuitplayground_m0
Skipping 1200-bps touch reset: no serial port selected!
Waiting for upload port...
No upload port found, using  as fallback
"/home/megabug/.arduino15/packages/arduino/tools/bossac/1.7.0-arduino3/bossac" -i -d --port={serial.port.file} -U true -i -e -w -v "/tmp/arduino-sketch-61DECCCDDA68480BC07770DEB6E56DDB/Bare.ino.bin" -R
```
As we can see the `bossac` tool is launched anyway with the unexpanded `{serial.port.file}` variable.
New behavior:
```
$ …
```

Better detection of required serial port during upload.

---

arduino/cores/packagemanager/loader.go
arduino/cores/packagemanager/loader_test.go
commands/upload/upload.go
test/test_upload_mock.py

Improves the automatic conversion of platforms to keep backward compatibility after the introduction of pluggable-discovery.
If a platform defines `upload.tools` in the configuration part of the `boars.txt` (typically in the `menu.*.*.upload.tool` properties), the upload will fail because the properties under the `menu.*` hierarchy are not converted.
The properties are now converted.
No
Fix arduino/arduino-cli#1444

Improved pluggable discovery conversion for platforms not supporting it

---

arduino/discovery/discovery.go
arduino/monitor/monitor.go

Allow case-insensitive `ok` or `OK` replies from pluggable discoveries and monitors.
If a discovery or a monitor replies to a command, for example, with:
```
{
"eventType": "describe",
"message": "ok",
"port_description": {
"protocol": "serial",
"configuration_parameters": {
}
}
}
```
the answer is treated as an error because it requires a **case-sensitive** `"OK"`.
Also. the error message is completely useless:
```
Error getting port settings details: Port monitor error: command 'describe' failed: ok
```
**What is the new …

Allow case-insensitive `ok` or `OK` replies from pluggable discoveries and monitors

---

docs/package_index_json-specification.md
docs/pluggable-monitor-specification.md

Some documentation improvement for pluggable discovery/montior

---

arduino/cores/packagemanager/download.go
arduino/cores/packagemanager/package_manager_test.go
arduino/cores/packagemanager/testdata/package_tooltest_index.json

Fixed a bug that prevented pluggable monitors to be installed
non-builtin pluggable monitors are not installed (see https://github.com/arduino/arduino-cli/issues/1564)
non-builtin pluggable monitors are now installed
No breaking changes

bugfix: Install pluggable monitor dependencies together with a platform

---

i18n/cmd/commands/transifex/pull_transifex.go
i18n/cmd/commands/transifex/push_transifex.go
i18n/cmd/commands/transifex/transifex.go

Updates the `i18n` commands.
`i18n` commands to push and pull translation files use the deprecated [Transifex API 2.0](https://docs.transifex.com/api/introduction).
The `i18n` commands have been updated to use the new [Transifex API 3.0](https://transifex.github.io/openapi/index.html#section/Introduction).
Nope.
Closes #1494. …

Update i18n scripts to use Transifex REST API v3

---

.github/workflows/check-i18n-task.yml
.github/workflows/i18n-nightly-push.yaml
.github/workflows/i18n-weekly-pull.yaml

Fixes i18n workflows.
Following workflows are failing cause `TRANSIFEX_ORGANIZATION` env var is missing:
* `.github/workflows/check-i18n-task.yml`
* `.github/workflows/i18n-nightly-push.yaml`
* `.github/workflows/i18n-weekly-pull.yaml`
Workflows don't fail anymore.
Nope.
None.
---
See [how to …

Add missing env var to i18n workflows

---

arduino/monitor/monitor.go
commands/monitor/monitor.go

* Added more logging for pluggable monitor
* Force monitor close if the port cannot be opened (fix resource leak)
no breaking change

Improved error logging for pluggable monitors / Fixed resource leak in some rare conditions

---

commands/compile/compile.go
test/test_compile_part_4.py

- [x Tests for the changes have been added (for bug fixes / features)
Fixes a panic on `compile`.
```
$ arduino-cli compile -b aduino:avr:uno ~/Documents/Arduino/Blink/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x10128f424]
goroutine 1 [running]:
github.com/arduino/arduino-cli/arduino/cores.(*Platform).String(...)
/Users/alien/workspace/arduino-cli/arduino/cores/cores.go:262
github.com/arduino/arduino-cli/commands/compile.Compile(0x1016a1 …
```

Fix panic calling compile with wrong FQBN

---

arduino/cores/packagemanager/install_uninstall.go
arduino/cores/packagemanager/loader_test.go
arduino/cores/packagemanager/package_manager.go
arduino/cores/packagemanager/package_manager_test.go
arduino/discovery/discovery.go
arduino/discovery/discovery_test.go
arduino/monitor/monitor.go
arduino/monitor/monitor_test.go
commands/board/list_test.go
commands/daemon/daemon.go
commands/debug/debug.go
commands/debug/debug_test.go
commands/instances.go
commands/upload/upload.go
commands/upload/upload_test.go
docs/UPGRADING.md
docs/platform-specification.md
executils/process.go
executils/process_test.go
legacy/builder/builder_utils/utils.go
legacy/builder/create_cmake_rule.go
legacy/builder/ctags_runner.go
legacy/builder/gcc_preproc_runner.go
legacy/builder/hardware_loader.go
legacy/builder/phases/libraries_builder.go
legacy/builder/phases/linker.go
legacy/builder/phases/sizer.go
legacy/builder/preprocess_sketch.go
legacy/builder/recipe_runner.go

> ~~Adds a new environment variable `ARDUINO_MODE` that is passed on all tools launched by the CLI.~~
> ~~The value of the variable may be:~~
> ~~* `cli` if the `arduino-cli` is used from terminal or scripts as a pure command-line tool.~~
> ~~* `daemon` if the `arduino-cli` is launched as a daemon.~~
Adds an `ARDUINO_USER_AGENT` environment variable to all the tools launched for compile and upload.
The variable is in HTTP user-agent format and contains the version of the CLI and possibly the version of the gRPC client of the user if this information is available. …

[breaking] Add env variable to let tools know the cli version and the gRPC client version

---

cli/compile/compile.go
cli/upload/upload.go
commands/upload/upload.go
test/test_compile_part_4.py

Enhances certain error messages of `compile` and `upload` commands.
```
$ arduino-cli core list
$ arduino-cli compile -b arduino:samd:nano_33_iot ~/Arduino/Blink
Error during build: Platform 'arduino:samd' not found: platform not installed
$ arduino-cli compile -b adafruit:samd:adafruit_feather_m4 ~/Arduino/Blink
Error during build: Platform 'adafruit:samd' not found: platform not installed
$ arduino-cli upload -b arduino:samd:nano_33_iot ~/Arduino/Blink -p /dev/ttyACM1
Error during Upload: Unknown FQBN: platform arduino:samd …
```

Sample command to solve compile or upload issue is now shown to CLI users

---

cli/daemon/daemon.go

Adds a new flag to an existing command.
A user running `daemon` has no way of setting a custom IP. 
A user can now use the `--ip` flag to use a custom IP to listen for gRPC requests.
Nope.
This flag was also introduced in #1622 but it won't be merged into `master` until the whole configs migration is finished.
Since this is …

Add ip flag to daemon command

---

cli/board/list.go
commands/board/list.go

Makes `arduino-cli` more resilient to errors.
Calling `arduino-cli board list` runs all discoveries installed, by default `builtin:serial-discovery` and `builtin:mdns-discovery` are installed and ran.
If one of those discoveries return an error the whole command fails.
`arduino-cli board list` now prints any error from discoveries and then eventual partial results obtains from other discoveries.
[titled …

board list now returns partial results in case of errors

---

arduino/discovery/discovery.go
arduino/discovery/discovery_client/main.go
arduino/discovery/discoverymanager/discoverymanager.go
commands/board/list.go

Enhances internal handling of pluggable discoveries.
If sending a command to a discovery returns an error its process is left running, this often causes subsequent commands to fail.
If sending a command to a discovery returns an error now its process is killed and the discovery removed from the list of running discoveries.
Nope. …

Discoveries are now closed and unregistered after failure

---

cli/board/list.go

Fix a missing value in the `board list` table output.
```
$ arduino-cli board list
Porta        Protocollo Tipo    Nome scheda FQBN Core
/dev/ttyUSB0 serial     Unknown                 
```
```
$ arduino-cli board list
Porta        Protocollo Tipo              Nome scheda FQBN Core
/dev/ttyUSB0 serial     Serial Port (USB) Unknown
```
No

Fix: add missing value in 'board list' table

---

arduino/security/signatures.go
i18n/cmd/po/parser.go

It's a bug fix.
I have been using arduino-cli as a Go library to run batch operations like installing multiple libraries. I noticed the process was leaking memory quite quickly.
With these two fixes, memory consumption is much more stable. I think there might be still other memory leaks somewhere else, but for now this is what I found.
No breaking …

Fix a couple memory leaks caused by unclosed file handles

---

cli/instance/instance.go

Bug fix
If index parsing on first start fails for some reason, the error is not correctly printed.
The error gets printed
no
See https://github.com/arduino/ArduinoCore-samd/runs/5286418366?check_suite_focus=true#step:7:300
---

Fix error being printed in index parsing during first start

---

arduino/cores/packagemanager/loader.go
arduino/cores/packagemanager/loader_test.go
arduino/discovery/discovery.go
arduino/discovery/discovery_client/main.go
arduino/discovery/discovery_test.go
arduino/errors.go
commands/instances.go
docs/UPGRADING.md
legacy/builder/hardware_loader.go
test/test_core.py

Replace `*status.Status` with `error`s in `packagemanager.Load*` functions
The CLI behaviour is unchanged.
The breaking change is in the golang API of `packagamanager` module, as documented in `UPGRADING.md`.

[breaking] Refactor errors handling in `packagemanager.Load*` methods

---

docs/sketch-build-process.md

It's fairly easy to miss the one line early in the doc that says this text uses 'avr' as an example, leading a reader to possibly believe the documentation hasn't been updated since 'avr' was the only platform choice. Within the doc, the text was a little inconsistent as to how it referred to the avr platform and platform specific tools. This change tries to standardize how we refer to the example platform.
- [X ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
- [ X] Docs have …

[docs] Make use of 'avr' as example platform more consistent

---

cli/arguments/fqbn.go

feature
The only way to specify board options is by appending them along with the fqbn
I've added a CLI flag (`--board-options`) that allows to specify additional options separately from the FQBN. Of course, the old way of adding options along the FQBN is still supported. I've added this possibility because the secureboot will work with a specific board property security=sien(signature and encryption) in order to use it.
[titled …

add flag to allow board options to be specified seperately from fqbn

---

.github/workflows/check-go-dependencies-task.yml
.github/workflows/check-go-task.yml
.github/workflows/check-markdown-task.yml
.github/workflows/check-mkdocs-task.yml
.github/workflows/check-protobuf-task.yml
.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
.github/workflows/test-go-integration-task.yml
.github/workflows/test-go-task.yml
DistTasks.yml
arduino/discovery/discovery_client/go.mod
arduino/discovery/discovery_client/go.sum
client_example/go.mod
docs/CONTRIBUTING.md
docsgen/go.mod
go.mod

Update go version used
We currently use go 1.16.4
We currently use go 1.17.8
nope
---

Bump go version to go 1.17.8

---

arduino/builder/sketch.go
arduino/builder/sketch_test.go
arduino/cores/board.go
arduino/cores/packageindex/index.go
arduino/cores/packagemanager/package_manager.go
arduino/cores/status.go
arduino/cores/tools.go
arduino/libraries/librariesindex/json.go
arduino/monitors/null.go
arduino/resources/checksums.go
arduino/resources/helpers.go
arduino/resources/helpers_test.go
arduino/sketch/sketch.go
cli/feedback/feedback.go
cli/globals/globals.go
cli/lib/args.go
cli/lib/search.go
commands/core/search_test.go
commands/daemon/monitor.go
i18n/cmd/po/parser.go

Fixes a lot of `staticcheck` linter warnings. Two of them are actually non-critical bugs in i18n resource handling.
No change in behaviour
No breaking change.

Some static-check fixes

---

cli/daemon/daemon.go
cli/daemon/interceptors.go

Added `--debug-file` flag to the `daemon` command, so the CLI will output the debug logging output to a specific file (useful when the output of CLI is not visible from the IDE GUI).
No breaking changes.

Added --debug-file flag to gRPC daemon debug mode

---

arduino/monitor/monitor.go
commands/daemon/daemon.go
commands/daemon/term_example/main.go
commands/monitor/monitor.go

Here is the list of bugs fixed, they are all related to the pluggable monitor management and gRPC:
- ensure that monitor processes are killed and collected correctly (previously it leaked a zombie process)
- fixed the gRPC `commands.Monitor` streaming call, now the cancel request is handled correctly
- fixed crash if no configuration is provided in the `commands.Monitor` gRPC call
- reduce timeout for monitor close/quit commands to 250ms, this allows termination of the monitor even if the monitor itself lags in freeing up resources
**Does this PR introduce a …

Fixed some weird behaviour in gRPC Monitor command

---

mkdocs.yml

fix doc
I forgot to update the nav in #1686 
fix nav bar
no
---

[skip-changelog] fix nav being left out form #1686

---

.github/workflows/check-go-dependencies-task.yml

- ~~[N/A] Tests for the changes have been added (for bug fixes / features)~~
- ~~[N/A] Docs have been added / updated (for bug fixes / features)~~
- ~~[N/A] `UPGRADING.md` has been updated with a migration guide (for breaking changes)~~
Bug fix
The "**Check Go Dependencies**" GitHub Actions workflow checks for dependencies with incompatible or unapproved license types.
The dependency license metadata consumed by [the "**Licensed**" tool](https://github.com/github/licensed) is cached in the project repository, in a dedicated …

[skip changelog] Detect unused dependency license metadata files

---

install.sh

(testing is done in the assets repo, but they were not updated there due to the lack of an M1 runner
- [N/A] ~~Docs have been added / updated (for bug fixes / features)~~
- [N/A] ~~`UPGRADING.md` has been updated with a migration guide (for breaking changes)~~
Bug fix
An installation script contained in this repository provides convenient installation of Arduino CLI:
https://arduino.github.io/arduino-cli/dev/installation/#use-the-install-script
Some defects are present in the script's handling of lack of a build for a specific host architecture, which manifested when users with Apple M1 systems attempted to use it:
- …

Fix installation script bugs affecting Apple M1 users

---

.github/workflows/check-go-dependencies-task.yml

- [N/A] ~~`UPGRADING.md` has been updated with a migration guide (for breaking changes)~~
Enhancement
A "Check Go Dependencies" GitHub Actions workflow is used to check whether all Go package dependencies of the modules in this repository use compatible licenses.
This workflow is hosted and maintained in a repository dedicated to a collection of such reusable Arduino tooling project assets.
Several enhancements have been made to the upstream file, but those have not been pulled into this repository.
- Add schedule event trigger to catch breakage caused by external changes
https://github.com/arduino/tooling-project-assets/commit/e71e4702279bd165769efd830f276b6b492de92 …

[skip changelog] Sync "Check Go Dependencies" workflow with upstream

---

arduino/libraries/librariesindex/index.go
arduino/libraries/librariesindex/index_test.go
cli/lib/list.go
commands/lib/list.go
commands/lib/upgrade.go
test/test_lib.py
test/test_outdated.py
test/test_update.py
test/test_upgrade.py

This change resolves #1041, where packages that have upgrades based on `library_index.json` do not show up as upgradable with using the `arduino-cli lib` commands.
When using the `arduino-cli lib` commands to check for or apply updates, packages that have spaces in the name in the index are not shown as upgradable.
The overall behavior is unchanged and commands remain as currently implemented and documented. However, the resolution of packages that have spaces in the names now works, so commands …

Fix resolution of library names when checking for upgrades

---

cli/daemon/interceptors.go

Since many gRPC calls may happen together, to better understand what's happening, now:
- each call is identified by a sequence number (even if they are interleaved)
- when a non-streaming calls ends a "CALL END" log is printed
for example:
```
14 CALLED: /cc.arduino.cli.commands.v1.ArduinoCoreService/Init STREAM_RESP
14 |  REQ:  {
14 |    "instance": {
14 |      "id": 1
14 |    }
14 |  }
14 |  RESP: {
14 |    "Message": {
14 |      "Error": {
14 |        "code": 9,
14 |        "message": "Loading index file: loading json index file …
```

Improved gRPC debug logger

---

.github/workflows/check-protobuf-task.yml

Pin `buf` to v1.4.0. The latest 1.5.0 requires go1.18+.
We could put it back to "latest" once we migrate to go1.18.
No

Pin `buf` to v1.4.0

---

test/conftest.py
test/pytest.ini
test/test_board.py
test/test_completion.py
test/test_lib.py

Integration tests are no more parallelized and the test output Is displayed for better debugging.
The parallelization is no more needed since they are split using GitHub actions runners.
Tests are run in "parallel" (in reality only one test per runner so there is no effective parallelization) and the output is hidden.
Tests are run sequentially and the output is visible.
**Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#bre …

De-parallelize integration test

---

cli/outdated/outdated.go
test/test_upgrade.py

bug fix :bug: 
`arduino-cli outdated --format json` command does not print correctly json output
fixed
nop
---

fix `arduino-cli outdated --format json` output

---

docs/pluggable-monitor-specification.md

Slightly changes the pluggable monitor specification to match the current implementation, see #1738
Technically yes, but actually this change could be considered just as a typo in the specification.
**Other information**:
Fix #1738

Fixed pluggable monitor specification to match the de-facto implementation

---

arduino/libraries/libraries_layout.go
arduino/libraries/libraries_location.go
arduino/libraries/libraries_test.go

Fixed LibraryLocation and LibraryLayout JSON encoder/decoders
JSON decoding of `libraries.Library` object fais due to wrong implementation of `LibraryLocation` and `LibraryLayout` unmarshaler.
JSON decoding now works
No

Fixed LibraryLocation and LibraryLayout JSON encoder/decoders

---

arduino/cores/packagemanager/package_manager.go
arduino/cores/packagemanager/profiles.go
commands/compile/compile.go

The compiler will now detect changes in the filesystem when not using profiles. This fixes a regression described in #1755
The daemon caches all the libraries installed in the sketchbook. This provides a quicker compile but it prevents detection of changes in the sketchbook happening outside the daemon process.
Libraries are re-scanned at each compile.
No …

Do library rescan on compile (if no profies are used)

---

DistTasks.yml

enhancement
The Arduino CLI is built with `CGO_ENABLED=1`:
> Cgo enables the creation of Go packages that call C code
This does not allow the cli to be a fully static binary. We have to use CGO because of `go.bug.st/serial.v1/enumerator` used by [`go.bug.st/serial`](https://pkg.go.dev/go.bug.st/serial):
>  This library tries to avoid the use of the "C" package (and consequently the need of cgo) to simplify cross compiling. Unfortunately the USB enumeration package for darwin (MacOSX) requires cgo to access the IOKit framework. …

disable CGO on every OS except macOS

---

.markdown-link-check.json

This is a test to see if this change helps markdown link checker to pass.

Relax markdown link-check timeouts

---

commands/daemon/daemon.go

~~This is a countermeasure for kernel/firwmare bugs: resources may take a few milliseconds to actually get freed for real after killing the process, or even after a regular closing.~~
~~This delay makes the caller more resilient to this kind of issues.~~
The gRPC `Monitor` request is closed only after the monitor is successfully closed.
gRPC callers of `Monitor` will get the streaming request close as soon as the CLI asks the monitor to "close" (but without waiting for the monitor to actually close). …

Clear gRPC Monitor request only after monitor successfully closes

---

arduino/utils/stream.go

This change should allow a better buffering of the outgoing gRPC messages (fewer messages with bigger data blocks -> less fragmentation). This should allow the clients (IDE) to better handle incoming data.
In particular on Windows, the output of the compile commands may be very fragmented, leading to a lot of small gRPC messages each one transporting just a single o few bytes.
Messages are buffered and sent every 50 ms (unless an higher throughput is required).
**Does this PR introduce a breaking …

Rate limit the number of outgoing gRPC messages

---

.github/workflows/publish-go-nightly-task.yml

Bug fix
During a refactoring of the "Publish Nightly Build" workflow (https://github.com/arduino/arduino-cli/pull/1770/commits/f96ce4bef60a9192f954983ee96e3d27f163b81d), [globbing](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html) of the macOS build artifact filename in the repackaging step was accidentally lost, causing the glob pattern to be treated instead as a string and the updated package saved to a file named by …

[skip changelog] Restore globbing of nightly build artifact filename

---

.codecov.yml
.github/workflows/test-go-task.yml

[Code coverage](https://en.wikipedia.org/wiki/Code_coverage) is an important metric of quality, efficiency, and sustainability of the development and maintenance of a software project.
Although it is commendable that an above average coverage level has been achieved in this project, the current level is still not sufficient.
No meaningful attention is given to the overall coverage level and impact of each specific …

[skip changelog] Enable Codecov reports on pull requests

---

.github/workflows/test-go-integration-task.yml
configuration/network.go

Add a secret token to the User Agent to bypass Cloudflare spam-check filters

[skip-changelog] Try to whitelist CI for Cloudflare spam-check filters

---

arduino/sketch/sketch.go
arduino/sketch/sketch_test.go
legacy/builder/container_setup.go
test/test_compile_part_1.py
test/test_compile_part_3.py
test/test_sketch.py
test/test_upload.py

* Fix #1797
* Removes a compatibility layer for the Arduino IDE 1.x, see https://github.com/arduino/arduino-cli/pull/1187 for details. The proper fix must be made in the Arduino IDE 1.x, not as an exception in the CLI.
```
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 6ac5f7a3 Date: 2022-07-09T19:16:18Z
$ mkdir /tmp/Arduino
$ arduino-cli compile -b arduino:avr:uno /tmp/Arduino/alma
Error opening sketch: no valid sketch found in C:\Users\per\AppData\Local\Temp\Arduino: missing …
```

Fix path in error messages on sketch loading

---

arduino/resources/checksums.go
commands/instances.go

Package indexes are loaded after the installed platforms.
The reason for this change is that the installed packages keep an extract of the original `package_XXX_index.json`, at the moment of the installation, inside a file named `installed.json`. This extract turns out useful if the original `package_XXX_index.json` is lost or removed to keep the platform functional.
On the other hand, if the original `package_XXX_index.json` is modified the information kept in the
`installed.json` may be outdated and should be replaced by the upstream index: this is the reason why …

Fix bogus "wrong file size" error in some rare cases

---

arduino/discovery/discovery.go
test/test_board.py

Better handling of discovery startup in case the discovery is not properly installed.
The CLI crashes, see arduino/arduino-cli#1669  for details
The CLI does not crash anymore
No

Fix regression: do not crash on `board list` if a discovery is not properly installed

---

.github/workflows/test-go-task.yml

Versions of [the `codecov/codecov-action` GitHub Actions action](https://github.com/codecov/codecov-action) prior to 1.0.6 required the use of a token provided by Codecov in order to upload coverage data to Codecov. This token was stored in a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the Arduino CLI repository and used in the test …

[skip changelog] Enable Codecov comments on PRs from forks

---

test/test_lib.py

Fix integration tests using library `AzureIoTProtocol_MQTT` that has been removed from the registry
Integration tests fails
Integration tests succeed
No

[skip-changelog] Fixed integration tests using a library that is no more available

---

arduino/cores/packagemanager/download.go

Bug fix
[`github.com/arduino/arduino-cli/i18n.Tr`](https://github.com/arduino/arduino-cli/blob/c7163b776f756a0ca25e9bebf872eeb1e7bf404a/i18n/i18n.go#L41-L45) provides [a `fmt.Printf`-style interface](https://pkg.go.dev/fmt#hdr-Printing), where the first argument may serve as a template filled by subsequent arguments according to its format verbs.
The call modified in this PR contains a subsequent argument, but no verb in the format string to use it. This generates some cryptic content in the error message.
For …

[skip changelog] Remove spurious argument from error message

---

arduino/cores/packagemanager/loader.go
internal/integrationtest/core/core_list_test.go
internal/integrationtest/core/testdata/issue_1823/DxCore-dev/megaavr/README.md
internal/integrationtest/core/testdata/issue_1823/DxCore-dev/megaavr/boards.txt
internal/integrationtest/core/testdata/issue_1823/DxCore-dev/megaavr/platform.txt
internal/integrationtest/core/testdata/issue_1823/DxCore-dev/megaavr/programmers.txt

Fix #1823 
See #1823 for reference. CLI crash.
The `version` property is handled correctly.
No

Expand property references in `version` property of `platform.txt`

---

client_example/main.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
---

delete minor unreachable code caused by log.Fatal

---

arduino/cores/packagemanager/package_manager_test.go
arduino/discovery/discovery.go
arduino/discovery/discovery_client/go.mod
arduino/discovery/discovery_client/main.go
arduino/discovery/discoverymanager/discoverymanager.go
cli/arguments/completion.go
cli/arguments/port.go
cli/board/list.go
commands/board/list.go
commands/daemon/daemon.go

Fix the functionality of the discovery manager, making it more robust when `arduino-cli` is running as a daemon with many concurrent calls.
The behavior is undefined, the most frequent issues are:
- when a `BoardListWatch` is disconnected and reconnected it will not see new events
- running `BoardList` multiple times on the same instance may cause issues/crashes
It should be more resistant to the above cases.
**Does this PR introduce a breaking change, and is [titled …

Fix gRPC `BoardList*` methods concurrency issues

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
docs/CONTRIBUTING.md
docs/FAQ.md
docs/command-line-completion.md
docs/integration-options.md
docs/library-specification.md
docs/sketch-specification.md

Documentation fix
Some of the links in the documentation are broken (in ways or forms that are not covered by the automated link check).
Some of the links in the documentation rely on redirects which could break in the future.
All links in documentation reach their intended target, and reach it directly.
No breaking change.
Fixes https://github.com/arduino/arduino-cli/issues/1832

[skip changelog] Update broken or outdated links

---

i18n/data/README.md

**Arduino CLI** has been translated to [12 languages](https://explore.transifex.com/arduino-1/arduino-cli/).
The [localization](https://wikipedia.org/wiki/Language_localisation) process follows the following steps:
1. An English language source string is defined in the **Arduino CLI** codebase
2. The source string is [pushed](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/i18n-nightly-push.yaml) to [**Transifex**](https://explore.transifex.com/arduino-1/arduino-cl …

[skip changelog] Add readme for localization data

---

cli/compile/compile.go

The key name is hereby corrected.
Bug fix
The `--dump-profile` flag causes Arduino CLI to print the board and sketch dependencies of that compilation as a YAML document. This could be copied into a ["sketch project file"](https://arduino.github.io/arduino-cli/dev/sketch-project-file/) for later use as a ["build profile"](https://arduino.github.io/arduino-cli/dev/sketch-project-file/#build-profiles) specified via the `--profile` flag.
A typo in the `profiles` key name caused the generated "build profile" entry to not …

Correct key name in `arduino-cli compile --dump-profile` output

---

commands/daemon/daemon.go
internal/integrationtest/daemon/daemon_compile_test.go

Fix the error messages from `compile`, they were not correctly encoded in the response.
The message `grpc: error while marshaling: proto: Marshal called with nil` appeared instead of the real error message. See #1812 for details.
The correct error message is outputted.
No
Fix #1812

Fixed cryptic error messages returned from Compile

---

test/test_compile_part_1.py
test/test_compile_part_3.py

Fix CI tests until we replace the removed library `Arduino_TensorflowLite` with another precompiled example.
Test fails
Test passes
No

[skip-changelog] Temporarily disable 'precompiled-lib' tests

---

arduino/utils/stream.go
commands/daemon/daemon.go
commands/daemon/debug.go
commands/daemon/stream.go
docs/UPGRADING.md

Simplifies the gRPC streams helpers: the `Close` method on the `WriteCloser` object, returned by the function `FeedStreamTo`, is now synchronized with the other side of the "pipe" and automatically waits for the messages to be flushed., there is no more need to explicitly wait.
In theory, there should be no change in behavior.
In practice, this PR may solve some very well hidden bugs.
**Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CON …

[breaking] Simplified gRPC streams helpers

---

arduino/cores/board.go
arduino/cores/packagemanager/loader.go
arduino/cores/packagemanager/loader_test.go
commands/monitor/monitor.go
commands/monitor/settings.go
docs/platform-specification.md

Adds the possibility for board developers to override the default port settings when the monitor is opened.
This is useful in particular for the `serial` port settings of `dtr` and `rts` since the Arduino IDE 1.8.x allowed the following `board.txt` properties:
```
BOARD_ID.serial.disableRTS=true
BOARD_ID.serial.disableDTR=true
```
To generalize the above to the Pluggable Monitor a new way to override specific port settings has been added:
```
BOARD_ID.monitor_port.PROTOCOL.SETTING_NAME=SETTING_VALUE
```
where:
* `BOARD_ID` is the board identifier
* `PROTOCOL` is …

Extended Pluggable Monitor specification to allow board-specific settings to be applied

---

executils/process.go
internal/integrationtest/arduino-cli.go

Should fix this problem: https://github.com/arduino/arduino-cli/runs/8158553770?check_suite_focus=true#step:6:1752 
sometimes the output of the subprocess doesn't reach the output buffer:
```
=== RUN   TestCompletionNoArgs
>>> Running: /home/runner/work/arduino-cli/arduino-cli/arduino-cli completion
<<< Run completed (err = exit status 1)
completion_test.go:32: 
Error Trace:	/home/runner/work/arduino-cli/arduino-cli/internal/integrationtest/completion/completion_test.go:32
Error:      	"" does not contain "Error: accepts 1 …
```

[skip-changelog] Proper handling of stdout/stderr copy in subprocess

---

legacy/builder/hardware_loader.go
legacy/builder/test/tools_loader_test.go

Fix a weird compile regression.
The `runtime.tools.PACKAGER-TOOL-VERSION.*` variables are not populated (unless they are specified as a platform dependcy in the package_xxx_index.json and that index file is present).
The above bug is fixed.
No

Fixed `compile` regression

---

internal/integrationtest/arduino-cli.go

The testsuite is now able to detect arduino-cli panics when running integration tests.
The following test
```go
_, _, err = cli.Run("lib", "upgrade", "Servo")
require.Error(t, err)
```
may pass if `arduino-cli` panics, but this is wrong, `arduino-cli` should always return gracefully with a polite error message.
The above test fails:
```
arduino-cli.go:165: 
Error Trace:    /home/megabug/Workspace/arduino-cli/internal/integrationtest/lib/arduino-cli.go:165 …
```

testsuite: arduino-cli should never panic during tests

---

internal/integrationtest/arduino-cli.go

CopySketch is a function that copies a sketch present in the "testdata" folder and copies it into the testing environment.
Infrastructure Enhancement
CopySketch is a function that copies a sketch present in the `testdata` folder into the testing environment and returns its path.
No
---

[skip-changelog] Add CopySketch to the testsuite library

---

internal/integrationtest/arduino-cli.go
internal/integrationtest/compile/compile_part_1_test.go
internal/integrationtest/daemon/daemon_test.go

Infrastructure Enhancement
By default, the working directory is the one containing the test.go file. This causes problems when executing commands that have to create files specifically in the working directory, because they either must be deleted manually or the user has to be aware of it and defer a deleting instruction. Furthermore, it messes with tests using relative paths. Setting the environment directory as the CLI's WorkingDir prevents the above mentioned issues from occurring. …

[skip-changelog] Set test environment directory as CLI WorkingDir

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/release-go-task.yml
DistTasks.yml

Infrastructure Enhancement
[Release-go-task](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/release-go-task.yml), [publish-go-nightly-task](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/publish-go-nightly-task.yml) and [publish-go-tester-task](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/publish-go-tester-task.yml) are currently using `task dist:all` to build and create the release artifacts. This is done by calling the tasks related to each OS consecutively. As a …

[skip-changelog] Use a matrix to create parallel builds for each OS

---

.github/PULL_REQUEST_TEMPLATE.md

This repository uses a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) in order to provide a standardized structure for pull request messages.
There are several problems with the markup used in the template …

[skip changelog] Fix pull request template markup

---

arduino/cores/cores.go
arduino/cores/packagemanager/loader.go
arduino/cores/packagemanager/package_manager_test.go
commands/board/listall.go
internal/integrationtest/board/board_list_test.go

The ordering of the boards returned by `board listall` is now the same as the order of definition in the `boards.txt` of the platform.
The ordering is undefined (random):
```
$ arduino-cli board listall arduino:avr --format json | jq '.boards[] | .name'
"Arduino Industrial 101"
"Arduino Esplora"
"Arduino Robot Motor"
"Arduino Nano"
"Arduino Yún"
"Arduino Mini"
"Arduino Uno WiFi"
"Arduino Duemilanove or Diecimila"
"Arduino Uno Mini"
"Adafruit Circuit Playground"
"Arduino Gemma"
"LilyPad Arduino"
"Arduino Mega ADK"
"Arduino Leonardo ETH"
"Arduino Micro"
"Arduino Robot Control"
"Arduino Pro or Pro Mini"
"Linino One"
"Arduino Ethernet"
"Arduino Mega or Mega 2560"
"Arduino Fio"
"Arduino BT" …
```

Let `board listall` return boards sorted with the same order as in the original `boards.txt`

---

Taskfile.yml
internal/integrationtest/upgrade/upgrade_test.go

A workaround to fix the integration test.
go-lang tests in each package are run in parallel (instead the tests inside each package are run sequentially). This is not good for tests in `integrationtest` because these share the download directory to save bandwidth.
The tests are run sequentially using the `-p 1` flag
No
Maybe a better long term solution could be to move all integration tests in the same "package" under `internal/intergationtest`. @MatteoPologruto @umbynos

Fix integration test intermittent failure due to download/file in use

---

arduino/libraries/libraries.go
arduino/libraries/librariesresolver/cpp.go
arduino/libraries/librariesresolver/cpp_test.go
arduino/libraries/loader.go
docs/UPGRADING.md
internal/integrationtest/lib/lib_test.go
legacy/builder/create_cmake_rule.go
legacy/builder/phases/libraries_builder.go
legacy/builder/types/types.go

Bug fix.
Each Arduino library has a name, which is used as its sole identifier by the user in `arduino-cli lib` commands, and by Arduino CLI when referring to the library in messages displayed to the user.
The name is defined by:
- ["1.5 format"](https://arduino.github.io/arduino-cli/dev/library-specification/#15-library-format-rev-22) libraries: `name` field in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format)
- ["1.0 format" (AKA "legacy")](https://arduino.github.io/arduino-cli/dev/library-specification/#old-library-format-pre-15) libraries: installation folder name
The name is …

[skip changelog] Use appropriate name for field that stores library folder name

---

cli/config/add.go
cli/config/set.go
test/test_config.py

Fixes #1437.
This change ensures that duplicate values are not introduced into configuration, such as for `board_manager.additional_urls`
The following will result in two identical entries in the config:
```bash
arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
```
Entries that accept multiple values are ensured to be unique.  Care was taken to …

Prevent duplicate entries in board_manager.additional_urls

---

internal/integrationtest/compile/compile_part_1_test.go
internal/integrationtest/compile/compile_part_2_test.go
internal/integrationtest/debug/debug_test.go
internal/integrationtest/subtests.go

A lot of tests (especially the compile ones) are doing something like:
* `core install arduino:avr` (slow)
* perform the test (very quick)
There are a lot of tests that take most part of the time just installing the same platform again and again.
All the tests that require the same platform installed as a prerequisite are grouped together in a bigger test that runs each of them as a sub-test.
This change requires a bit more attention on the cleanup of the sub-tests since the leftovers of one test can be retrieved in a later test.
No

[skip-changelog] Reuse already installed platforms to speed up integration tests

---

.github/workflows/test-go-task.yml

The code coverage data generated by running the unit tests in the "Test Go" GitHub Actions workflow is uploaded to Codecov.
This upload is prone to occasional transient failures. With the previous workflow configuration this caused a failure of the Linux test run job. Contributors would need to review the logs to understand that these …

[skip changelog] Move upload of coverage data to dedicated job in test workflow

---

docs/platform-specification.md

Add missing docs for `recipe.hooks.prebuild.NUMBER.pattern` build hook.
Fix #1910 
No changes.
No changes.
No

[skip-changelog] Added missing docs for 'recipe.hooks.prebuild.NUMBER.pattern'

---

internal/integrationtest/arduino-cli.go

Infrastructure imperfection fix
Sketches are copied into `SketchbookDir`. This is not causing problems at the moment because, the tests that implement the `CopySketch()` function, use absolute paths. Nevertheless, this is incorrect and could cause problems when migrating other tests.
The original copy sketch function written in [conftest.py](https://github.com/arduino/arduino-cli/blob/master/test/conftest.py#L228) copies sketches into the testsuite's working directory. Changing the copy sketch function present in the golang testsuite to match the original one, should prevent errors …

[skip-changelog] Fix copySketch testsuite function

---

.github/workflows/check-certificates.yml
.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml
.prettierignore
Taskfile.yml
docs/installation.md
installer/cli.wixproj
installer/cli.wxs
installer/ui.wxs

build msi installer for windows
should solve #705 
we are able to build an msi installer for windows
nop
I already added the required secrets to the repo.
The installer is able to install the Arduino CLI to a specified path (by default in `C:\Program Files\Arduino CLI`) also being able to put that as PATH env variable. Upgrades …

Add windows `.msi` installer to the CI

---

.github/workflows/check-certificates.yml

The check-certificates workflow is failing not being able to decode the secret
The workflow should be fixed
no

[skip-changelog] fix `check-certificates.yml` failing

---

internal/integrationtest/http_server.go

Added a function that spawns a server that responds with a given error code to requests. It will be useful during the migration of integration tests like `core_test` and `upload_test`.
No

[skip-changelog] Add function to spawn a server that responds with error code

---

docs/installation.md

As a newcomer, this made me assume ARMv6 is not supported so I searched the issues, found https://github.com/arduino/arduino-cli/issues/340, which suggested building from source so I did, only to discover an ARMv6 binary in the release files.
As for the table layout, it's not ideal. It would also make sense to have this in another column.

[skip-changelog] Add ARMv6 download links to install docs

---

commands/lib/upgrade.go
internal/integrationtest/lib/lib_test.go

Bug fix on an existing command.
Current behaviour is explained in issue #1856
Calling `lib upgrade` now will also install newly added dependencies to libraries being updated. 
This fixes also the gRPC interface commands `LibraryUpgradeAll` and `LibraryUpgrade`.
Nope.
Fixes #1856.
This PR depends on #1934.

Fix lib upgrade command not installing new libraries dependencies

---

.github/workflows/check-certificates.yml
.github/workflows/check-go-dependencies-task.yml
.github/workflows/check-go-task.yml
.github/workflows/check-protobuf-task.yml
.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
.github/workflows/publish-go-nightly-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/release-go-task.yml
.github/workflows/sync-labels.yml
.github/workflows/test-go-integration-task.yml
.github/workflows/test-go-task.yml

GitHub Actions provides the capability for workflow authors to use the capabilities of the GitHub Actions ToolKit package directly in the `run` keys of workflows via "[workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)". One such command is `set-output`, which allows data to be passed out …

[skip changelog] Migrate workflows from deprecated `set-output` commands

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/release-go-task.yml
Taskfile.yml

Adds a new task and changes the tester, nightly and stable build release processes.
Currently there is no easy way for developers to download only `.proto` files to work on projects that depend on them. 
Those files are necessary to generate other languages files to handle gRPC communication.
The only way as of now is to download the whole `arduino-cli` repo and copy the files.
A new command has been added to zip all the `.proto` files and save them in `dist`, the task is called `protoc:collect`.
The output zip will be called `arduino-cli_<version>_proto.zip`, `<version>` as defined …

Add task to collect proto files and add steps to release them with tester, nightly and stable builds

---

cli/config/validate.go
docs/configuration.md

Allows `locale` key to be used in config.
```
$ arduino-cli config set locale de
Settings key doesn't exist
$
```
The setting is correctly applied:
```
$ arduino-cli config set locale de
$
```
No
Fix #1928

Allow `locale` key to be used in `config ...` commands.

---

docs/sketch-specification.md

Arduino IDE allows opening searches in Library Manager and Boards Manager by clicking a link with a special format in a comment of the sketch.
During the initial implementation in Arduino IDE 1.x (https://github.com/arduino/Arduino/commit/b99ab40ba29cdc45d0ff239295b351ebd990b65c), support for setting the "Type" filter via the URI in addition to specifying search keywords was attempted and claimed to work, …

[skip changelog] Document filter setting capability of Library/Boards Manager links

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml
Taskfile.yml

An additional operation was recently added to the GitHub Actions workflows that produce builds of Arduino CLI: the generation of [protocol buffer](https://developers.google.com/protocol-buffers) archive files to publish
along with the builds (https://github.com/arduino/arduino-cli/pull/1931).
Some bugs were introduced at that time which caused …

[skip changelog] Fix bugs related to protobuf archive generation

---

docs/integration-options.md
docs/library-specification.md
docs/package_index_json-specification.md
docs/platform-specification.md

Documentation fix/update
The Arduino Pro IDE application was mentioned several places throughout the documentation. That project became Arduino IDE 2.x 1.5 years ago while still in the alpha development phase.
All users of that application will now know it by the name "Arduino IDE 2.x".
The Arduino Pro IDE page on the Arduino website has been removed, which broke the link and caused the link check workflow to fail.
Update all …

[skip changelog] Update all mentions of Arduino Pro IDE

---

internal/integrationtest/lib/lib_test.go

Fixed an integration test:
```
<<< Run completed (err = <nil>)
json.go:90: 
Error Trace:	/home/runner/work/arduino-cli/arduino-cli/internal/integrationtest/lib/json.go:90
/home/runner/work/arduino-cli/arduino-cli/internal/integrationtest/lib/json.go:144
/home/runner/work/arduino-cli/arduino-cli/internal/integrationtest/lib/lib_test.go:100
Error:      	json data length does not match: expected=1, actual=3
Test:       	TestLibInstallMultipleSameLibrary
Messages:   	A duplicate library install has been detected
```
https://github.com/arduino/arduino-cli/actions/runs/3410728596/jobs/56740 …

Fixed integration test `TestLibInstallMultipleSameLibrary`

---

.licenses/go/github.com/arduino/go-properties-orderedmap.dep.yml
arduino/discovery/discovery_client/go.mod
arduino/discovery/discovery_client/go.sum
arduino/libraries/libraries_test.go
arduino/libraries/testdata/LibWithNonUTF8Properties/library.properties
client_example/go.sum
docsgen/go.mod
docsgen/go.sum
go.mod
go.sum

Allow ISO8859-1 (non UTF-8) `.properties` files.

---

arduino/cores/board.go

This is a tentative fix for #1970 
See #1970 
Should solve the nil pointer exception reported here: https://github.com/arduino/arduino-cli/issues/1970#issuecomment-1309533962
BTW I found no way to reproduce it, so testing is needed.
No

Fix concurrency problem in `Board.buildConfigOptionsStructures`

---

cli/lib/search.go
commands/lib/search.go
commands/lib/search_test.go

When searching for libraries put the exact match as the first result.
```
$ arduino-cli lib search FlashStorage --names
Sto scaricando l'indice: library_index.tar.bz2 downloaded                                                                                                                                                   
Nome: "BlynkEthernet_Manager"
Nome: "Blynk_Esp8266AT_WM"
Nome: "Blynk_WiFiNINA_WM"
Nome: "DoubleResetDetector_Generic"
Nome: "DueFlashStorage"
Nome: "ESP_AT_WM_Lite"
Nome: "ESP_AT_WiFiManager"
Nome: "Ethernet_Manager"
Nome: "Ethernet_Manager_STM32"
Nome: …
```

`lib search` returns exact match as the first result.

---

arduino/cores/cores.go
internal/integrationtest/compile_2/compile_propeties_test.go
internal/integrationtest/testdata/bare_minimum/bare_minimum.ino
internal/integrationtest/testdata/foo/avr/boards.txt
internal/integrationtest/testdata/foo/avr/platform.txt

Set `runtime.hardware.path` property during upload.
`runtime.hardware.path` property is empty during upload (it is only set for compile).
`runtime.hardware.path` property is set during upload too.
No
Fix #1971

Set `runtime.hardware.path` property during upload

---

cli/output/rpc_progress.go

Fix the progress bar.
In an operation with multiple downloads (for example a `core install` with many tools), the progress bar is displayed only for the first download, the remainder just displays `tool-X downloaded.`
The progress bar is displayed for all downloads.
No
This is a regression from #1875

Fix download progress bar (not always displayed)

---

test/test_lib.py

Fix:
```
=================================== FAILURES ===================================
_________________________________ test_search __________________________________
run_command = <function run_command.<locals>._run at 0x7f37384a3c10>
def test_search(run_command):
assert run_command(["update"])
result = run_command(["lib", "search", "--names"])
assert result.ok
lines = [l.strip() for l in result.stdout.strip().splitlines()]
assert "Downloading index: library_index.tar.bz2 downloaded" in lines
libs = [l[6:].strip('"') for l in lines if "Name:" in l]
expected = {"WiFi101", …
```

Fixed integration test in `test_lib.py`

---

commands/board/list.go
commands/board/list_test.go
inventory/inventory.go

* calls to builder-api are cached 24h
* do not error on `board list` if the network is not available (fix #1963)
`board list` terminate with an error if the network is not available and the board is not "known" (there are no platform installed for that board).
The `board list` command always complete even if the network is not available
No

Improve `board list` detection via cloud API

---

commands/upload/upload.go
internal/integrationtest/upload_mock/upload_mock_test.go

Slightly changes an output message in upload
The "no port found" upload message was:
```
No upload port found, using address:"/dev/ttyACM0"  protocol:"serial"  as fallback
```
(notice that the message contains double spaces that are produced pseudo-randomly when a structure is printed using the default `String()` implementation)
Just print the port address:
```
No upload port found, using /dev/ttyACM0 as fallback
```
This is more user-friendly, and the message is 100% reproducible for testing purposes.
No

Small change in upload message

---

arduino/libraries/librariesmanager/install.go
arduino/libraries/librariesmanager/librariesmanager.go
commands/lib/install.go
docs/UPGRADING.md
internal/integrationtest/compile_1/compile_test.go
internal/integrationtest/lib/lib_test.go

Fix double install detection running `lib install` with `--git-url` or `--zip-path` flags.
A double-install of a library may be the outcome of `lib install` command: it happens when a library is installed twice under two different subdirectories of the sketchbook's `libraries` folder.
See https://github.com/arduino/arduino-cli/issues/1871 for more details and examples.
The multiple install problem should be fixed.
Yes

[breaking] Fixed detection of double-install using `lib install` with `--git-url` or `--zip-path`

---

cli/board/details.go
internal/integrationtest/board/board_test.go

CLI imperfection fix
Running `board details -b` produces unnecessary empty lines between each `Required tool` entry. 
```
Required tool:             arduino:arm-none-eabi-gcc                                         7-2017q4
Required tool:             arduino:bossac                                                    1.7.0-arduino3
Required tool:             arduino:openocd                                                   0.10.0-arduino7
Required tool:             arduino:CMSIS                                                     4.5.0
Required tool:             arduino:CMSIS-Atmel …
```

[skip-changelog] Eliminate empty lines produced by `board details -b`

---

internal/integrationtest/testdata/installed.json

`installed.json` is out of date. This causes [TestCoreInstallCreatesInstalledJson](https://github.com/arduino/arduino-cli/blob/master/internal/integrationtest/core/core_test.go#L976).
Adding and modifying some entries solves the issue. However, this is just a temporary workaround. In the future, a better solution would be to modify the test in some way.
No

[skip-changelog]Update `installed.json` with newer entries

---

internal/integrationtest/lib/lib_test.go
test/test_lib.py

The first 12 tests that were previously present in `test_lib.py` have been rewritten in `lib_test.go`, without changing their original purpose.
No

[skip-changelog] Migrate twelve tests from `test_lib.py` to `lib_test.go`

---

.github/workflows/publish-go-tester-task.yml

Infrastructure imperfection fix
[publish-go-tester-task](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/publish-go-tester-task.yml) runs when a tag is pushed. Since the tag has priority when [version](https://github.com/arduino/arduino-cli/blob/master/Taskfile.yml#L378) is defined, the workflow fails because it does not find any build named `test-XXX-git-snapshot` when calculating the checksums. It recently happened here: https://github.com/arduino/arduino-cli/actions/runs/3480562942/jobs/5820576240#step:3:16
During run determination, the workflow checks if …

[skip-changelog] Avoid running publish-go-tester-task if tag is set

---

.github/workflows/check-certificates.yml

The "Check Certificates" GitHub Actions workflow uses [**OpenSSL**](https://www.openssl.org/) to check for problems with the project's signing certificates.
Certificates exported to [PKS #12](https://en.wikipedia.org/wiki/PKCS_12) archive files using older tools may have been encrypted using the ["RC2-40-CBC" …

[skip changelog] Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS #12

---

.github/workflows/test-go-integration-task.yml

It looks like the upgraded runners from Github did not have python 3.9.6.
https://github.com/actions/setup-python/issues/561#issuecomment-1340657956
https://github.com/actions/setup-python/issues/544
Let's try to let the action choose the latest minor available.
No

Let the integration-test workflows to choose the latest minor version of python

---

arduino/resources/resources_test.go
internal/integrationtest/core/core_test.go

Some tests are failing because urls are outdated after PR #2011  
Updating the urls prevents the tests from failing.
No

[skip-changelog] Update urls to prevent tests from failing

---

.github/workflows/test-go-task.yml

For efficiency, the "Test Go" GitHub Actions workflow splits the test suite into multiple jobs which run in parallel. This is done via a "[job matrix](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)".
[By default GitHub Actions uses a "fail fast" behavior for job …

Disable "fail fast" feature in "Test Go" workflow

---

commands/lib/list.go
internal/integrationtest/lib/lib_test.go

Platform bundled libraries are not shown when `-b` flag is used. It is necessary to set the `--all` flag with it.
```
C:\Users\m.pologruto>arduino-cli lib list -b esp32:esp32:esp32 ArduinoOTA
No libraries installed.
C:\Users\m.pologruto>arduino-cli lib list -b esp32:esp32:esp32 ArduinoOTA --all
Name       Installed       Available     Location          Description
ArduinoOTA 1.0             1.0.8         esp32:esp32@1.0.6 Enables Over The Air upgrades, via wi...
```
To show the bundled libraries, the `--all` flag is automatically set when the `-b` flag is used.
``` …
```

Include platform bundled libs when `-b` flag is used

---

.github/workflows/test-go-task.yml

The CI pipeline is changed in order to prevent empty Codecov coverage reports. It follows [the workaround in the Codecov related issue](https://github.com/codecov/codecov-action/issues/844#issuecomment-1367603838)
Commit related Codecov reports are empty, see example screenshot:
Coverage reports are shown correctly by Codecov

chore: prevent empty codecov report

---

README.md

Set the Codecov badge url to point the `master` branch instead of `main`, so that the badge image display a valid coverage percentage.
The coverage percentage is "unknown" in the badge
Correct information is shown
No

[skip-changelog] chore: fix codecov badge url

---

commands/board/listall.go
internal/integrationtest/board/board_test.go

Makes the `board listall` command output order consistent across formats. The list items are ordered by the package and platforms names they belong too, other than the board names themselves.
The plain text format remains an exception to this as it's sorted alphabetically by board name. 
In output formats other than plain text the board list is inconsistently ordered: while the boards within a single package/platform are ordered alphabetically they might appear before or after the ones of an other package/platform.
The list is ordered by package, platform and board names.
No
Fixes …

fix: consistent boards list ordering

---

arduino/cores/packagemanager/download.go
arduino/cores/packagemanager/profiles.go
arduino/httpclient/httpclient.go
arduino/resources/download.go
arduino/resources/helpers_test.go
arduino/resources/index.go
arduino/resources/resources_test.go
commands/daemon/daemon.go
commands/instances.go
commands/lib/download.go
commands/lib/install.go
commands/lib/upgrade.go
internal/cli/lib/download.go
internal/cli/lib/install.go
internal/integrationtest/lib/lib_test.go

Three different query parameters have been added to the urls generated by `lib` commands like `lib install` and `lib upgrade`. The query parameters are:
- `install`: which is selected when a library is installed through `lib install`;
- `upgrade`: which is selected when a library is upgraded through `lib upgrade`;
- `depends`: which is selected when a library dependency is installed.
No

[skip-changelog] Add query parameters to urls generated by lib commands

---

commands/daemon/daemon.go
commands/lib/download.go
commands/lib/install.go
commands/lib/upgrade.go
internal/cli/lib/download.go
internal/cli/lib/install.go
internal/integrationtest/lib/lib_test.go

Follow up to PR #2034.
`queryParameter` can be introduced for the first time inside `commands.lib.install.LibraryInstall`. For this reason, every prior declaration has been removed, avoiding breaking changes.
No

[skip-changelog] Remove `queryParameter` where it is not needed

---

arduino/libraries/librariesmanager/install.go
arduino/libraries/librariesmanager/librariesmanager.go
arduino/libraries/librariesmanager/librariesmanager_test.go
internal/integrationtest/daemon/daemon_test.go

Requests](https://github.com/arduino/arduino-cli/pulls)
Rescan libraries before installing new ones. Upon each installation request the libraries folders 
are rescanned.
The installed libraries are scanned only at initialization time. If other are added 
while the program runs, especially in deamon mode, these are not known to the running instance.
This causes the execution to fail improperly if different installation attempts have an 
overlap/conflict in dependencies.
The installed libraries are reloaded before every installation request, so the logic has the updated 
status.
Fixes …

fix: scan libraries on install

---

docs/UPGRADING.md
internal/cli/daemon/daemon.go

Code security improvement
It is currently possible to use `--ip` to set a custom ip for listening to gRPC request.
The `--ip` flag is removed and the default value is set to `127.0.0.1`.
Yes

[breaking] Remove `ip` flag from daemon command

---

commands/sketch/new.go
commands/sketch/new_test.go
docs/UPGRADING.md
internal/cli/sketch/new.go
internal/integrationtest/sketch/sketch_test.go

It alignes the validation of sketch names to the documentation
https://arduino.github.io/arduino-cli/dev/sketch-specification/#sketch-folders-and-files
Sketch creation request that don't respect the validation rules are rejected
No validation is performed on the sketch name
Sketch names that don't respect the required pattern, consisting in alphanumeric characters, dots, underscores and dashes, or that are longer 
than 63 characters cause the request to be rejected.
Yes! Freeform sketch names that were in use before will not be compatible anymore.
Fixes #2043

[breaking] fix: validate sketch name

---

legacy/builder/ctags_runner.go

ctags can fail, for example if TMPDIR is unset. It aids debugging to show the stderr with -v if that's the case

Show ctags errors when verbose

---

internal/cli/version/version.go

The command `arduino-cli version` always shows if there is an available update, even if `updater.enable_notification` is set to `false`.
`arduino-cli version` no longer ignores the flag `updater.enable_notification`.
No.
To test this change, I manually modified the `ldflags` to build an outdated version of the CLI, then set `updater.enable_notification` to `false`.
```
PS C:\Users\m.pologruto\Desktop\Arduino\arduino-cli> .\arduino-cli config dump                                 
board_manager:
additional_urls: []
daemon:
port: "50051"
directories:
data: …
```

Do not show available updates with `version` if `updater.enable_notification=false`

---

commands/daemon/daemon.go

gRPC code imperfection fix
Some gRPC commands like `UpdateLibrariesIndex` stream an empty object after a successful execution.
The empty object has been removed.
No
Close #2046

[skip-changelog] Remove empty object from the output of grpc commands

---

commands/sketch/new.go
commands/sketch/new_test.go
docs/UPGRADING.md

Follow up on https://github.com/arduino/arduino-cli/pull/2051. Fixing the error messages returned when validating the sketch name
Errors are difficult to understand
Errors are more human readable

fix: sketch name validation error messages

---

internal/integrationtest/core/core_test.go
internal/integrationtest/testdata/installed.json

Fixes failing tests due to outdated expected files

[skip-changelog] test: updated expected cores file

---

internal/integrationtest/upload/upload_test.go

`TestUploadWithInputDirContainingMultipleBinaries` fails because the error output was slightly changed in PR #2003 and no longer contains the message `Error during upload`.
The test works correctly:
```
PS C:\Users\m.pologruto\Desktop\Arduino\arduino-cli> go test github.com/arduino/arduino-cli/internal/integrationtest/upload -run TestUploadWithInputDirContainingMultipleBinaries
ok      github.com/arduino/arduino-cli/internal/integrationtest/upload  41.566s
```
No
No

[skip-changelog] Fix upload test according to CLI output refactoring

---

internal/cli/lib/search.go

Executing `lib search` always downloads and updates `library_index.json`.
A timeout has been introduced to avoid updating the index every time `lib search` is executed.
No
This is a duplicate of #1789. Since the original author did not make any recent update, I'm simply rebasing his commits and applying the suggestions. Once this PR is merged, the original can be closed.
Close #1789

[skip-changelog] Do not force `update index` every time `lib search` is executed

---

commands/lib/install.go
internal/cli/lib/install.go
internal/integrationtest/lib/lib_test.go

Adds `--install-in-builtin-dir` flag to `lib install` command.
When the `--install-in-builtin-dir` flag is set, the libraries are installed in the directory specified by the `directories.builtin.libraries` configuration setting:
```yaml
directories:
builtin.libraries: /home/user/.....
```
The libraries installed inside the builtin directory are not automatically upgraded via `lib upgrade`. They can be upgraded anyway, by forcing an install of an already installed library.
No

Added `--install-in-builtin-dir` flag to `lib install` command

---

arduino/cores/packagemanager/install_uninstall.go
commands/instances.go
docs/UPGRADING.md
internal/integrationtest/core/core_test.go

`post_install` scripts are not handled after the tool installation.
`post_install` scripts for tools are handled the same way the ones related to platforms are.
No

[breaking] Add post install script support for tools

---

rpc/cc/arduino/cli/commands/v1/commands.proto

Documentation fix
The ["gPRC Reference" section](https://arduino.github.io/arduino-cli/dev/rpc/commands/) of the documentation website is automatically generated from the code and comments in the project's Protocol Buffers files. The documentation is automatically structured according to the structure of the Protocol Buffers code using heading levels, and the …

[skip changelog] Remove comment that breaks gRPC documentation structure

---

internal/cli/board/search.go

Documentation imperfection fix
`board search` and `board listall` have the same `--help` description. The first one is wrong.
```
PS C:\Users\m.pologruto\Desktop\Arduino\arduino-cli> arduino-cli board --help
Available Commands:
attach      Attaches a sketch to a board.
details     Print details about a board.
list        List connected boards.
listall     List all known boards and their corresponding FQBN.
search      List all known boards and their corresponding FQBN.
```
`board search --help` description has been changed to correctly reflect the command's function.
```
PS …
```

[skip-changelog] Modify `board search --help` description to correctly explain the command's function

---

internal/integrationtest/core/core_test.go
internal/integrationtest/testdata/installed.json

Requests](https://github.com/arduino/arduino-cli/pulls)
Fix failing integration test after index update

[skip-changelog] test: updated tests after index changes

---

commands/compile/compile.go
internal/integrationtest/compile_3/compile_test.go

It is not possible to build a sketch multiple times when the `--build-path` is the same and is inside the sketch directory. The following error is thrown:
```
Error during build: unable to read contents of the source item: open <mydir>/build-mega/compile_commands.json:
no such file or directory
```
It happens because the CLI treats the build directory as part of the sketch itself, therefore it fails when the content of the directory gets deleted/overwritten.
If the `--build-path` target already exists and is inside the sketch directory, it is ignored when the …

[skip-changelog] Handle repeated builds of a sketch when `--build-path` target is in the sketch directory

---

commands/compile/compile.go

There is currently no support for `hooks.savehex.presavehex` and `hooks.savehex.postsavehex`.
`hooks.savehex.presavehex` and `hooks.savehex.postsavehex` run if `exportBinaries` if set to `true`.
No

[skip-changelog] Add hooks `hooks.savehex.presavehex` and `hooks.savehex.postsavehex`

---

arduino/cores/packagemanager/download.go
arduino/cores/packagemanager/install_uninstall.go
internal/integrationtest/core/core_test.go
internal/integrationtest/testdata/test_index.json

No instructions are provided when a tool download/install fails because it is not available for the OS in use.
The error message has been enhanced by adding the `email` field of the package that provides the tool.
No

[skip-changelog] Add remediation path when tool is not available for an OS

---

arduino/cores/packagemanager/install_uninstall.go

Strings in the error message are unindexed and cannot be translated.
Strings in the error message are correctly indexed.
No

[skip-changelog] Fix string indexing in `tool not available for the current os` error message

---

internal/cli/daemon/daemon.go

When running the daemon in text mode a line with a parable JSON is printed together with the text. This will allow the Arduino IDE to pick this up when running in text-mode with `-v` logging and `--debug` enabled.
```
$ arduino-cli daemon -v --debug
INFO[0000] Using config file: /home/megabug/.arduino15/arduino-cli.yaml 
INFO[0000] arduino-cli version 0.0.0-git                
INFO[0000] Executing `arduino-cli daemon`               
Deamon è ora in ascolto su 127.0.0.1:50051
```
A line with a machine-readable JSON is added to the output:
```
$ arduino-cli daemon -v --debug
INFO[0000] …
```

Added machine-readable `IP:PORT` in text-mode daemon

---

internal/integrationtest/compile_3/compile_test.go
internal/integrationtest/compile_3/testdata/blink_with_wrong_cpp/blink_with_wrong_cpp.ino
internal/integrationtest/compile_3/testdata/blink_with_wrong_cpp/wrong.cpp
legacy/builder/builder.go
legacy/builder/builder_utils/utils.go
legacy/builder/container_find_includes.go
legacy/builder/preprocess_sketch.go
legacy/builder/types/context.go
legacy/builder/utils/utils.go

In some cases, while running a compile with JSON output format, the stderr of the compiler is lost.
See #1698 for details
```
$ cat Blink.ino 
void setup() {
}
void loop() {
}
$ cat test.cpp 
void aaa() {
$ arduino-cli compile -b arduino:avr:uno --format json | jq .compiler_err
"\n"
```
With the same setup:
```
$ arduino-cli compile -b arduino:avr:uno --format json | jq .compiler_err
"/home/cmaglie/Arduino/Blink/test.cpp: In function 'void aaa()':\n/home/megabug/Arduino/Blink/test.cpp:2:12: error: expected '}' at end of input\n void aaa() {\n            ^\n\n"
```
No

Fixed compiler output capture in JSON mode

---

commands/sketch/new.go
commands/sketch/new_test.go
docs/sketch-specification.md

Enhancement
The Arduino Sketch Specification defines the allowed format of sketch folder names and sketch code filenames.
The origin of the specification is the text of the error message shown in Arduino IDE when the user attempts to save to a name that contains disallowed characters:
https://github.com/arduino/Arduino/blob/89539b1131f8cde9f7a83225f21c811071af53a8/app/src/processing/app/SketchController.java#L847-L853
However, …

Allow leading underscore in sketch filenames

---

arduino/cores/packagemanager/package_manager.go
arduino/cores/packagemanager/package_manager_test.go
arduino/discovery/discovery.go
arduino/discovery/discoverymanager/discoverymanager.go
commands/instances.go

It introduces a teardown of the running discovery processes when installing a new core, restarting them after to keep the watchers receiving events.
When a new core is installed the running discovery processes are not terminated. Alive watchers freeze and don't receive any new events.
When a new core is installed all running discovery processes are terminated, also those not interested by the update. They are restarted after the installation completed and watchers are reconnected to the new stream of events.
Connected boards face first a "remove" and then an "add" event.
Fixes #1960 …

fix: discovery cleanup and watchers continuity upon core install 

---

.github/workflows/check-go-task.yml
.licensed.yml

Since the following:
* `arduino/discovery/discovery_client`
* `client_example`
* `commands/daemon/term_example`
* `docsgen`
are no more separate go modules there is no more need to run `vet`, `fix`, `lint`, `fmt`, and `tidy` on all of them.

Removed no more needed checks to go sub-programs

---

arduino/monitor/monitor_test.go
executils/process.go

Fixed a couple of theoretical race conditions (they are detected by the race condition detector, but they are very unlikely to happen in a real-world scenario).
No

Fixed a couple of (very rare) race conditions

---

docs/UPGRADING.md
internal/cli/core/list.go
internal/cli/lib/list.go
internal/cli/outdated/outdated.go
internal/integrationtest/outdated/outdated_test.go
internal/integrationtest/update/update_test.go
internal/integrationtest/upgrade/upgrade_test.go

Fixes issue #2104
The code for `internal/cli/core` and `internal/cli/lib` has been
refactored so that we can use only the `Get` functions from
`internal/cli/outdated` package and compose there composited object.
For regular text output, the new table will have some extra fields that
either for platforms or for libraries will be blank.
For JSON and YAML output, the resulting object will have the top-level
keys `platforms` and `libraries` which contain, respectively, the array
of outaded platforms and outdated libraries.
Fixes #2104
`outdated` commands prints two tables for text mode, …

Fix invalid JSON and YAML outputs for `outdated` command

---

.github/workflows/check-markdown-task.yml
.gitignore
.markdownlintignore
Taskfile.yml
package-lock.json
package.json

`check-markdown-task` workflow has been updated to match its [upstream template](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md).
No
`markdown-link-check` tool version has been pinned to `3.10.3` because the latest release of the tool introduced some errors. More on the subject here: https://github.com/tcort/markdown-link-check/issues/246

[skip-changelog] Sync `check-markdown-task` with upstream version of the workflow

---

arduino/cores/packagemanager/loader_test.go
arduino/cores/packagemanager/package_manager_test.go
arduino/cores/tools.go
internal/integrationtest/board/board_test.go

The recovery from an interrupted builtin tool installation must be manually performed by deleting the empty tool directory.
If the `installDir` of a tool is an empty directory, the tool is not considered as installed, so it will be downloaded again when necessary.
No

[skip-changelog] Recover from interrupted builtin tool installation

---

arduino/libraries/libraries.go
arduino/libraries/librariesresolver/cpp.go
arduino/libraries/librariesresolver/cpp_test.go
commands/lib/list.go
docs/UPGRADING.md
internal/cli/lib/list.go
internal/integrationtest/lib/lib_test.go

For details see #1566, and #1656
```
$ arduino-cli lib list USBHost --all
Name    Installed   Available   Location              Description                                                               
USBHost 1.0.5       -           LIBRARY_LOCATION_USER -                                                                         
"      1.0         1.0.5       arduino:samd@1.8.13   Allows the communication with USB per...                                  
"      1.0         1.0.5       things:samd@1.8.13    Allows the communication with USB per...                                  
$ …
```

[breaking] Fix: `lib list --fqbn` and `lib examples --fqbn` do not show platform bundled lib when lib of same name is installed globally

---

executils/executils_freebsd.go
i18n/detect_freebsd.go

Allows to build the software in freebsd.
On building you get an error on using the default (unimplemented) method for the two new files.
It builds Ok.  A link from the linux versions with `_freebsd.go` suffix has been created.  Internally the call used in freebsd is the same as the one used in linux.  
I don't think so.
N.A.

Compile on freebsd

---

internal/integrationtest/core/core_test.go

Fixed an integration test.
The test was failing because the expected result wasn't on the line it was supposed to be.
The test does not depend anymore on a fixed-line assumption.

Made an integration test more reliable

---

legacy/builder/test/prototypes_adder_test.go

Just an optimization of a test.

Skip useless operations in legacy test

---

legacy/builder/preprocess_sketch.go
legacy/builder/test/prototypes_adder_test.go
legacy/builder/types/context.go

Remove an undocumented and unused feature.
It's not a breaking change, because the feature can not be enabled in any way and the golang API change is in the `legacy` package.

Removed legacy 'codecomplete' implementation.

---

arduino/libraries/libraries_test.go
arduino/libraries/loader.go
docs/library-specification.md
internal/integrationtest/lib/lib_test.go

Empty folders under `<directories.user>/libraries` show up as `is_legacy: true` libraries.
Folders that do not contain a `library.properties` or a `.h` file are ignored when `lib list` is executed.
No

[skip-changelog] Exclude libraries with a missing `.h` file from `lib list`

---

commands/instances.go
internal/integrationtest/compile_3/compile_test.go
legacy/builder/libraries_loader.go

- The library loading errors do not affect compile results anymore.
- Fixed an error message
- Library loading warnings are reported only in verbose compile
If an invalid library is installed in the system, all sketch compilations will fail, even if the library is not used:
```
$ arduino-cli compile -b arduino:avr:uno
Error initializing instance: Loading libraries: &{0xc001c760c0}
Used platform Version Path                                                        
arduino:avr   1.8.5   /home/megabug/.arduino15/packages/arduino/hardware/avr/1.8.5
Error during build: rpc error: code = …
```

fix: library loading errors genereates unneeded compile failures

---

arduino/cores/packageindex/index.go

The verification of the signature on the package index fails silently.
A warning is issued if the signature verification fails.
No

[skip-changelog] Issue a warning when the signature verification fails

---

docs/configuration.md
internal/cli/config/init.go

The documentation has been improved by adding the correct format for the environment variable `ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS`. Also, `config init` now fails if a URL saved in `additional_urls` contains a comma.
No

[Skip-changelog] Improve documentation regarding `ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS`

---

internal/cli/compile/compile.go
internal/integrationtest/compile_1/compile_test.go

Do not print compilation stats at the end of the `compile --preprocess` output.
```
$ arduino-cli compile -b arduino:avr:uno ~/Arduino/Blink/ --preprocess
#include <Arduino.h>
#line 1 "/home/megabug/Arduino/Blink/Blink.ino"
#line 1 "/home/megabug/Arduino/Blink/Blink.ino"
void setup();
#line 3 "/home/megabug/Arduino/Blink/Blink.ino"
void loop();
#line 1 "/home/megabug/Arduino/Blink/Blink.ino"
void setup() {
}
void loop() {
}
Used platform Version Path                                                        
arduino:avr   1.8.6 …
```

Fix preprocess output (do not print stats after the preprocessed source)

---

arduino/cores/packagemanager/loader.go

Platform authors cannot use a custom monitor tool for the `serial` protocol.
```
$ echo "pluggable_monitor.pattern.serial=foobar" >> ~/.arduino15/packages/arduino/hardware/avr/1.8.3/platform.txt
$ arduino-cli monitor --port /dev/ttyACM0 --fqbn arduino:avr:leonardo --protocol serial
Connected to /dev/ttyACM0! Press CTRL-C to exit.
Hello world from the Arduino Leonardo's serial port!
^C
$ echo "pluggable_monitor.pattern.myprotocol=bazqux" >> ~/.arduino15/packages/arduino/hardware/avr/1.8.3/platform.txt
$ arduino-cli monitor --port /dev/ttyACM0 --fqbn …
```

[skip-changelog] Override default pluggable monitor for `serial` protocol

---

arduino/cores/board.go
arduino/cores/board_test.go

This will change the output sorting when calling the boards details.
When launching the `arduino-cli boards details -b esp8266:esp8266:generic --format json` the order of the
config options doesn't follow the order of the menu declared in the first lines of `boards.txt` file.
We now ensure that the order of the config options are following the order of the menus fields declared at the beginning of `boards.txt`
Nope

Respect the order of menu, when computing the config options

---

.licenses/go/github.com/arduino/go-paths-helper.dep.yml
arduino/cores/packagemanager/install_uninstall.go
arduino/sketch/sketch.go
commands/compile/compile.go
go.mod
go.sum

This issue is mainly seen on Windows.
(copied from original issue: https://github.com/arduino/arduino-cli/issues/2156)
```
$ arduino-cli sketch new "e:/FooSketch"
Sketch created in: e:\FooSketch
$ arduino-cli compile --build-path "c:/Users/per/AppData/Local/Temp/build-path" --fqbn arduino:avr:uno "e:/FooSketch"
Error during build: Cannot find build path: Rel: can't make c:\Users\per\AppData\Local\Temp\build-path relative to E:\FooSketch
```
Compiles succeed as expected.
No
The actual patch is here: https://github.com/arduino/go-paths-helper/pull/20
Fix …

fix: Allow build-path to be in a different drive than current sketch

---

arduino/libraries/libraries_test.go
arduino/libraries/loader.go
arduino/libraries/testdata/TestLibExamples/library.properties

When loading a library or sketch that contains multiple symlinks to a parent path, Arduino CLI locks up in a perpetual loop.
Arduino CLI fails with an error when a symlink loop is encountered.
No

[skip-changelog] Avoid getting locked up in a perpetual symlink loop when loading a library

---

arduino/cores/packagemanager/loader_test.go
arduino/cores/packagemanager/package_manager_test.go
arduino/cores/tools.go
internal/integrationtest/board/board_test.go

The CLI checks if an executable file is present inside the installation directory of a builtin tool. If not, that tool is marked as not installed.
No

[skip-changelog] Verify installation of builtin tools by checking that their executable is present

---

.licenses/go/github.com/arduino/go-win32-utils.dep.yml
go.mod
go.sum

`go-win32-utils` dependency has been updated to version `1.0.0`.
No

[skip-changelog] Update `go-win32-utils` dependency

---

arduino/serialutils/serialutils.go
commands/upload/upload.go
internal/integrationtest/upload_mock/upload_mock_test.go

This PR should make it easier to recover from soft-bricked boards with native USB (in cases where the serial port is unavailable because the bootloader has a too-short timeout).
Trying the upload without a port selected would cause the upload to immediately fail, without leaving any room for the user to synchronize with the upload by tapping the reset button. See #1943 for more details.
The upload should wait a reasonable amount of time for the user to tap the reset button and make the bootloader avaiable.
No, in theory...
Fix #1943

Easier recovery from soft bricked native USB boards

---

docs/CONTRIBUTING.md

Just some improvements in documentation

Improved gRPC how-to in contributing guide

---

internal/integrationtest/lib/lib_test.go

Fix an integration test.
The test checks a download URL for a dependency that has been updated.
Previously it downloaded version 3.3.1, but at the moment the new dependency is 3.4.0.
This fix makes the test independent from such changes.

Fixed integration test

---

.github/workflows/check-go-task.yml
Taskfile.yml
arduino/discovery/testdata/cat/main.go
commands/lib/search_test.go
commands/sketch/new_test.go
configuration/configuration_schema_test.go
executils/testdata/delay/main.go
i18n/cmd/po/merge_test.go
internal/cli/arguments/completion.go
license_header.tpl

This adds a new CI check for new go files missing the license headers. 
We have to put in the root of the folder a template called: `license_header.tpl`. This file will be used by `addlicense` to add any missing license header in the go file.
If we create a new go file and forget to add a license header we can spot it only by a manual CR which might be error-prone if the PR is large.
Every time a new golang file is pushed with a missing license header the CI will fail and warn the user.
Any suggestion are welcomed

[skip changelog] Automate license headers checks in CI

---

docs/package_index_json-specification.md

Improve the Archive docs section
-

Improve archive structure docs

---

.github/workflows/check-protobuf-task.yml

Bump the setup-protoc action. This will enable us to use the latest protobuf versions in the future

[skip-changelog] Bump setup-protoc to v2

---

arduino/serialutils/serialutils.go
commands/upload/upload.go

Trying to upload a sketch when the serial port is busy correctly fails, but the error is displayed as simple output text.
```
$ grpcurl \
-plaintext \
-import-path ./rpc \
-proto cc/arduino/cli/commands/v1/commands.proto \
127.0.0.1:50051 \
cc.arduino.cli.commands.v1.ArduinoCoreService.Create
{
"instance": {
"id": 1
}
}
$ grpcurl \
-plaintext \
-import-path ./rpc \
-proto cc/arduino/cli/commands/v1/commands.proto \
-d '{"instance": {"id": 1}}' \
127.0.0.1:50051 \
cc.arduino.cli.commands.v1.ArduinoCoreService.Init
$ grpcurl \
-plaintext \
-import-path ./rpc \ …
```

[skip-changelog] Handle errors that occur during reset

---

arduino/builder/preprocessor/gcc.go
legacy/builder/container_add_prototypes.go
legacy/builder/container_find_includes.go
legacy/builder/ctags/ctags_has_issues.go
legacy/builder/ctags/ctags_parser.go
legacy/builder/ctags/ctags_parser_test.go
legacy/builder/ctags/ctags_to_prototypes.go
legacy/builder/ctags/ctags_to_prototypes_test.go
legacy/builder/gcc_preproc_runner.go
legacy/builder/preprocess_sketch.go
legacy/builder/prototypes_adder.go

This PR is a try to split the bigger PR https://github.com/arduino/arduino-cli/pull/2147 into smaller pieces to allow an easier review process.
No changes
No

[skip-changelog] legacy: Arduino preprocess subroutine refactorization (part 4)

---

commands/upload/upload.go
internal/integrationtest/upload/upload_test.go

Fix a crash in upload if:
* The platform requires an upload tool from another (referenced) platform
* The referenced platform is missing
See https://github.com/arduino/arduino-cli/issues/2042 for more details:
```
$ arduino-cli compile -b arduino:avr:uno --upload arduino-cli/internal/integrationtest/testdata/bare_minimum
Sketch uses 444 bytes (1%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.
panic: runtime error: invalid memory address or nil pointer dereference …
```

Fix crash in upload if the upload tool platform is missing

---

internal/cli/core/upgrade.go
internal/integrationtest/core/core_test.go

Return exit code 0 if a platform is already at the latest version
Returns exit code 1.
Returns exit code 0.

Return exit code 0 when a core is already up to date

---

arduino/resources/index.go
commands/core/list.go
commands/daemon/daemon.go
commands/instances.go
docs/UPGRADING.md
internal/cli/arguments/completion.go
internal/cli/arguments/reference.go
internal/cli/core/list.go
internal/cli/core/search.go
internal/cli/core/update_index.go
internal/cli/core/upgrade.go
internal/cli/instance/instance.go
internal/cli/lib/search.go
internal/cli/lib/update_index.go
internal/cli/update/update.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/daemon/daemon_test.go

This PR changes the behavior of the `Init` function of the gRPC API.
Previously if the main indexes `package_index.json` or `library_index.json` were missing (for example after installing on a clean system) the gRPC client had to call `UpdateIndex` or `UpdateLibrariesIndex` to download the indexes and re-`Init` the gRPC instance.
The indexes download is performed automatically.
It changes some golang API calls as described in the `UPGRADING.md`.
The gRPC is backward compatible, but the old clients may not be optimized and may force the download of the index twice.
Fix #1529

Automatically download indexes, if missing, in gRPC `Init` call

---

commands/sketch/new.go
commands/sketch/new_test.go
docs/UPGRADING.md
docs/sketch-specification.md

Sketch names ending with a `.` can be used. [Reserved names](https://learn.microsoft.com/en-ca/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) can be used as sketch names.
It is no longer possible to name sketches in the above mentioned way.
Yes

[breaking] Check cross-platform compatibility of sketch names

---

internal/integrationtest/testdata/installed.json

Infrastructure imperfection fix
Expected `installed.json` used in integration tests is up-to-date.
No

[skip-changelog] Update expected `installed.json` after index changes

---

internal/integrationtest/board/board_test.go

Some board tests are failing.
`TestBoardSearch` has been updated to match the changes in the package index. `TestBoardListWithInvalidDiscovery` has been removed because it's a duplicate of `TestBoardListWithFailedBuiltinInstallation`, with the latter being more recent.
No

[skip-changelog] Fix failing board tests

---

docs/UPGRADING.md
internal/cli/board/list.go

The json output of the two commands is different.
The output of `board list --watch` has changed to align to `board list`. The changes are:
- `matching_boards` replaced `boards`
- `address`, `label`, `protocl` and others have been grouped under `port`
- `eventType` replaced `type`
These are the json outputs now:
```
$ ./arduino-cli.exe board list --watch --format json
{
"eventType": "add",
"matching_boards": [
{
"name": "Arduino Nano RP2040 Connect",
"fqbn": "arduino:mbed_nano:nanorp2040connect"
}
],
"port": {
"address": "COM3",
"label": "COM3",
"protocol": …
```

[breaking] Align `board list --watch` and `board list` json output

---

commands/board/list.go

Populates the `is_hidden` field when the board is detected.
`board list` do not report hidden field:
`board list` do report hidden field:
```
[
{
"matching_boards": [
{
"name": "Arduino Uno R4 WiFi",
"fqbn": "arduino:renesas_portenta:unor4wifi",
"is_hidden": true
},
{
"name": "Arduino Uno R4 WiFi",
"fqbn": "arduino:renesas_uno:unor4wifi"
}
],
"port": {
"address": "/dev/ttyACM0",
"label": "/dev/ttyACM0",
"protocol": "serial",
"protocol_label": "Serial Port (USB)",
"properties": {
"pid": "0x1002",
"serialNumber": "DC5475C30184",
"vid": "0x2341"
},
"hardware_id": "DC5475C30184"
}
},
{ …
```

Report `is_hidden` field in board identification

---

arduino/serialutils/serialutils.go

This PR disables the step that sets DTR low on the 1200-bps touch subroutine.
This reason why it was originally introduced:
https://github.com/arduino/Arduino/commit/a6909bdb49d99253b4e684365e72e5dce31a49a7
Why we are removing it now?
* Windows does preserve the state of the RTS/DTR bits on the next opening of the serial port.
* The serial library used in the Arduino IDE 1.8.x has a bug when trying to set DTR=false, on successive opening of the port the DTR line is set back high by the USB serial driver. This works differently from the serial library we use in the Arduino CLI, which …

Fix 1200-bps touch DTR handling (Windows)

---

internal/cli/core/list.go
internal/integrationtest/core/core_test.go

`core list` command now prints the table headers in the stdout when no platforms are installed
Empty stdout. The only case we show something is when we set the json format flag it returns `[]`
The new behavior if no platforms are installed prints only the table headers.
The other option we have is to show something like this:
```bash
$ arduino-cli core list
No platforms installed.
```

When launching `core list` with no installed platforms show table headers

---

configuration/configuration.schema.json
docs/configuration.md

An explanation for the configuration key `output.no_color` has been added to the docs.
No

[skip-changelog] Add `output.no_color` to configuration docs

---

docs/FAQ.md

An explanation on how to change monitor configuration parameters using `monitor -c` has been added to the FAQ.
No

[skip-changelog] Add explanation on how to change the monitor configuration to FAQ

---

internal/cli/monitor/monitor.go

docs update
The [`--config`](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_monitor/#options) flag of the [`arduino-cli monitor`](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_monitor/) command is used to configure the communication port used by the monitor.
Previously the command line help did not provide any guidance for the usage of this flag, which might lead the users to wonder (https://github.com/arduino/arduino-cli/issues/2070):
- How can the configuration options available for use via the flag be determined?
- What is the format for the …

Explain usage of `monitor --config` in command help

---

internal/cli/cli.go

Adds a `--log` global flag and hides the old `-v`.
This change allows to print logs with commands that have their own `-v` flag overridden (`compile` and `upload`).
```
$ arduino-cli
[...]
--log-file string           Path to the file where logs will be written.
--log-format string         The output format for the logs, can be: text, json
--log-level string          Messages with this level and above will be logged. Valid levels are: trace, debug, info, warn, error, fatal, panic
--no-color                  Disable colored output.
-v, --verbose                   Print the logs on the …
```

Add `--log` global flag as alias for `--verbose/-v`

---

docs/package_index_json-specification.md

Improved the documentation about tools' "flavor" selection mechanism.
Fix #2004

docs: clarified how tools flavours are selected

---

arduino/libraries/libraries_test.go
arduino/libraries/loader.go

Givin a relative path is not ideal, but at least allows the CLI to compile the sketch correctly.
This PR makes the `Library` loader a bit more resilient by allowing relative paths as input.
Using relative paths may lead to other problems, but at least this change allows the CLI to not bail out with weird errors.
If a relative path is given (via `directories` configuration in `arduino-cli.yaml`) in some cases the path composition during compile fails. See #2180 for an example.
The compilation succeeds.
No
Fix #2180

Fixed loading of Library given a non-absolute path

---

arduino/builder/preprocessor/gcc.go

Previously the undefined template placeholders in `recipe.preproc.macros` were silently replaced by the empty string. This changed after a refactoring in 0585435f8b1d05e0117606f69bea42d3f3dfec79.
Previously it was:
https://github.com/arduino/arduino-cli/commit/0585435f8b1d05e0117606f69bea42d3f3dfec79#diff-371f93465ca5a66f01cbe876348f67990750091d27a827781c8633456b93ef3bL62
```diff
-       cmd, err := builder_utils.PrepareCommandForRecipe(buildProperties, "recipe.preproc.macros", true, ctx.PackageManager.GetEnvVarsForSpawnedProcess())
```
The `true` parameter in the call to …

regression: Fix property expansion of "recipe.preproc.macros"

---

internal/integrationtest/compile_3/compile_test.go
internal/integrationtest/compile_3/testdata/using_Wire/using_Wire.ino
legacy/builder/container_find_includes.go

This regression was made during a refactoring of the Arduino preprocessor. In particular the wrong change was part of this commit: https://github.com/arduino/arduino-cli/commit/0585435f8b1d05e0117606f69bea42d3f3dfec79#diff-65ff16cbee816c0f443157444d99bcc144beee06c3329aec891894c8aeda7b27L372-R378
```diff
-                       preproc_stderr, preproc_err = GCCPreprocRunner(ctx, sourcePath, targetFilePath, includes)
+                       var preproc_stdout []byte
+                       preproc_stdout, preproc_stderr, preproc_err = preprocessor.GCC(sourcePath, targetFilePath, …
```

regression: hide include-not-found errors during library discovery

---

arduino/globals/globals.go
docs/platform-specification.md
internal/integrationtest/compile_3/compile_cxx_cc_test.go
internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/sketch_with_cxx_cc.ino
internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/test.cc
internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/test.cxx
legacy/builder/builder_utils/utils.go

Allows compilation to build also `.cxx` and `.cc` files.
In theory, the platforms should provide a recipe for compiling `cxx` and `cc` specifically, but this implementation reuses the recipe for `.cpp` as a fallback if the specific recipes are missing (that is the situation for basically all the platforms in the existence, and it is unlikely to change in the future).
`.cxx` and `.cc` files are ignored.
`.cxx` and `.cc` files are compiled.
No
Fix #1149

Allow `.cxx` and `.cc` extension in compile

---

commands/compile/compile.go
commands/upload/upload.go
docs/sketch-project-file.md
internal/cli/compile/compile.go
internal/cli/upload/upload.go
internal/integrationtest/profiles/profiles_test.go
internal/integrationtest/testdata/sketch_with_default_profile/sketch.yaml
internal/integrationtest/testdata/sketch_with_default_profile/sketch_with_default_profile.ino
internal/integrationtest/testdata/sketch_with_profile/sketch.yaml
internal/integrationtest/testdata/sketch_without_default_profile/sketch.yaml
internal/integrationtest/testdata/sketch_without_default_profile/sketch_without_default_profile.ino

It is now possible to `compile` and `upload` using the `default_profile` specified in the `sketch.yaml` file through the following commands:
```
compile [sketch]
```
```
upload -p [port] [sketch]
```
The `gRPC` interface also supports the `default_profile`. If present, it will be part of `LoadSketchResponse` (#2264).
No

Add support for default build profile

---

internal/integrationtest/daemon/daemon_concurrency_test.go

I see an increase in transient CI failures for this test. Let's try to increase the timeout to see if it solves the problem.

Relaxed test constraints

---

commands/upload/upload.go

This patch takes into account the port connection/disconnection that may happen after the upload.
This case was already handled, but this patch slightly increased the timeout to allow the port re-enumeration.
Moreover, I've added a fallback: if the algorithm is unable to find a port, it will return the user-provided port for the upload.
No upload port detected:
```
./arduino-cli upload -b arduino:mbed_nano:nano33ble -p /dev/cu.usbmodem5 ~/Documents/Arduino/minimal --format json
{
"stdout": "Device       : nRF52840-QIAA\nVersion      : Arduino Bootloader (SAM-BA extended) 2.0 …
```

Upload port detector improvements

---

table/table.go

Remove the right-padding of tables of the CLI.
See #2289:
> Here is an example of what the current behavior looks like, with = replacing spaces to make it clearer.
>
> ```
> Sketch=uses=58120=bytes=(11%)=of=program=storage=space.=Maximum=is=507904=bytes.
> 
> Used=library===============Version=Path==================================================
> CAN=Adafruit=Fork==========1.2.1===/home/trb/Arduino/libraries/arduino-CAN-master========
> LibPrintf==================1.2.13==/home/trb/Arduino/libraries/LibPrintf=================
> …
```

Text output: removed trailing spaces for right-padding of tables

---

internal/cli/arguments/completion.go

No changes, the code is reorganized to avoid accessing `arduino/cores` package directly.
No
Related to https://github.com/arduino/arduino-cli/issues/1948

[skip-changelog] Use gRPC function call to avoid accessing `arduino/cores` package directly

---

internal/cli/arguments/fqbn.go
internal/cli/arguments/port.go
internal/cli/burnbootloader/burnbootloader.go
internal/cli/upload/upload.go

No changes, the gRPC interface is used to avoid accessing `arduino` package directly.
No
Related to #1948

[skip-changelog] Use `LoadSketch` in upload function and return `rpc.Port` in `GetPort`

---

commands/compile/compile.go
commands/upload/upload.go
docs/sketch-project-file.md
internal/cli/arguments/fqbn.go
internal/cli/arguments/port.go
internal/cli/burnbootloader/burnbootloader.go
internal/cli/compile/compile.go
internal/cli/upload/upload.go
internal/integrationtest/profiles/profiles_test.go
internal/integrationtest/testdata/sketch_with_default_profile/sketch.yaml
internal/integrationtest/testdata/sketch_with_default_profile/sketch_with_default_profile.ino
internal/integrationtest/testdata/sketch_without_default_profile/sketch.yaml
internal/integrationtest/testdata/sketch_without_default_profile/sketch_without_default_profile.ino

The regression has already been fixed as part of another refactoring:
- #2297
- #2203
This PR cherry-picks the fix in the current 0.34.x branch to release a `0.34.2`.
`arduino-cli compile ... --input-dir .` crashes instead of uploading.
Please have a look at #2304 for details.
Upload works as expected.
Fix #2304

regression: Import fix for `compile --input-dir .` regression found in #2304

---

arduino/errors.go
internal/cli/arguments/reference.go
internal/integrationtest/core/core_test.go

Fixed an error message.
```
$ arduino-cli core install asdasd:asdasd
Invalid argument passed: Found 0 platform for reference "asdasd:asdasd":
```
```
$ arduino-cli core install asdasd:asdasd
Invalid argument passed: Platform 'asdasd:asdasd' not found
```

Fixed weird error message in `core install` if invalid platform is spcified

---

arduino/cores/packagemanager/package_manager.go

Feature.
Logging with `info` generates too much noise.
Log `Required tool` with `debug` severity.
No.
Closes arduino/arduino-cli#2313

feat: log `Required tool` with `debug` severity

---

arduino/resources/index.go
commands/instances.go

There are some cases where the signature check is skipped when upgrading indexes. This PR ensures that the signature check is enforced for the library_index.json.
If the "bundle index+signature" `library_index.tar.bz2` does not contain the signature, then the signature check is silently sipped.
If the "bundle index+signature" `library_index.tar.bz2` does not contain the signature, then the index upgrade fails.
No

Improve signature check on library_index.json

---

commands/compile/compile.go
internal/integrationtest/compile_1/compile_test.go

Skip the copy of compiled binaries when the specified `--build-path` equals to `--output-dir`. 
By doing so we also avoid useless computation. (This doesn't solve the root of the problem which is underneath the `CopyTo` function. Another PR will address it to go-paths-helper repo)  
When `--build-path` equals to `--output-dir` we copy the compiled files but their contet is empty.
When both flags are set we simply skip the copying part.
Most likely we should address this also in the gopaths library.

Fix empty copy of compiled binaries when `--build-path` equals to `--output-dir`

---

internal/cli/monitor/monitor.go
internal/cli/monitor/monitor_test.go

New feature in the monitor that can add a timestamp to the beginning of each received line.
No such option.
When `--timestamp` is provided, the monitor wraps the output tty with a timestamping Writer. The format of the timestamps is `YYYY-mm-dd HH:MM:SS`.
Negative.
This is my first time writing Go (except for the sample program I used to work out the approach), so please review carefully.
There don't appear to be any docs specifically about the monitor command, nor tests of the CLI entry point.
The change was tested by hand using this sketch:
```
void setup()
{
Serial.begin(115200);
}
static const uint32_t period = 100; // millis
void loop()
{
static uint32_t …
```

Added `--timestamp` option to monitor command.

---

arduino/builder/builder.go
commands/compile/compile.go

Fixed a regression after legacy builder refactoring.
Preprocessor output is always displayed.
The preprocessor output is displayed only with `--preprocess` flag.

legacy: Fixed regression on `compile --preprocess` output

---

arduino/globals/globals.go
arduino/sketch/sketch.go
commands/upload/upload.go
internal/integrationtest/compile_1/compile_test.go

Reduce CPU and disk consumption if multiple build paths are created in the sketch directory.
See #2266 for details, for example running a build using the build-path to multiple subdirs of the sketch:
```
arduino-cli compile -b arduino:mbed_nano:nano33ble --build-cache-path build-nano33ble --build-path build-nano33ble
arduino-cli compile -b arduino:mbed_nano:nano33ble --build-cache-path build-nano33blesense2 --build-path build-nano33blesense2 --build-property 'compiler.cpp.extra_flags=-DSENSE_REV2'
```
results in:
* a full sketch rebuild when the target directory is changed (unneeded …

bugfix: excessive CPU/Disk usage when multiple build-paths points in the sketch directory

---

arduino/resources/index.go
arduino/resources/resources_test.go

Fixes a regression that truncates every `.` in the filename.

fix wrong IndexFile truncate

---

arduino/builder/builder.go
internal/integrationtest/compile_3/compile_show_properties_test.go

Adds the missing `sketch_path` variable to the build properties.
`{sketch_path}` is missing from the build properties:
```
$ arduino-cli compile -b arduino:avr:uno --show-properties | grep sketch_path
$
```
`{sketch_path}` is present in the build properties:
```
$ arduino-cli compile -b arduino:avr:uno --show-properties | grep sketch_path
sketch_path=/home/cmaglie/Arduino/Blink
$
```
No
Fix #2340

Added `{sketch_path}` to build properties

---

.github/workflows/release-go-task.yml
Taskfile.yml
docs/UPGRADING.md
install.sh

Infrastructure change
Fix #2341 
We release Arduino CLI with "v" version format
We still use `0.35.x` format for the doc branch and internally in the CLI the format is semver-compliant.
Test run after pushing `0.35.x` branch: https://github.com/umbynos/arduino-cli/actions?query=branch%3A0.35.x
Test run of `release-go-task` after pushing `v.0.35.0` tag https://github.com/umbynos/arduino-cli/actions/runs/6576137988
Technically no

Introduce new "v" version format

---

install.sh

Due to PR https://github.com/arduino/arduino-cli/pull/2374, `install.sh` fails to run on the latest release tag:
```
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
Installing in [dir]
ARCH=64bit
OS=macOS
Using curl as download tool
Failed to install arduino-cli
```
In turn, this causes repositories that have automated tooling and rely upon `install.sh` (such as adafruit/ci-arduino) to fail.
This pull request implements a fix suggested by @tobozo in https://github.com/arduino/arduino-cli/issues/2370 because the `v?` prefix requires escaping to be passed to `grep`.
cc @cmaglie @per1234

Fix "Failed to install arduino-cli" when invoked by install.sh

---

commands/lib/search.go
commands/lib/search_matcher.go
commands/lib/search_test.go
commands/lib/testdata/qualified_search/library_index.json
internal/cli/lib/search.go
internal/integrationtest/lib/lib_test.go

More powerful search using a syntax of `qualifier[:=]value` that allows for partial or exact match (still case-insensitive) against specific library metadata fields.
The behavior was discussed in https://github.com/arduino/arduino-cli/issues/1535
All `lib search` commands compare the provided query terms against a string constructed from several of each library's metadata fields.
All queries that do not contain either a ':' or '=' character are handled exactly as before.
Queries that do contain one of the above characters are parsed using new logic that allows for double-quoted strings to contain spaces, and allows for backslash-escaped literal double-quote …

Added search using qualifier[:=]value syntax

---

internal/cli/arguments/port.go
internal/cli/arguments/sketch.go
internal/cli/board/attach.go
internal/cli/compile/compile.go
internal/cli/debug/debug.go
internal/cli/monitor/monitor.go
internal/cli/upload/upload.go
internal/integrationtest/monitor/monitor_test.go
internal/integrationtest/monitor/testdata/SketchWithDefaultFQBN/SketchWithDefaultFQBN.ino
internal/integrationtest/monitor/testdata/SketchWithDefaultFQBN/sketch.yaml
internal/integrationtest/monitor/testdata/SketchWithDefaultPort/SketchWithDefaultPort.ino
internal/integrationtest/monitor/testdata/SketchWithDefaultPort/sketch.yaml
internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndFQBN/SketchWithDefaultPortAndFQBN.ino
internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndFQBN/sketch.yaml
internal/integrationtest/monitor/testdata/SketchWithNoProfiles/SketchWithNoProfiles.ino

It is not possible to retrieve port address and protocol information from a sketch profile. `monitor` cannot run if `-p <port>` is not specified.
Default port address and protocol can be retrieved from the sketch profile using the `-s <sketchPath>` flag. `-p <port>` and `-l <protocol>` have priority over the information stored in the profile.
No

Get default port address and protocol from sketch profile using `monitor -s <sketchPath>`

---

commands/debug/debug_info.go
commands/debug/debug_test.go
commands/debug/testdata/custom_hardware/arduino-test/samd/programmers.txt

Enforce programmer selection to `debug`.
The `debug` command allows running without specifying the `-P` flag.
```
$ arduino-cli debug -b arduino:samd:mkr1000 
Error during Debug: Missing programmer
$ arduino-cli debug -b arduino:samd:mkr1000 --info
Error getting Debug info: Missing programmer
$ arduino-cli debug -b arduino:samd:mkr1000 --info --format json
{
"error": "Error getting Debug info: Missing programmer"
}
$ 
```

debug: Enforce programmer selection

---

internal/cli/daemon/daemon.go
internal/cli/feedback/errorcodes.go

Makes the `daemon` command return a consistent exit code for specific errors.
The exit code was a bit random:
* If "CLI failed to open a TCP port to listen for incoming connections" the exit code could be 1 (Generic error), 5 (Network error), or 0 (Success!)
* If "TCP port argument is not valid" the exit code could be 6 (Core config error) or 7 (Bad Argument error).
The following error codes have been added:
* code `8`: CLI failed to open a TCP port to listen for incoming connections
* code `9`: TCP port argument is not valid
Related to #2352

feat: added exit codes for CLI `daemon` command errors

---

internal/cli/board/details.go
internal/cli/board/list.go
internal/cli/board/listall.go
internal/cli/board/search.go
internal/cli/compile/compile.go
internal/cli/core/list.go
internal/cli/core/search.go
internal/cli/feedback/result/rpc.go
internal/cli/feedback/result/rpc_test.go
internal/cli/lib/check_deps.go
internal/cli/lib/examples.go
internal/cli/lib/list.go
internal/cli/lib/search.go
internal/cli/monitor/monitor.go
internal/cli/outdated/outdated.go
internal/cli/sketch/new.go
internal/cli/upload/upload.go

IT add a layer of mappers used only in the cli output of ours command and subcommand
We are currently returning/using the rpc structs which isn't ideal for 2 reasons:
- Maps can be serialized randomly
- Enums are serialized as a number instead of their string representation.

Use feedback/result structs in cli commands instead of rpc ones

---

internal/cli/cli.go
internal/cli/feedback/errorcodes.go

Add a specific exit code for the CLI to signal failure on initializing the "inventory" storage.
In case of failure to initialize inventory, the CLI returned a generic error code `7`, i.e. `ErrBadArgument`.
In case of failure to initialize inventory, the CLI return an error code `10`, i.e. `ErrInitializingInventory`.
Fix #2352

Added specific CLI return error-code if inventory can not be created

---

mysketchbook/newsketch/newsketch.ino

Remove the `mysketchbook` folder introduced by mistake by https://github.com/arduino/arduino-cli/pull/2375

[skip-changelog] remove `mysketchbook` folder committed by mistake

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml

change in tooling see https://github.com/arduino/tooling-project-assets/issues/359
An excellent tool named [gon](https://github.com/mitchellh/gon) was used to perform the notarization.
the latest stable release of gon uses the altool command-line utility for notarization:
https://github.com/mitchellh/gon/blob/v0.2.5/notarize/upload.go#L41
Using altool for notarization is now deprecated by Apple and support for notarization via this tool is scheduled to be disabled 2023-11-01:
https://developer.apple.com/news/?id=y5mjxqmn
Furthermore, gon was archived
I switched to …

Replace `mitchellh/go` used for macOS notarization

---

.github/workflows/test-go-task.yml
internal/integrationtest/board/board_test.go
internal/integrationtest/board/hardware_loading_test.go

The `board` integration test package was skipped during integration tests. This was due to a strange behavior of `jq`, which was cutting the first package in the list unless the `-n` flag was passed.
The documentation of jq reports:
```
○   --null-input/-n:
Don't  read any input at all! Instead, the filter is run once using null as the input. This is useful when using jq as
a simple calculator or to construct JSON data from scratch.
```
¯\\\_(ツ)\_/¯
See https://stackoverflow.com/a/68859958/1655275

test: Fixed runners not running 'board' integration test

---

docs/UPGRADING.md
internal/cli/board/list.go
internal/cli/board/listall.go
internal/cli/board/search.go
internal/cli/config/add.go
internal/cli/config/dump.go
internal/cli/config/init.go
internal/cli/config/set.go
internal/cli/core/list.go
internal/cli/core/search.go
internal/cli/lib/check_deps.go
internal/cli/lib/examples.go
internal/cli/lib/list.go
internal/integrationtest/board/board_test.go
internal/integrationtest/board/hardware_loading_test.go
internal/integrationtest/compile_1/compile_test.go
internal/integrationtest/config/config_test.go
internal/integrationtest/core/core_test.go
internal/integrationtest/lib/lib_test.go

We're wrapping in json object all the results that previously were emitting directly an array
Currently, some commands when printing with json, are starting with an array instead of an object
We uniformed every command to always output a json Object.

[breaking] cli: format json always start with a json object

---

arduino/builder/internal/utils/utils.go

Removes the following file filter:
```go
// filterReadableFiles is a ReadDirFilter that accepts only readable files
func filterReadableFiles(file *paths.Path) bool {
```
from the `FindFilesInFolder` function. The filter has been inherited from the legacy builder, but the reason for it is unclear. On the other hand, it triggers the ESET antivirus software, slowing down the compile.

Removed useless file-readable check while enumerating source code files

---

.licensed.yml
.licenses/go/sigs.k8s.io/yaml.dep.yml
.licenses/go/sigs.k8s.io/yaml/goyaml.v2.dep.yml
go.mod
go.sum
internal/cli/feedback/feedback.go

Instead of using go struct to produce YAML output, we're now generating it starting from the JSON result using `sigs.k8s.io/yaml`.
pros:
- We don't have to implement custom Marshaling for YAML object
- We are guaranteed that the same JSON output matches 1:1 to YAML one
- We don't risk mismatching key names between JSON and YAML.
- We don't have to maintain 2 different output formats in many places.
cons:
- slightly less performant as we're doing a double marshaling
Currently, some values in the JSON output are missing when using the YAML format.
The yaml output is now consistent with …

Make yaml output consistent with the json one

---

internal/cli/feedback/result/rpc.go

Make `programmers` and `build_properties` deterministic in JSON output.
Now when performing `arduino-cli boards details ...` it produces a JSON that has some fields that contain values that are always randomly sorted.
Now the `arduino-cli boards details ...` output produces a JSON that is always deterministic. No more randomly sorted values in arrays 🤘

make boards details JSON output deterministic

---

internal/integrationtest/board/board_test.go

Improve the `TestBoardListWithFqbnFilter`, `TestBoardList` , and `TestBoardListWithFqbnFilterInvalid` tests by using the mocked serial discovery

Use mocked serial discovery in board integration tests that weren't running in CI

---

Taskfile.yml
internal/integrationtest/arduino-cli.go

* Adds logs folding in GH-actions runners, to improve the readability of logs.
* Remove the `-v` flags from `go build` command to avoid printing hundreds of package name being build, clogging up the log with useless information.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

Improved logging on GitHub Actions runners (using log folding commands)

---

arduino/builder/internal/detector/detector.go
internal/integrationtest/compile_3/compile_commands_test.go

Fixed a regression in `compile_commands.json` generation.
This feature is mainly used in arduino-language-server.
Fix #2401

fix: Fixed regression in `compile_commands.json` generation

---

commands/debug/debug.go
commands/debug/debug_info.go
docs/UPGRADING.md
rpc/cc/arduino/cli/commands/v1/debug.pb.go
rpc/cc/arduino/cli/commands/v1/debug.proto

The `debug.toolchain.prefix` key was ignored in older versions of the Arduino IDE.
In the upcoming release (Arduino IDE 2.2.2) instead the key is used, but in the older releases of the platforms it was wrongly set to `"arm-none-eabi-"` when we actually want `"arm-none-eabi"`.
This patch ensures backward and forward compatibility.

Added a compatibility trick in `debug -I` for `toolchain.prefix` key

---

internal/cli/arguments/profiles.go
internal/cli/arguments/sketch.go
internal/integrationtest/completion/completion_test.go
internal/integrationtest/completion/testdata/SketchWithProfiles/SketchWithProfiles.ino
internal/integrationtest/completion/testdata/SketchWithProfiles/sketch.yaml

Add completion support to `--profile`

---

commands/debug/debug_info.go
docs/platform-specification.md
internal/integrationtest/debug/debug_test.go
internal/integrationtest/debug/testdata/hardware/my/samd/boards.txt
internal/integrationtest/debug/testdata/hardware/my/samd/platform.txt

It is now possible to use any sub-tree of the platform configuration to override the debugger configuration using the directive `debug.additional_config=CONF_PREFIX`.
This change allows a more convenient rationalization and selection of the configs to apply. For example, we could factor common parts of a configuration in the `platform.txt` file:
```
debug-overrides.esp32.cortex-debug.custom.name=Arduino on ESP32
debug-overrides.esp32.cortex-debug.custom.request=attach
debug-overrides.esp32.cortex-debug.custom.postAttachCommands.0=set remote hardware-watchpoint-limit 2 …
```

Debugger now allows generic selection of sub-configurations

---

docs/configuration.md

Documentation on the `network.proxy` configuration's field has been added to the docs.
No

[skip-changelog] Add documentation on the `network.proxy` configuration's field

---

commands/debug/debug_info.go
docs/UPGRADING.md
docs/platform-specification.md

Allow debugger to be disabled in case `debug.executable` property is undefined OR defined as the empty string.
Previously the debugger was disabled only if undefined.

fix: debugging requires a non empty debug.executable

---

internal/integrationtest/arduino-cli.go
internal/integrationtest/upload_mock/upload_mock_test.go

Parallelize `upload_mock` integration test.
Since the `upload_mock` tests are the longest, this change should reduce the overall execution time, I didn't check accurately, but I'm pretty sure we are gaining at least a couple of minutes over the full CI process.
`test-integration (windows-latest, upload_modk)` completes in roughly ~12 minutes.
`test-integration (windows-latest, upload_modk)` completes in roughly ~8 minutes.

Parallelize `upload_mock` integration tests

---

docs/index.md
docs/versioning.md
mkdocs.yml

Added backward compatibilty policy document

Added backward compatibilty policy document

---

.licenses/go/github.com/arduino/go-paths-helper.dep.yml
go.mod
go.sum
internal/arduino/builder/archive_compiled_files.go
internal/arduino/builder/core.go
internal/arduino/builder/libraries.go
internal/arduino/builder/linker.go
internal/integrationtest/compile_1/compile_test.go

Since archiveCompiledFiles already handles hot cache correctly, this avoids objs.a being rebuilt even if files don't change.
Would be ideal if PathList could expose a generic Filter API (to get rid of the "duplicated" filter) @cmaglie 
Reusing code is always a good idea, particularly if this fixes a missed optimization (the code path for long commandlines was always rebuilding `objs.a` even if the cache was hot)
`objs.a` are always recreated in "long commandline" sketches
Cached `objs.a` are reused, quite significant speedup for ArduinoIotCloud sketches

Reuse archiveCompiledFiles helper for long commandline shrink

---

commands/board/details.go
commands/board/list.go
commands/board/listall.go
commands/board/search.go
commands/compile/compile.go
commands/core/download.go
commands/core/install.go
commands/core/search.go
commands/core/uninstall.go
commands/core/upgrade.go
commands/debug/debug.go
commands/debug/debug_info.go
commands/instances.go
commands/internal/instances/instances.go
commands/lib/download.go
commands/lib/install.go
commands/lib/list.go
commands/lib/resolve_deps.go
commands/lib/search.go
commands/lib/uninstall.go
commands/lib/upgrade.go
commands/monitor/monitor.go
commands/monitor/settings.go
commands/upload/burnbootloader.go
commands/upload/programmers_list.go
commands/upload/upload.go

It makes explicit that the function may fails to get the package manager or the library manager.
Just a refactoring of internal functions
No changes

Return `error` instead of `nil` in package/library manager getters

---

commands/compile/compile.go
docs/UPGRADING.md
docs/configuration.md
internal/arduino/builder/build_options_manager.go
internal/arduino/builder/builder.go
internal/arduino/cores/cores.go
internal/arduino/cores/packagemanager/loader.go
internal/arduino/cores/packagemanager/package_manager.go
internal/cli/configuration/directories.go
internal/integrationtest/compile_4/compile_test.go
internal/integrationtest/core/core_test.go

After an internal discussion, we have decided that after the refactoring of the legacy builder, is impossible to maintain the old arduino-builder used by the Java IDE.
In the spirit of the upcoming v1.0.0 we're dropping the support of: package_bundled_index.json and builtin_tools_versions.txt for good as the Java IDE is deprecated trying to maintain this legacy part doesn't bring any relevant value.

Drop support of package_bundled_index.json and builtin_tools_versions.txt

---

install.sh

Fix the `install.sh` script that broke: https://github.com/arduino/arduino-cli/issues/2483
Since we are going to prefix a `v` in the version tag to follow golang standards about publishing modules versions, the `v` should be removed from the download link.
```
$ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
Installing in /home/megabug/bin
ARCH=64bit
OS=Linux
Using curl as download tool
Downloading https://downloads.arduino.cc/arduino-cli/arduino-cli_v0.35.0_Linux_64bit.tar.gz
Did not find a release for your system: Linux 64bit
Trying to find …
```

Fix install.sh for versions targs with `v` prefixed

---

internal/integrationtest/config/config_test.go

test: add missing file close

---

commands/instances.go
commands/internal/instances/instances.go
internal/arduino/builder/internal/detector/detector.go
internal/arduino/libraries/librariesmanager/librariesmanager.go
internal/arduino/libraries/librariesmanager/librariesmanager_test.go

This is a code refactoring to improve `librariesmanager` package.
No user-visible changes
No user-facing API change

refactoring: Added `LibrariesManager.Clone()` / Auto-scan libs on `LibrariesManager.Build()`

---

commands/daemon/settings.go
commands/daemon/settings_test.go

It is not possible to merge empty values to delete elements inside the configuration.
It is possible to delete non-defaults elements inside the configuration using an empty value. A full json configuration must be passed to the merge command.

Allow empty configuration merging

---

DistTasks.yml

Bumping the cross-build container to have the latest security fix of golang

[skip-changelog] update the build container to use go 1.21.6

---

commands/compile/compile.go
internal/arduino/builder/builder.go
internal/integrationtest/compile_3/compile_env_var_test.go
internal/integrationtest/compile_3/testdata/printenv/.gitignore
internal/integrationtest/compile_3/testdata/printenv/main.go

Fix `ARDUINO_USER_AGENT` env var.
The `ARDUINO_USER_AGENT` is not set during the build.
The `ARDUINO_USER_AGENT` is set during the build.
No
Should fix #2499

Fixed missing `ARDUINO_USER_AGENT` env var setting.

---

commands/instances.go
internal/arduino/sketch/profiles.go

Do not panic if a sketch profile has a syntax error.
```
~/Arduino/Blink$ cat sketch.yaml 
profiles:
uno:
fqbn: arduino:avr:uno
platforms:
- platform: arduino:avr (aaaa1.8.6)
~/Arduino/Blink$ arduino-cli compile --profile uno 
panic: profiles parsing err: si è verificato un errore durante il parsing dei vincoli di versione: no major version found
goroutine 1 [running]:
github.com/arduino/arduino-cli/internal/arduino/sketch.(*projectRaw).getProfiles(0xc000500000)
/home/megabug/Workspace/arduino-cli/internal/arduino/sketch/profiles.go:85 +0x1fe …
```

bugfix: do not panic if a sketch profile has a syntax error

---

internal/cli/compile/compile.go

Adds the `--jobs/-j` to the command line interface to allow fine-tuning the number of parallel threads used during compilation.
The gRPC API is unchanged because it already had this parameter available.
Using Arduino CLI as a command line app, the number of parallel jobs was fixed to the number of available CPU cores in the system.
The maximum number of cores can be tuned with `--jobs/-j` flag.
No

Added `--jobs/-j` flag to `compile` command

---

docs/FAQ.md
internal/arduino/cores/fqbn.go
internal/arduino/cores/fqbn_test.go

Each field of the `fqbn` is checked to verify if it contains invalid characters.
No

[skip-changelog] Improve the definition of FQBN and explicitly state which characters are allowed

---

internal/cli/config/config.go
internal/cli/config/get.go
internal/integrationtest/config/config_test.go

Feature addition
There are `config` commands to `add`/`set` individual settings, but retrieving settings requires the user to `dump` all settings and parse the output with either JSON/YAML to retrieve an individual.
With the addition of a `config get` command, the user can retrieve individual configuration settings without having to parse JSON/YAML.
Not a breaking change
None

add "config get" command to print settings values

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml

~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
~~- [ ] Docs have been added / updated (for bug fixes / features)~~
~~- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)~~
~~- [ ] `configuration.schema.json` updated if new parameters are added.~~
infra change
We currently use statically generated credentials to access to s3 buckets.
OpenID Connect allows workflows to exchange short-lived tokens directly from your cloud provider (see [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about- …

[skip-changelog] use OIDC to retrieve the credentials

---

commands/debug/debug_info.go
commands/debug/debug_test.go
internal/integrationtest/debug/debug_test.go

Allow optional `programmer` in debugging.
Normally configurations for debugging are layered one over the other in the following order:
* `platforms.txt`
* `boards.txt` (the part relative to the board selected)
* `boards.txt` (the parts relative to the board options selected)
* `programmers.txt` (the part relative to the programmer selected)
BTW some platforms seem to have managed to go without the `programmers.txt` facility. This is a tentative fix to support them.
The CLI will fail to debug with the `missing programmer` error.
The CLI will try to proceed with the debugging anyway. …

Allow empty programmer in `debug` command

---

commands/debug/debug_info.go
commands/debug/debug_test.go
internal/integrationtest/debug/debug_test.go

This is a cherry-pick of https://github.com/arduino/arduino-cli/pull/2540 from the 0.35.x branch

Allow optional programmer in `debug` command

---

.github/workflows/release-go-task.yml

https://github.com/ncipollo/release-action/issues/208#issuecomment-1398625039
~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
~~- [ ] Docs have been added / updated (for bug fixes / features)~~
~~- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)~~
~~- [ ] `configuration.schema.json` updated if new parameters are added.~~
Bug fix
After #2541 the release CI is not working anymore: 
```
Run ncipollo/release-action@v1
Error: Error 403: Resource not accessible by integration
```
The release pipeline should be able to push again …

fix ncipollo/release-action not being able to write

---

internal/arduino/cores/packagemanager/profiles.go

Just a small warning fix detected by the go linter:
```
if err != nil {
~~~~~~~~~~
```
Impossible error condition `nil != nil`

Fixed linter warning

---

install.sh

The error message that is displayed when the `install.sh` script does not find the `arduino-cli` binary has been made clearer.
No changes.
No

[skip-changelog] Improve `install.sh` error message when the CLI binary is not found

---

.github/workflows/check-go-task.yml
.golangci.yml
commands/instances.go
internal/cli/feedback/warn_deprecated.go

Bump golangci-lint to v1.57.x, and disable autofix

[skip-changelog] bump golangci-lint to v1.57.x

---

internal/arduino/discovery/discoverymanager/discoverymanager.go

Fix a bug in the discovery manager.
No change
No

Fixed extremely rare race condition in DiscoveryManager

---

docs/sketch-build-process.md

Fix a link that reports 404 in the documentation.

Fixed broken link (failing `check-links` test)

---

docs/sketch-project-file.md

Docs fix
The [sketch project file documentation](https://arduino.github.io/arduino-cli/0.35/sketch-project-file/) includes [a demonstration of a complete project file](https://arduino.github.io/arduino-cli/dev/sketch-project-file/#build-profiles:~:text=field%20is%20optional.-,A%20complete%20e …

[skip-changelog] Correct profile dependency version constraint format in demo sketch project file

---

.github/dependabot.yml

We use the `[skip-changelog]` prefix to avoid having such commits in our
changelog history.
When merging dependabot PRs we always manually add the prefix, but it's
common to forget about it at the cost of manually removing that entry in
the changelog when publishing a new release.
With this PR dependabot will add that prefix in every commit, the GH PR
will be open with the same commit name, and when pressing the `merge squash`
we won't need to add the prefix manually.

Add [skip-changelog] prefix to dependabot commit

---

.github/workflows/check-certificates.yml
.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml

Infra change
The certificate used to sign windows binaries is expiring, and the provider no longer ships a digital one.
We have setup a local runner used to sign.
no
TODO:

use eToken for signing

---

.licenses/go/go.bug.st/downloader/v2.dep.yml
commands/instances.go
commands/service_library_download.go
commands/service_platform_download.go
commands/service_platform_install.go
commands/service_platform_upgrade.go
go.mod
go.sum
internal/arduino/cores/packagemanager/download.go
internal/arduino/cores/packagemanager/install_uninstall.go
internal/arduino/cores/packagemanager/profiles.go
internal/arduino/httpclient/httpclient.go
internal/arduino/resources/download.go
internal/arduino/resources/helpers_test.go
internal/arduino/resources/index.go
internal/arduino/resources/resources_test.go

Allows the cancellation of a gRPC call involving a download.
If a gRPC call is blocked in a slow download, it cannot be interrupted. Even if the gRPC call is canceled, the download will continue in the background.
Closing a gRPC call will terminate the download process immediately.
No
Fix #2595

gRPC: allow cancellation of downloads

---

docs/CONTRIBUTING.md
docs/integration-options.md
package-lock.json
package.json

Force the use of the same prettier version as in the CI.
The CI may use a more recent version of the `prettier` tool since it's installed fresh at each run.
The local task now forces the update of the `prettier` tool if available.

Force the use of the latest prettier in `general:format-prettier` task

---

.github/workflows/release-go-task.yml

Remove auto-update to homebrew from release workflow since `arduino-cli` is now added to homebrew's autobump:
https://github.com/Homebrew/homebrew-core/pull/174456/files#diff-895127b46978b016c724afe1fe53341d3d25253eead3b82d796b9bd72aa0c9a9R79

Remove auto-update to homebrew from release workflow

---

main.go

Prints configuration warnings in text mode only if running one of the `config ...` commands.
Previously if there was an error in the configuration file, the warning was printed on all commands run from the cli.
In JSON mode the warning is always returned.
Also improve the error message from:
```
schema not defined for key 'asdasd'
```
to
```
Invalid value in configuration: schema not defined for key 'asdasd'
```
```
$ arduino-cli version 
schema not defined for key 'asdasd'
arduino-cli  Version: 0.0.0-git Commit:  Date: 
$ arduino-cli version --json
{
"Application": "arduino-cli", …
```

Silence "config warnings" in text mode, except for `config ...` commands

---

internal/cli/configuration/defaults.go
internal/go-configmap/cli.go
internal/integrationtest/config/config_test.go

Fixes a regression of release 1.0.0: setting more than one URL via `ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS` was impossible.
```
$ export ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS="https://espressif.github.io/arduino-esp32/package_esp32_index.json https://arduino.esp8266.com/stable/package_esp8266com_index.json"
$ arduino-cli config get board_manager.additional_urls
- https://espressif.github.io/arduino-esp32/package_esp32_index.json https://arduino.esp8266.com/stable/package_esp8266com_index.json
```
The configuration is incorrect because the two URLs are concatenated in a single string. …

fix regression: setting 3rd party URL via `ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS` env var

---

internal/cli/arguments/fqbn.go
internal/cli/arguments/port.go
internal/cli/monitor/monitor.go

If a port cannot be identified (i.e. can not be associated with a board) the current version of the CLI requires to specify a board with the `-b` flag. Previously this wasn't necessary and the monitor would sometimes fail to work because it may require special `dtr` / `rts` settings.
This PR now reverts the old behavior that is more convenient but also adds a warning to the user when the board can not be identified and the default settings may not work as expected.
```
$ arduino-cli board list
Port       Protocol Type        Board Name FQBN Core
/dev/ttyS4 serial   Serial Port …
```

regression: allow `monitor` to not require to specify the board if the port cannot be identified.

---

docs/platform-specification.md

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [NA] `configuration.schema.json` updated if new parameters are added.
Docs fix
The platform developer can [associate port properties with a board definition](https://arduino.github.io/arduino-cli/dev/pluggable-discovery-specification/#board-identification) in order to cause Arduino CLI to identify ports having those properties as that board.
The [list format](https://pkg.go.dev/github.com/arduino/go-properties-orderedmap#Map.Ext …

[skip changelog] Correct format of `upload_port` identification properties in snippet

---

install.sh

I run install.sh on freshly installed Ubuntu so did not have curl installed as most people do, so it fallback to wget, but there was a bug in getFile(). Here is correction.

install.sh to work with wget

---

commands/service_board_list.go
internal/cli/arguments/port.go
internal/cli/board/list.go
internal/integrationtest/daemon/daemon_test.go

The gRPC streaming call `BoardListWatch` does not persist until the client cancels the gRPC call. Instead the call is immediately canceled server side. This is a regression introduced in CLI 1.0.0. 
The gRPC call `BoardListWatch` is canceled server-side almost immediately.
The gRPC call `BoardListWatch` runs until it is canceled client-side.
No

grpc: fixed BoardListWatch streaming call

---

docs/UPGRADING.md

Documentation update
Previously, the `config dump` CLI command returned the effective configuration, including both the values explicitly set via the [configuration file](https://arduino.github.io/arduino-cli/1.0/configuration/#configuration-file) and [environment variables](https://arduino.github.io/arduino-cli/dev/configuration/#environment-variables) as well as the values provided by defaults.
It was changed to only return the explicitly set configuration data (https://github.com/arduino/arduino-cli/commit/1fddba76a15360b083f457c1028065f764747b10). The breaking change was not documented at that time.
The breaking change is documented in the "Upgrading" document in compliance with the project's development policies.
The new approach for getting the effective configuration values is also …

 Document breaking change to `config get` command output

---

.github/workflows/check-go-dependencies-task.yml
.github/workflows/publish-go-nightly-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/release-go-task.yml
.github/workflows/sync-labels.yml
.github/workflows/test-go-task.yml

Updates the artifacts-related actions to the latest version:
* [actions/upload-artifact@v4](https://github.com/actions/upload-artifact)
* [actions/download-artifact@v4](https://github.com/actions/download-artifact)
* [geekyeggo/delete-artifact@v5](https://github.com/geekyeggo/delete-artifact)
Here the migration guide > https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
If the testing is successful, I will update the [tooling asset repo](https://github.com/arduino/tooling-project-assets) too.

Update artifact-related actions

---

.github/workflows/sync-labels.yml

A small change in the sync-label workflow: the 'name' value `${{ env.CONFIGURATIONS_ARTIFACT }}` would not match the name of the produced intermediate artifacts. The correct pattern is `${{ env.CONFIGURATIONS_ARTIFACT }}-*`.

Another small gh-action workflow fix.

---

commands/service_board_list.go

It's a bugfix to a regression: the gRPC API call `BoardListWatch` kept the `packagemanager` locked until the watcher was closed.
The `packagemanager` is released right after the board watcher feed is obtained.

regression: Ensure BoardListWatch gRPC call correctly release resources

---

internal/cli/cli.go
internal/cli/configuration/configuration.go
internal/cli/configuration/configuration_test.go
main.go

Adds the `--config-dir` global flag that overrides the default data directory. This command can be used with `config init --dest-dir` to work in an "isolated" environment.
```
$ arduino-cli config init --dest-dir test --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
Config file written to: /home/cmaglie/test/arduino-cli.yaml
$ cat test/arduino-cli.yaml 
board_manager:
additional_urls:
- https://arduino.esp8266.com/stable/package_esp8266com_index.json
$ arduino-cli core update-index --config-dir test/
Downloading index: library_index.tar.bz2 …
```

Added `--config-dir` flag

---

.github/workflows/test-go-task.yml

Since Windows and MacOSX are the slowest to complete this reordering allows us to start the long-running tests early and reduce the overall completion time.

Run integration tests on Linux as latest

---

.github/workflows/check-go-dependencies-task.yml

A breaking change was made in the 3.2.1 release of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action (https://github.com/actions/upload-artifact/issues/602), without doing a major version bump as would be done in a responsibly maintained project. The action now defaults to not uploading "hidden" files.
This project's "**Check Go Dependencies**" workflow uses the [**Licensed**](https://github.com/github/licensed) tool to check for incompatible dependency licenses. The dependencies license metadata cache used by **Licensed** is stored in a folder named `.licensed`.
In order to facilitate updates, the workflow uploads the generated dependencies license metadata cache as a [workflow artifact](https://docs.github.com/actions/writing-workflows/choosing-what-you …

[skip changelog] Configure actions/upload-artifact action to upload required hidden files

---

docs/package_index_json-specification.md
internal/arduino/cores/tools.go
internal/arduino/cores/tools_test.go

Hello, I recently successfully built the arduino-cli and Arduino IDE 2.0 on the RISC-V architecture SBC, [Sipeed Lichee Pi 3A](https://wiki.sipeed.com/hardware/en/lichee/K1/lpi3a/1_intro.html), based on the Linux distribution [openKylin](https://www.openkylin.top/index-en.html) that it supports. After testing, this PR allows us to smoothly download packages for the riscv64-linux architecture. This is the first step for Arduino to support the RISC-V platform, and I will submit more PRs in the future to fully support the operation of Arduino in a RISC-V architecture desktop …

Add riscv64 linux tools download support

---

.licenses/go/github.com/arduino/pluggable-discovery-protocol-handler/v2.dep.yml
go.mod
go.sum

Updates the pluggable-discovery client library.
In some circumstances the pluggable-discovery client panics (in particular if the discovery crashes on startup).
The crashing discovery is handled gracefully.
No
Upstream fix https://github.com/arduino/pluggable-discovery-protocol-handler/pull/50
Fix #2665

Updated pluggable-discovery-protocol-handler library

---

.github/dependabot.yml

Disable the auto-rebase feature on pull requests opened by dependabot.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
Any change made on `master` will trigger a rebase on all PR opened by dependabot. If a bunch of pending PR is opened, this will trigger a storm of integration tests that will keep the available runners busy for a long time.
Dependabot should not auto-rebase on `master`.

Disable auto-rebase on dependabot PR

---

commands/service_monitor.go
internal/cli/daemon/daemon.go
internal/integrationtest/daemon/daemon_concurrency_test.go

Fix a deadlock in the gRPC `Monitor` command that keeps the package manager busy for no reason.
While a call to gRPC `Monitor` command is running, other calls may be blocked, in particular the `Init` call. This lead to the Arduino IDE bug described in #2719 
The `Monitor` command doesn't lock the package manager anymore.
No
Fix #2719

Fix monitor init handling

---

internal/cli/daemon/daemon.go
internal/cli/daemon/interceptors.go

* Increase gRPC message size limit from 4MB to 16MB
* Added `--max-grpc-recv-message-size <SIZE>` flag to `daemon` command
gRPC message size limit is 4MB
gRPC message size limit is 16MB
No
Fix #2718

Increased gRPC message size limit to 16MB / added CLI flag to set the value

---

install.sh

This is an improvement in the `install.sh` script to support more platforms. For example, Termux is an Android terminal emulator which doesn't follow conventional UNIX file system, which means `/tmp` folder does not exist. Although, `$TMPDIR` is a variable that can be used to reference the `/tmp` equivalent in Termux.
The current behavior of the `install.sh` script is that it crashes when running from Termux, as the installer tries to write the installation files in a folder that doesn't exist (`/tmp`).
A new variable `$TEMPDIR` is defined based on some default variables that holds …

Set installer tmp path to env var

---

go.mod
internal/arduino/builder/internal/utils/ansi_others.go
internal/arduino/builder/internal/utils/ansi_windows.go
internal/arduino/builder/internal/utils/utils.go
internal/integrationtest/compile_4/lib_caching_test.go

As reported in #2671, the compile cache is not reused on a Windows machine if a non-ASCII character is present in the path.
EDIT: This is due to a weird encoding used by GCC in writing the `.d` file. It seems the file is written the default encoding with ANSI "codepages". This patch leverages the [MultiByteToWideChar](http://msdn.microsoft.com/en-us/library/dd319072(VS.85).aspx) API to properly decode the .d files.
Already compiled files are **not** reused on a Windows machine if a non-ASCII character is present in the path.
Already compiled files **are reused** on a Windows machine …

Fixed compiler-cache on Windows when there are non-ASCII characters in file path

---

.github/workflows/publish-go-nightly-task.yml
.github/workflows/release-go-task.yml

Bug fix
GitHub Workflows are used to automatically generate and publish production and nightly releases of the project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
GitHub Actions …

Fix collision between macOS workflow artifacts in release workflows

---

commands/service_upload.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/daemon/upload_test.go
internal/mock_avrdude/.gitignore
internal/mock_avrdude/main.go

If an `Upload` gRPC request is canceled, the underlying upload tool is terminated immediately.
In particular, this affects the Arduino IDE "cancel" button, because the IDE can only cancel the `Upload` gRPC request and has no control over the underlying upload tool.
If an `Upload` gRPC request is canceled, the underlying upload tool is NOT terminated, and it may take a very long time to timeout and close itself.
The upload tool is terminated immediately.
Related to:
* https://github.com/arduino/arduino-ide/issues/2517
* https://github.com/arduino/arduino-ide/issues/1199

gRPC: if an `Upload` request is canceled, immediately terminate the upload tool process.

---

internal/arduino/resources/checksums.go
internal/arduino/resources/resources_test.go
internal/integrationtest/core/core_test.go

As requested in #2332 
> Do not error if the downloaded file size doesn't match the size value in the index.
> 🙂 Users will no longer suffer when package developers fail to correctly set a size value.
If a downloaded file has an incorrect size written in the index (but a correct checksum), it will fail to download.
If a downloaded file has an incorrect size written in the index (but a correct checksum), it will download successfully.
No
Fix #2332

Do not fail if downloaded file has good checksum but incorrect size.

---

commands/instances.go
commands/service.go
commands/service_settings_test.go
internal/cli/configuration/defaults.go
internal/cli/configuration/locale.go
internal/i18n/detect_windows.go
internal/integrationtest/config/config_test.go

Fixed incorrect locales detection.
```
$ LANG=it arduino-cli
Arduino Command Line Interface (arduino-cli).
Usage:
arduino-cli [command]
Examples:
arduino-cli <command> [flags...]
Available Commands:
board           Arduino board commands.
burn-bootloader Upload the bootloader.
cache           Arduino cache commands.
compile         Compiles Arduino sketches.
completion      Generates completion scripts
config          Arduino configuration commands.
core            Arduino core operations.
daemon          Run the Arduino CLI as a gRPC daemon.
debug           Debug Arduino sketches. …
```

Fixed locales (translations) not being detected with default config

---

.github/workflows/check-protobuf-task.yml
.github/workflows/publish-go-nightly-task.yml
.github/workflows/publish-go-tester-task.yml
.github/workflows/release-go-task.yml
Taskfile.yml

It uses the `buf export` function to produce the protoc.zip artifact content. `buf` will automatically include all the dependencies.
The export was missing the `google/rpc/status.proto`
Future exports will have the missing `google/rpc/status.proto` file again.
Fix #2755

Fixed protoc.zip release artifact missing `google/rpc/status.proto`

---

commands/service_compile.go

This PR fixes a concurrency problem in `Compile`. When a compile is run, the function will keep the Boards Manager locked for the duration of the compile. This prevents another compile from running in parallel.
This is mostly theoretical since the Arduino IDE does not allow starting two compilations together. BTW, there is another scenario that could be impacted: when the Arduino IDE starts the language server, the language server is required to run a bootstrap compilation in the background, and this compilation may prevent the user from compiling for some seconds.
The package …

In `compile` command try to release the package manager lock ASAP

---

commands/service_compile.go
internal/integrationtest/compile_1/compile_test.go

Fixes the export-dir, when it tries to copy a folder it crashes.
The copy mechanism fails to copy the dir because it's treated as a file, and the compile exits with error code 1
We filter out the directories and copy only exported binaries files.

compile: fix export when artifacts contains a folder

---

Taskfile.yml

Makes `task protoc` handle some common cases.
* `task protoc` fails if the `buf format` changes the formatting of the protoc files, since the other tasks are run in parallel the .proto files may be changed while being read by other processes:
```
$ task protoc
task: [protoc:breaking-change-detection] buf breaking --against '.git#branch=origin/master,subdir=rpc'
task: [protoc:format] buf format --write --exit-code
task: [protoc:check] buf lint
task: [protoc:compile] buf dep update
Failure: context canceled
Failure: context canceled
Failure: context canceled
```
* `task protoc:format` …

Small improvements in Taskfile about protocol buffer generation

---

internal/arduino/builder/preprocess_sketch.go
internal/integrationtest/compile_3/compile_test.go
internal/integrationtest/compile_3/testdata/blink_with_error_directive/blink_with_error_directive.ino

Fix the error output during sketch preprocessing wrongly redirected to stdout instead of stderr.
```
$ arduino-cli compile -b arduino:avr:uno 
/home/megabug/Arduino/Blink/Blink.ino:1:2: error: #error eeee
#error eeee
^~~~~
$ arduino-cli compile -b arduino:avr:uno 1> /dev/null 
Error during build: exit status 1
```
```
$ arduino-cli compile -b arduino:avr:uno 
/home/megabug/Arduino/Blink/Blink.ino:1:2: error: #error eeee
#error eeee
^~~~~
$ arduino-cli compile -b arduino:avr:uno 1> /dev/null 
/home/megabug/Arduino/Blink/Blink.ino:1:2: error: #error eeee
#error eeee
^~~~~
Error during …
```

fix: Sketch preprocessing errors were displayed on stdout instead of stderr

---

commands/instances.go
commands/service_library_install.go
commands/service_platform_install.go
commands/service_platform_upgrade.go
docs/configuration.md
internal/arduino/cores/packageindex/index.go
internal/arduino/cores/packagemanager/install_uninstall.go
internal/arduino/cores/packagemanager/profiles.go
internal/arduino/resources/install.go
internal/arduino/resources/install_test.go
internal/cli/configuration/board_manager.go
internal/cli/configuration/configuration.schema.json
internal/cli/configuration/defaults.go
internal/integrationtest/core/core_test.go

We have added a new configuration option, `board_manager.enable_unsafe_install,` to allow the installation of platforms/tools that do not pass the checksum test. This option has been added to ease the platform's development phase, relieving the developer from having to regenerate the index every time, and is not intended for use in production environments.
If a platform fails the checksum test, it will not be installed:
```
$ arduino-cli core install GD32Community:gd32
Downloading packages...
[...]
Installing platform GD32Community:gd32@0.0.1...
Error during install: Cannot install …
```

Added option to disable integrity checks in `core install` (for development purposes)

---

commands/instances.go
internal/integrationtest/config/config_test.go

Fix the panic reported in #2786
The `arduino-cli` panics by reproducing the steps described in #2786 
```
$ arduino-cli update-index
Error initializing instance: Invalid additional URL: parse "foo=https://arduino.esp8266.com/stable/package_esp8266com_index.json": first path segment in URL cannot contain colon
Downloading index: package_index.tar.bz2 downloaded                                                                                                                           
Downloading index: foo=https://espressif.github.io/arduino-esp32/package_esp32_index.json Unable to …
```

Fixed panic if malformed 3rd party url is specified

---

commands/instances.go
commands/service_board_identify.go
commands/service_board_identify_test.go
commands/service_check_for_updates.go
commands/service_library_download.go
internal/arduino/resources/helpers_test.go
internal/cli/configuration/network.go
internal/cli/configuration/network_test.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/core/core_test.go
internal/integrationtest/daemon/daemon_test.go
internal/integrationtest/http_server.go

Bug fix
The user agent does not specify if the CLI runs in daemon mode. It is always something like `arduino-cli/git-snapshot (amd64; windows; go1.23.2) Commit:84fc413a`.
The user agent obtained from the context metadata is propagated to the`network.user_agent_ext` if it's empty and the CLI runs in daemon mode. The complete user agent is `arduino-cli/git-snapshot arduino-ide/2.3.4 grpc-node-js/1.9.5 daemon (amd64; windows; go1.23.4) Commit:f3dc127e`.

Add metadata retrieved from the `context` to the user agent when a new HTTP client is created

---

commands/service_compile.go
internal/arduino/builder/archive_compiled_files.go
internal/arduino/builder/builder.go
internal/arduino/builder/compilation.go
internal/arduino/builder/core.go
internal/arduino/builder/internal/detector/detector.go
internal/arduino/builder/internal/preprocessor/ctags.go
internal/arduino/builder/libraries.go
internal/arduino/builder/linker.go
internal/arduino/builder/logger/logger.go
internal/arduino/builder/preprocess_sketch.go
internal/arduino/builder/recipe.go
internal/arduino/builder/sizer.go
internal/arduino/builder/sketch.go
internal/cli/compile/compile.go
internal/integrationtest/compile_3/compile_verbosity_test.go

* It makes the compile output completely silent if the `--quiet` flag is specified and the compile has no errors.
* It removes the recap table if the build is successful and no `--verbose` or `--quiet` flags have been provided.
* Adds the `-q` shortcut to the `--quiet` flag
Command line | A successful build shows | A build with errors shows
-------------------|-------------|-------------
`arduino-cli compile` | Sketch size | Sketch size, used libraries
`arduino-cli compile -v` | Build commands, sketch size, used libraries | Build commands, sketch size, used libraries
`arduino-cli …

Suppress compile summary stats if `--quiet` flag is set on `compile`.

---

docs/package_index_json-specification.md

`x86_64-migw32` --> `x86_64-mingw32`

fix(docs): typo in suggested host value

---

internal/arduino/libraries/librariesmanager/install.go
internal/integrationtest/lib/lib_test.go

Fixes library install from git-url when reference points to a git branch.
Using the `--git-url` option with a specific branch gives error
```
Error installing Git Library: Library install failed: reference not found
```
Library installs correctly
No
Fix #2825

Fixed library install from git-url when reference points to a git branch

---

internal/integrationtest/daemon/daemon_test.go

It's a debugging of an intermittent integration-test failure.
The following test fails:
```
=== RUN   TestDaemonUserAgent
{
"IP": "127.0.0.1",
"Port": "50051"
}
>>> Create() -> instance:{id:1}
>>> Init(instance:{id:1})
INIT> &{download_progress:{start:{url:"https://downloads.arduino.cc/libraries/library_index.tar.bz2"  label:"Downloading index: library_index.tar.bz2"}}}
INIT> &{download_progress:{update:{downloaded:3397585  total_size:3397585}}}
INIT> &{download_progress:{end:{success:true}}}
INIT> &{download_progress:{start:{url:"https://downloads.arduino.cc/packages/package_index.ta …
```

Investigate some integration-test failures

---

commands/service_sketch_new.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/daemon/daemon_test.go

Fix a nil pointer 
When the `directories.user` is not set by the user, an empty string is returned instead of using the default value. This leads to a panic
Use the `UserDir` function that correctly fallback to default dir in case of empty string.

Fix NewSketch crash when directories.user is not set

---

.github/workflows/check-easyjson.yml
.github/workflows/check-go-dependencies-task.yml
.github/workflows/check-go-task.yml
.github/workflows/check-i18n-task.yml
.github/workflows/check-markdown-task.yml
.github/workflows/check-mkdocs-task.yml
.github/workflows/check-protobuf-task.yml
.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
.github/workflows/i18n-weekly-pull.yaml
.github/workflows/publish-go-tester-task.yml
.github/workflows/test-go-task.yml
.golangci.yml
.licenses/go/golang.org/x/crypto/hkdf.dep.yml
.licenses/go/golang.org/x/crypto/sha3.dep.yml
DistTasks.yml
go.mod

Upgrade golang version to 1.24.1

---

internal/arduino/libraries/librariesmanager/install.go
internal/integrationtest/lib/lib_test.go

A previous "fix" allowed the installation of a library from git by specifying a branch, but introduced a regression, making it impossible to install from git by specifying a revision hash.
A library can not be installed from git using a revision hash, see https://github.com/arduino/arduino-cli/issues/2860 for details
It is now allowed to install from git using a revision hash.
Fix https://github.com/arduino/arduino-cli/issues/2860

fix: allow lib-install from git using revision hash as a reference

---

internal/arduino/cores/packagemanager/package_manager.go
internal/arduino/cores/packagemanager/package_manager_test.go

We correctly pass the downloader config during the `Build()` of the package manager
Currently, the downloader config is not passed when building the final package manager. This led to ignoring user network configs.
We correctly pass the downloader configs.

 Fix user network config being ignored in package manger operations

---

docs/index.md

Fix readme notice about CLI versioning

---

.github/workflows/release-go-task.yml

The `task dist:macos_ARM64` requires an arm64-based runner.
This change should fix the build task on the release workflow.
Related to #2850 
https://github.com/arduino/arduino-cli/pull/2850/files#diff-6b9acae2ec2dd8380951f75b0526e9c2f71976d513236d60e40d0f3dba275654

[skip changelog] Fixed release workflow build

---

package-lock.json
package.json

Update the project's [**markdown-link-check**](https://github.com/tcort/markdown-link-check) tool dependency to the latest version.
The **markdown-link-check** tool is used to check for broken links in the documentation hosted in this repository. This tool is managed via the npm package …

[skip changelog] Bump markdown-link-check from 3.10.3 to 3.13.7

---

.markdown-link-check.json

This reverts commit f470f407a3afca82e30c6503b421ddde694c7b6d.
This configuration entry was previously required in order to work around a bug in the [**markdown-link-check**](https://github.com/tcort/markdown-link-check) tool (https://github.com/tcort/markdown-link-check/issues/202) that resulted in false positives for links to anchors created by HTML anchor tags.
The bug in the "markdown-link-check" tool has since been fixed (https://github.com/tcort/markdown-link-check/pull/331), and this project updated to use the version of the tool with that fix (https://github.com/arduino/arduino-cli/pull/2898). So this configuration entry is no longer required.
The now superfluous configuration entry is hereby removed in order to ensure more comprehensive link check coverage.

[skip changelog] Revert "Disable internal anchor checks by link checker tool (#1692)"

---

docs/configuration.md

Docs update
A reference to Arduino CLI's `directories.downloads` configuration key in the documentation is misspelled as "directories.download".
The configuration key name is correctly spelled.
No breaking change
Originally reported at https://forum.arduino.cc/t/configuration-file/1378100/7

[skip changelog] Correct configuration key name in documentation

---

mkdocs.yml

Bug fix
The project is supplemented by [a documentation website](https://arduino.github.io/arduino-cli/latest/) which is generated by the [**MkDocs**](https://www.mkdocs.org/) static site generator. The site contains a navigation panel which lists the available documentation pages.
Rather …

[skip changelog] Add missing pages to website navigation panel

---

docs/FAQ.md
docs/package_index_json-specification.md
docs/platform-specification.md

Docs update
Arduino CLI restricts which characters are supported for use by platform developers in their vendor, architecture, board, custom board menu, and custom board option identifiers:
https://github.com/arduino/arduino-cli/blob/faf79a7d088e6fe503530ab29cb84ba3a7252657/pkg/fqbn/fqbn.go#L45-L93
This information is only documented(?) in the "FAQ" …

Move information re: allowed characters for FQBN component to specifications

---

internal/arduino/builder/internal/preprocessor/gcc.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/compile_5/recusive_include_test.go
internal/integrationtest/compile_5/testdata/SketchWithRecursiveIncludes/SketchWithRecursiveIncludes.ino
internal/integrationtest/compile_5/testdata/SketchWithRecursiveIncludes/a.h

Previously, compiling a sketch containing an include loop could generate a lot of output and crash the Arduino CLI with an out-of-memory error. This is due to the library-discovery process that buffers the stderr output of the compiler for analysis after the process exits.
To fix this problem, a limit to the compiler output has been set to 100KB of data.
```
$ cat sketch.ino
#include <a.h>
$ cat a.h
#include <a.h>
#include <a.h>
#include <a.h>
$ arduino-cli compile -b arduino:avr:uno
```
The process never terminates, and it's killed for OOM later by the kernel.
```
$ cat sketch.ino …
```

bugfix: Kill compile processes that generates too much output

---

commands/cmderrors/cmderrors.go
commands/service_platform_install.go
internal/arduino/cores/packagemanager/download.go

Improve error code when platform not available for OS

---

internal/arduino/builder/internal/preprocessor/ctags.go
internal/arduino/builder/internal/preprocessor/ctags_test.go

Fixes https://github.com/arduino/ArduinoCore-zephyr/issues/140
When parsing the preprocessed file, only the lines relevant for the sketch are preserved.
However, golang's `scanner` fails if a line is too long for its buffer.
Overcome the issue by adding a 1MB buffer (extremely conservative) and a non-fatal error message in case it's still not enough.
Compiling any sketch from https://github.com/arduino/ArduinoCore-zephyr fails to create prototypes due to `analogPins` macro, which expands into a ~90K characters line
The prototypes are created correctly
No breaking change

ctags: filterSketchSource: enlarge buffer size to handle long lines

---

docs/UPGRADING.md
docs/configuration.md
docs/package_index_json-specification.md

Updated formatting of .md files to new `prettier@3.6.2` standard.
CI fails.
CI pass (hopefully :-)

Updated formatting to new prettier standard

---

DistTasks.yml

Golang supports cross-building by default. With this PR I propose not to use the crossbuild container of Elastic, when we are building without cgo. This will make our build process faster, and we minimize the dependency on Elastic Container at the bare minimum.
The trigger of this PR is that Elastic seem to have broke the manifest of arm images, and we are now blocked by bumping our go version.
We are always using the elastic crossbuild container 
When building without CGO use native golang cross build capabilities

Do not use crossbuild container when CGO=0

---

commands/instances.go
docs/sketch-project-file.md
internal/arduino/cores/packagemanager/profiles.go
internal/arduino/sketch/profiles.go
internal/arduino/sketch/profiles_test.go
internal/arduino/sketch/testdata/profiles/bad_profile_1.yml
internal/arduino/sketch/testdata/profiles/profile_1.yml

The idea is to allow in the `sketch.yml` platforms without a specific version, like the following `giga_any`:
```yaml
profiles:
giga:
fqbn: arduino:mbed_giga:giga
platforms:
- platform: arduino:mbed_giga (4.3.1)
giga_any:
fqbn: arduino:mbed_giga:giga
platforms:
- platform: arduino:mbed_giga      # this does not specify a version
default_profile: giga_any
```
In this case, the Arduino CLI will not download the platform to the internal space, but it will use the globally installed platform.
You must specify a version in the `platform` directive of the `sketch.yml`
You can omit a …

Allow platforms without fixed version in profiles.

---

.github/workflows/release-proto-files.yml
buf.yaml

Pushes proto files when the files change on master and
when we release a new tag

ci: push proto files to buf registry

---

docs/platform-specification.md
internal/arduino/builder/builder.go
internal/arduino/builder/linker.go
internal/arduino/builder/recipe.go
internal/arduino/builder/recipe_test.go

This PR introduces the possibility of using multiple commands for the `c.combine` pattern, and infrastructure that will enable using the same logic on any build step, if so decided. 
Two changes in behavior are introduced:
* When looking for multi-step recipes (e.g. hooks) in `RunRecipe()`, a key that exactly matches `prefix.suffix` is explicitly ignored if numbered entries are found, and only used as a fallback when no other entries are present. 
This change is consistent with current docs that require a `prefix.NNN.suffix` syntax for multi-step recipes. A property named `prefix.suffix` is undefined behavior, and is currently included among the numbered ones.
* Reuse the `RunRecipe` logic for the `recipe.c.combine` step to allow multi-stage linking. The above change in this context means …

linker: allow multi-step link recipe (`c.combine`)

---

internal/integrationtest/arduino-cli.go

Fix a race condition in integration tests.
```
==================
WARNING: DATA RACE
Write at 0x00c0000be080 by goroutine 12:
bytes.(*Buffer).Write()
/home/megabug/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.linux-amd64/src/bytes/buffer.go:176 +0x3a
io.(*teeReader).Read()
/home/megabug/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.linux-amd64/src/io/io.go:630 +0xb7
bytes.(*Buffer).ReadFrom()
/home/megabug/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.linux-amd64/src/bytes/buffer.go:211 +0x10e
io.copyBuffer()
/home/megabug/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.linux-a …
```

Removed race condition in CI tests

---

commands/internal/instances/instances.go
internal/arduino/cores/packagemanager/package_manager.go
internal/integrationtest/arduino-cli.go
internal/integrationtest/board/board_test.go
internal/integrationtest/daemon/discoveries_test.go
internal/mock_serial_discovery/main.go

The Arduino CLI gRPC daemon does not correctly clean up pluggable-discovery processes after a `Destroy` call.
Zombie processes are left.
No zombie processes are left.
No
Fix #1981

fix: Multiple gRPC `Create/Init/Destroy` cycles causes multiple pluggable-discovery zombie process

---

internal/arduino/builder/sketch.go
internal/arduino/builder/sketch_test.go

**Summary**
When a sketch `.ino` is saved as UTF-8 **with BOM**, the three BOM bytes (`EF BB BF`) reach the compiler and cause:
```
stray '\357' in program
stray '\273' in program
stray '\277' in program
```
This PR strips the BOM at read-time so the merged `.cpp` and any copied sources are clean.
Refs: arduino/arduino-ide#2752
---
---
**Bug fix** — make the CLI robust to UTF-8 BOM at the start of `.ino` and additional files.
---
- If a `.ino` is saved as **UTF-8 with BOM**, the BOM bytes are preserved into the merged `.cpp`, leading to compiler errors (`stray '\357' / '\273' / '\277'`).
- This matches IDE issue **arduino/arduino-ide#2752** and appears “random” to users because some editors silently add a …

fix(builder): strip UTF-8 BOM from .ino sources before preprocessing
